### ISSUE TITLE
[v4.1 Bug] Improvement clay pit can not be constructed

### ISSUE THREAD

**Issue by estebanthebad** [We-the-People-civ4col-mod/Mod#1012]
Hi guys!

I think I found a bug. A hardy pioneer can not construct the improvement "clay pit" where it - by all information available - should be possible.

**Version**
Played version is 4.1

**Gamesave**
The gamesave is attached. The mod name was "We The People" in my case.
[bug clay pit AD-1784.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/15253659/bug.clay.pit.AD-1784.zip)

**What did I do?**
- I set up a village next to a tile (hills/tundra) which has the terrain yield "clay". The name of the village is "Inglaterra". It is in the south of the map.
- I brought an expert clay cutter to that village, who is now working that tile and producing clay.
- I sent a pair of hardy pioneers to build a road and a clay pit on that tile.

**The expected result**
- When selecting the pioneers on that tile, there should be a button for building a clay pit.

**The observed result**
- When selecting the pioneers on that tile, there is no button for building a clay pit.

**Screenshots**

Screenshot A shows the city screen with the clay cutter working the tile and clay being produced.

![bug clay pit wtp v4_1 screenA](https://github.com/We-the-People-civ4col-mod/Mod/assets/52369117/2a4351ef-ca26-49db-ac9b-defc8f44b225)

Screenshot B shows the pioneers on the map with no option to build a clay pit.

![bug clay pit wtp v4_1 screenB](https://github.com/We-the-People-civ4col-mod/Mod/assets/52369117/8bf7070e-c71d-4968-8b95-755e657d6ff6)

**Research I did**

Colopedia says there are two requirements for building a clay pit:
- Terrain yield "clay"
- Terrain type "hills"

I also had a brief look at [CIV4ImprovementInfos.xml](https://github.com/We-the-People-civ4col-mod/Mod/blob/Master/Assets/XML/Terrain/CIV4ImprovementInfos.xml) but could not - with my laymans knowledge - spot any further requirements. But when looking at the xml, I also could not spot the requirement, that it can only be built on hills.

**Comment by MatthewForrester** [comment]
I was also affected by this bug. A second look at Civ4ImprovementInfos.xml [shows that the only valid terrains are Marshes and Wetlands](https://github.com/We-the-People-civ4col-mod/Mod/blob/08e1a32a6aaf22c544b6ec5107d759e0bffe69a7/Assets/XML/Terrain/CIV4ImprovementInfos.xml#L2645). The tiles that you and I are trying to build on are Tundra. 

The English Colopedia strategy text [says](https://github.com/We-the-People-civ4col-mod/Mod/blob/08e1a32a6aaf22c544b6ec5107d759e0bffe69a7/Assets/XML/Text/XML_AUTO_UTF8_ImprovementInfo.xml#L1383):

> **Strategy**:
> A **clay pit** can be built only on hills. They increase the production of _clay_.
> **Background :**
> A clay pit is an open-pit mine from which clay is extracted. Clay is generally used for goods and other everyday items.</English>

This could be either a documentation bug (it's intended that Clay Pits can't be built on Tundra, but the Colopedia doesn't mention it) or a scripting bug (the Colopedia is correct and the Clay Pit should indeed be buildable on Tundra Hills). I wondered whether the in-game behaviour was intentional because digging down into permafrost with early modern technology would be more expensive. But the mod already allows Mines to be dug in Tundra and there is the 25% increase in Improvement building time to account for the difficulty. In addition, [the commit that added Clay Pits](https://github.com/We-the-People-civ4col-mod/Mod/commit/1088b57fc31a0dbd02faf5dca4b3fdc957970b6b) suggests that it was done by editing the existing XML for the Quarry, while [clay was only added to Tundra Hills at a later date](https://github.com/We-the-People-civ4col-mod/Mod/commit/770c7237d1b102df1844390fba7bac4a4cceb07a). So it looks like this was just an oversight and the in-game behaviour should be modified to match the Colopedia.

The bug was fixed in the `devel` branch by [this commit](https://github.com/We-the-People-civ4col-mod/Mod/commit/465fc3782303799fe2d450a19d078e0dbafc75ae) a few weeks after 4.1 was released, so this issue can probably be closed.

**Comment by raystuttgart** [comment]
Yeah, it is long solved in the **develop** branch.
