### ISSUE TITLE
"More siblings than memory allocated" errors on startup

### ISSUE THREAD

**Issue by Jasquith88** [We-the-People-civ4col-mod/Mod#1029]
![Colonization WTP Error](https://github.com/We-the-People-civ4col-mod/Mod/assets/173625682/16853d3d-8adc-4127-8fc1-e7a490b6bea7)

I am getting several (about 16) errors regarding allocated memory when trying to load WTP 4.1 (see screenshot.) It did work just fine for a few sessions, but it has now been throwing this error (and several like it) for a little while.

I am playing through Steam and am running the "original unsupported version", as advised. I have tried completely reinstalling steam & Civ4Col, clearing the custom assets folder & redownloading a fresh version of the mod in case I had messed it up in any way, but no luck.

Can anyone shine a light on what's going on and how to fix it please?

Thanks,

John

**Comment by Nightinggale** [comment]
This happens if colonization fails to load CvGameCoreDLL.dll from the mod. On top of the obvious that the file is missing (it should be in Assets), the most common cause of failure is not having tbb.dll and tbbmallc.dll inside the Colonization directory. This can be solved by running setup.bat or manually copying those two files from Copy to Colonization.exe. They should be in the same directory as Colonization.exe.

This is a known issue, but since the failure is that our code doesn't run, it's fairly limited what we can do about this issue.

**Comment by Jasquith88** [comment]
Thanks for the reply; running setup.bat as suggested fixed the issue. Much appreciated! 👍 

Thanks,

John
