### ISSUE TITLE
Drunk-Monk: "Revise the text for key event jungle fire 3 "

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#11]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15011864

**Comment by ErikSandbraaten** [comment]
@raystuttgart This is the missing XML entry that I talked about

**Comment by raystuttgart** [comment]
This TXT_KEY seems to have never existed.
Schmiddie does not know about it, and in RaR 2.5 it did not exist either.

Who created that Event?
He should know and be able to clarify.

Or this was created by the Script for UTF?

I cannot fix it since I have no idea what the text should be ...

**Comment by Nightinggale** [comment]
The UTF conversion script introduced it because by default it assumes each event to have a string. Granted it might be a bit overkill to do it like that, but other mods have problems with people not using TXT_KEYs and instead just write the string in the data xml file. This makes strings untranslatable. I scripted a ban on that approach.

The "script" is actually my GUI editor, which is still under development (it works, but it can't handle non-ascii names like the names of ships in CvCivilizationInfo, which it will then corrupt). The default way to add a new entry will automatically make the TXT_KEYs and fill it out with ????. This is intentionally to avoid lazy modders from not adding TXT_KEYs. Also it's more convenient when working with it.

I have a fix for the "intentionally left blank" strings in the works, which would be my next commit.

**Comment by raystuttgart** [comment]
I think this is long fixed.
I definitely found the XML tag now.

Edit:
Also tested the Event, all fine.
