### ISSUE TITLE
Moving Icebergs

### ISSUE THREAD

**Issue by MichaelQuell** [We-the-People-civ4col-mod/Mod#117]
#114  this issue said it destroys imersion if animals spawn under ice. My sugestion to solve this would be the follwoing: Move the ice in the direction of aequator, inflict like 50% damage to all units on the new plot. The farther it is from the poles the higher the chance it will despawn. Regulary spawn new ice plots near the poles.

**Comment by abmpicoli** [comment]
I believe that to solve the specific problem of #114 , there are simpler solutions... 

But to have icebergs as a new feature, I believe we have precedents in the oceanic storms... 

I'm a little divided about that: at one side, travel through the poles will become much more hazardous, but, on the other side, even if some maps could make poles impossible to travel, if ice shifts between turns, we could find interesting situations at the maps...

**Comment by abmpicoli** [comment]
But thanks for your idea, @MichaelQuell :) Let's see what other people think...

**Comment by ErikSandbraaten** [comment]
I generally welcome ideas that makes maps\"the game world" "more dynamic". This applies to the existing storm features  as well as this novel idea about icebergs. I give my general support to this because it could open up "new" paths near the poles that are sometimes blocked by ice (thanks to the map generator) due to migrating icebergs. This could open up new strategic possibilities. '

As a bonus, we'd have somewhere to properly place polar bears and even (dire) penguins 🤣

**Comment by ErikSandbraaten** [comment]
Concerning the pathfinding, I've seen autoplays where AI cities are already blocked by ice and the only way for ships to access these cities are through an adjacent indian village. Villages close to AI cities  are generally disbanded and thus these cities end up "marooned". Migrating icebergs could actually solve pathing issues for the AI!

**Comment by abmpicoli** [comment]
Well... Forts allow ships to pass through land tiles near water...

**Comment by raystuttgart** [comment]
Seriously, let us not mess with moving ice.
This is not worth it considering effort and performance.
