### ISSUE TITLE
IDEA: Colony Survival Chance 

### ISSUE THREAD

**Issue by civplayer** [We-the-People-civ4col-mod/Mod#129]
One aspect I think Colonization and most mods missed was the difficultly/mystery of early colonization as many early colonies in fact failed. There should be a probability of success failure of the colony. I think this should exist for the early settlements but maybe not later ones

Factors could include:
**latitude of colony**, generally areas away from the poles and the jungle, (this might be hard to implement), proximity to marsh will decrease chance

**relations with natives**- perhaps players would need to exchange something such as gold/tools for food.
If relations are at least +1 this will be positive for the colony with 0 or below having worse consequences.

the taking of native crops/resources
size of colony- every size above 1 increases chance 

**resupply from Europe. ( as colony will not be self sufficient at first, bringing food from Europe will increase chances. 

At the end of 10 turns factors would add up, if a colony's performance rate was below 70% it would vanish. 

As if programmers didnt have a enough work (I must appear awfully inconsiderate as a non programmer) this feature would be enhanced by an event tree of choices that could fire when a colony is settled.  I could not offer anything but writing form this perspective. Also the story/event feature is not necessary for the feature to work. 

Thanks for reading.

**Comment by Nightinggale** [comment]
While historically accurate, I'm not sure I like this idea. The problem I see with it is game balance. Right now there are good places to start and bad places. What you mention about terrain will make the good places even better and the bad places much worse. Also the distance to the polar regions means the game might end up as a gamble. Whoever starts in the middle will most likely win.

In short I'm worried about game balance. However even if it ends up as balanced, I fear it would end up being annoying rather than fun, particularly for inexperienced players.

**Comment by raystuttgart** [comment]
Sorry, I really hate this idea.
Many players might rage-quit because of this.

**Comment by raystuttgart** [comment]
I seriously hate this and would really put a hard no to it.
Let us please forget about that idea and close it.

We should never implement anything if there is one team member really does not like.
(There would be no consense then.)

In this case that is me.

**Comment by Nightinggale** [comment]
I'm not too happy with it either. I fear we won't be able to code it in any way, which will make the game more fun to play. Also even if we can manage to do that, I don't think it would be worth the time because it would likely take forever to set it up in any meaningful way without any risk of backfiring on any random maps.

Also I fear dividing the map even further will end up resulting in a game where players in the middle will gain an unfair advantage. I don't want a game where people start and then restart unless they encounter tropical climate. Likewise if certain events are polar only, the opposite could happen.

It's also not true that whale hunting is arctic thing. Australia used to hunt whales from rowboats near the cost and last time I checked Australia is not far north nor is it particularly cold.
