### ISSUE TITLE
XML setting: remove feature when founding colony

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#152]
Reading #151 made me consider what to do about colony founding and features. In some cases it would make sense to remove and in other cases it would make sense to keep the features.

I have come up with the idea of adding this function:

```cpp
bool CvPlayer::isFeatureRemovedWhenFoundingCity(FeatureTypes eFeature) const;
```

It seems simple enough to use, but the next question is what the function to rely on. I propose CivEffects #93. This will give each player an int array and the feature is removed if the value for the feature is > 0. The values are combined contributions from all the CivEffects owned by the player.

List of planned ways to gain ownership of CivEffects

* Default for all players
* Default for Europeans
* Default for natives
* Default for kings
* CivilizationInfo
* TraitInfo
* Founding Fathers
* Events, both for X turns and permanent
* (list incomplete)

This is all in xml and it allows both quick applying to all players as well as the ability to tailor each player. It allows something like FFH2 where elves and only elves skip clearing forests. Since the CivEffects adds an int, it can be both positive and negative, meaning we can make all players clear forests and then have a trait, which disables clearing. If we add #64, then the setup will be easy and fast.

The xml setup would be a list where each index has a FeatureType and an int. It's 0 unless specified otherwise. In other words the standard list approach in xml.

Note that this proposal does not specify what we should do ingame. It unlocks the ability to try out different settings.

Coding effort (once the CivEffect branch has advanced enough)
* add variable to CivEffectInfo class (3 lines)
* add xml tag loading (1 line)
* add array and get function to CvPlayer (2 lines)
* add cache updating (1 line)

It totals to 7 lines of C++. The CivEffect system is designed to be fast to code and fast at runtime.

**Comment by orlanth** [comment]
That sounds good. For the tags that can apply a civ effect to all players/Europeans/Natives/Kings, a good place for these could be HandicapInfos.xml, since this would allow modders to easily tweak/balance effects across difficulty levels for each of these categories.

If you wanted to be able to mod a "Wonder" type building with a civ-wide effect, it could be neat to have Buildings be able to apply one too.

**Comment by abmpicoli** [comment]
Well, 100% agreement will hardly be possible... I believe we need to place a vote? Or maybe make it a game setting? I'm personally inclined to keep features on, always ... more control to the player...

**Comment by raystuttgart** [comment]
Hi guys, keeping the Feature will reduce YIELD_FOOD.
But that is the most important YIELD in your early city.

Please let us consider carefully before doing something like that.
I really don't like that idea "Cities don't remove Feature" currently because I absolutely don't see how it would improve gameplay for WTP.

**Comment by raystuttgart** [comment]
This would really cause lots of strange issues with Food.
Also it is kind of unimmersive to found a city and not remove a feature.
(i.e. We now have Swamps and such as Features ... ever heard of real cities in a Swamp?)

Let us please close this.
