### ISSUE TITLE
Natives can get their navy...

### ISSUE THREAD

**Issue by NoFreeUsernameDammit** [We-the-People-civ4col-mod/Mod#160]
I'm not sure whether to consider this bug or unexpected feature.

So I started a new game (beta 2) on Marathon, played a bit...turned out that Cortez landed in quite inhospitable land next to Logan. Yeah, that won't end well...they very quickly got into a war, and Logan burned one of his colonies. Result:
![nativenavy](https://user-images.githubusercontent.com/43598424/46350875-34325100-c656-11e8-8971-1d267579af66.jpg)

It's not big issue, though I wonder what'll he do with it.

**Comment by Nightinggale** [comment]
While it's clearly not the intended behavior, I'm a bit careful to label it as a bug because in a way it makes sense that the natives would want to steal ships and try to navigate themselves. Historically some natives realized they were being ripped off and they decided to cross the Atlantic to cut out the middleman in the trade. It didn't go well with their canoes, but it shows the natives had the idea of sailing themselves. It's not farfetched for them to use a ship if they could get away with stealing one.

The question is how the AI will use it.

**Comment by orlanth** [comment]
I like it lol! 😝

In the 2071 mod, to make the “native” alien empires more of a challenge (and also a playable option!) I tried to comment out some parts of the vanilla code that limit/cripple them (e.g. the “native yield destruction” function); and made them able to do some research and manufacturing while still handicapped relative to “European” Earthlings. 🌏 I likely did a poor job with the code, but they did seem to be able to cope fairly effectively (at least by the stand7of vanilla AI) 😛

**Comment by abmpicoli** [comment]
Yeah, i kind of like this feature... It would allow natives to travel overseas to colonies at other islands...

**Comment by NoFreeUsernameDammit** [comment]
Back on CivFanatics, Schmiddie rejected the idea of native ships.  Pity, I feel that it takes the natives spawning on islands out of the game.

And occassionally, the isolation can turn into a little exploit. I've gotten several mounted conquistadors from events in one game because I spent two centuries at war with native tribe that had one village left on small island.

**Comment by raystuttgart** [comment]
By the way guys:
In RaR we had a bug that Natives could get "Free Units" from Founding Fathres if in a Permanent Alliance with another European Players.

I am not sure if this issue still exists.
It could even be that I had fixed it. - It is simply so long ago.

But this issue sounds like a new one.
It seems that "Coastal Transports" (and maybe only those) can be caught by Natives.

If that is the case, I think it could be fixed easily - I even have an idea for a solution already.
I will try to check it and fix it.

**Comment by raystuttgart** [comment]
Hi guys,
I just saw, that you **forgot to forbid** Native AIs to **build** Small Coastal Ships and Large Coastal Ships.
(So it will occassionaly really builds those Units - even if it takes quite long for Native Villages to do so - due to the low rate of Hammer Production.)

Every Native Nations needs to get a **NONE** entry for UNITCLASS in **CIV4CivilizationInfos.xml** (for Units it is not allowed to build / have).

UNITCLASS_SMALL_COASTAL_SHIP
UNITCLASS_BIG_COASTAL_SHIP

This is **really easy to fix** but of course I need to change **CIV4CivilizationInfos.xml**.
I also really think we **should** forbid to build Coastal Ships.

A) It cannot really use them purposely and thus wastes ressources.
B) It will confuse our players because they might think it is a bug.

@Nightinggale :
Could this this cause issues with Savegame compatibility?
Can I do it now and push to "fixes without causing any trouble?

**Edit:**
I also just tested "**Capturing** of Coastal Transports" but that **was / is not any problem**
They do not have ships to attack and capture them on water .
On land - when Native AIs capture a City (with a coastal transport in it) my last change will also make that impossible.

**Comment by ErikSandbraaten** [comment]
This was admittedly an oversight and should definitely be corrected.  I don't think that it will causes issues with savegame compatibility since we're only modifying an existing entry, we're not adding anything.

**Comment by raystuttgart** [comment]
No problem.
I just wanted to **explain / tell for the future**.

Once I hear from @Nightinggale  that it is ok for me to push it to "fixes" I will do it.
(It is not that much effort to correct.)

**About the "canoe" idea:**

Currently Native AI does not really have **any usage** for it and would just waste ressources.
(There is no game mechanic and Native AI logic that would use it.)

It is pointless for Native AIs to ship goods, since it does not have "Production" or Produced Yields. It has only Raw Yields.
It is also quite Pointless for AI to be able to ship Troops currently because it does not do "Coastal Invasions" or anything to conquer other Cities.

In the future, when we might come up with a reason for a "canoe" that might change of course.

**Comment by Nightinggale** [comment]
> Could this this cause issues with Savegame compatibility?

I don't think there would be any savegame related issues in changing the rules regarding which players can build what. We can't _add_ new units, but we have a fair degree of freedom regarding modding existing ones.

My only concern is what happens to colonies actively building a unit, which is no longer allowed to be build? Most likely nothing. It would likely be build and then leave the queue. We might trigger an assert though, but that's not really an issue.

**Comment by raystuttgart** [comment]
Ok great.

Than I will fix that and push to "fixes".
Just wanted to be sure first.
