### ISSUE TITLE
Hunter yields are not shown right:

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#162]
The hunter's yield doesn't appear right at the city screen at the profession popup dialog... it seems the dialog uses the farmer yield, and not the food provided as a hunter.
![image](https://user-images.githubusercontent.com/1733170/46563523-52a77f00-c8d8-11e8-8284-c1a211c0ef1c.png)
![image](https://user-images.githubusercontent.com/1733170/46563550-75d22e80-c8d8-11e8-8f4c-266bcd8234d6.png)

**Comment by Nightinggale** [comment]
Looks like the problem is actually in

```cpp
CvPlot::calculatePotentialProfessionYieldsAmount(YieldTypes eYield, ProfessionTypes eProfession, const CvUnit* pUnit, bool bDisplay)
```

It get the yield production from calling

```cpp
calculatePotentialYield((YieldTypes) eYield, pUnit, bDisplay)
```

The main issue is that it doesn't forward the profession, meaning it will return the production from the most productive profession, not the profession in question.

Two other issues with that function, though they are unrelated to the bug.

For some weird reason it typecasts YieldTypes to YieldTypes.

```cpp
CvProfessionInfo& kProfession = GC.getProfessionInfo(eProfession);
if (eYield != NO_YIELD)
```
Wrong order. If eYield is NO_YIELD, then we won't need kProfession. No need to waste time looking it up. Place it inside the the if statement.

**Comment by Nightinggale** [comment]
The more I look at this, the more it looks like the entire yield generation code assumes one profession => one yield and one yield => one profession.

This might not be trivial to fix, but at the same time I suspect the AI preview of production value could be affected by this as well, meaning while it's "just" a graphical glitch, it does affect game logic elsewhere because the issue is with the core code for yield production prediction.

**Comment by raystuttgart** [comment]
This bug does not exist in current version.
