### ISSUE TITLE
2 new resources - apples (or general fruits) -> cider

### ISSUE THREAD

**Issue by Ignasito** [We-the-People-civ4col-mod/Mod#166]
2 new resources - apples -> cider

apples can be changed to any fruits representing thing that you can turn to ale for example.

**Comment by NoFreeUsernameDammit** [comment]
Moonshine!

There might be-probably would be-issues with technical implementation of resource that could be, after harvesting, used as food or as production material. 

Though...you can make hard alcoholic beverage from virtually any edible plant matter. I wouldn't mind giving distillery another use to convert food to moonshine (new resource, representing generic stong distillate).

Though the number of resources is already quite high. Some time ago, Schmiddie put up a poll about cutting down the resource number...I think that's one thing that should be considered again.

**Comment by Nightinggale** [comment]
We can add as many buildings and yields as we want, but more might not be better. Each time something is considered, the question is: is it a tobacco clone? as in should the player grow something and then use a building to produce something to sell in Europe. We can add a lot of those without actually adding _anything at all_ to the gameplay. In fact it just might make it worse in the sense that it makes the city and yield bars more crowded and instead of 30 tobacco, you end up with 10 tobacco, 10 apples and 10 whatever, but without more cargo slots in the ships.

I would say that an apple plantation improvement wouldn't be a bad idea. Reduce the normal gains from a plot, but adds food. It could be interesting to grow apples in forests on hills where you can't build farms anyway.

**Comment by NoFreeUsernameDammit** [comment]
That reminded me of another little issue. There are a few resources-coconuts, bananas and turkeys-that provide little benefit, as often the tile provides same or better benefit when their forest/jungle requirements are ignored, chopped down and farm built, or they appear on hills where they're virtually impossible to exploit as there is no improvement available that would exploit them, and the food yield is still small.

A generic "fruit plantation" improvement that would be buildable on non-desert hills and special resources like bananas, coconuts and some other fruit-if added-would be great, it would also make the colonies in hills more viable.

**Comment by Ignasito** [comment]
Well actually yeah, you can make tequila from cactus :)

**Comment by ShadesOT** [comment]
I very much agree with what @Nightinggale wrote. One more thread of production is merely a cosmetic, rather than an addition to the gameplay.

The idea of having new tile improvements is interesting. I am indifferent to it though. Because, if there are improvements which enable to grow something on very unfertile plots, what difference does it make, where a city is built? The need to find suitable areas for cities IS a challenging game mechanic and imo should be strengthened rather than weakened.

**Comment by NoFreeUsernameDammit** [comment]
@ShadesOT it could be limited so on hills, such improvement would be available only if coconuts or bananas are present.

**Comment by ShadesOT** [comment]
> it could be limited so on hills, such improvement would be available only if coconuts or bananas are present.

That is a good restriction, ... isn't it allready in the game?




> fertile hills being so bad that non-experts can't even produce more than they eat even with an improvement.

I recall one can build a spice farm, a vine yard or a coca drying tower, which give 2 food to non-experts, and 4 to experts, plus anything that comes from mills. so that is 4+ food per plot on all hills except unfertile ones (desert, tundra, etc ...).




> This isn't about making hills as good as flatland. Instead it's about making colonies in hilly terrain possible.

If not all of the land can be colonized, then it makes the suitable places more valuable. Longer roads have to be built, travel times are longer ... which all leads to a more challenging strategic gameplay.






> Right now if you start a place where natives have taken all the non-hill land, you could be close to starting over.

That is something I do not like either, but I think we rather place less indian villages than make all land colonizable.
On a side note, it appears to me, currently the native village placement algo places them evenly on the map, with no regard of how sustainable the land is. So I deduce, the natives will be everywhere, in every game anyways. Making the whole continent more sustainable, so the europeans can fill the gaps better, does not seem to me to address this bahavior and its consequences.

**Comment by LibSpit** [comment]
I think a food-able hill should support a village, where as flat lands can support towns/cities. So 3 food barely supports the worker, 4-6 food supports 3 people or a small community. 1 grower and 2 'workers' that seems reasonable for a highly developed farm in a 'tougher' landscape.

I also support the concept that night put out about there being a lot of resources that are basically the same thing just cosmetically different. (i.e. make it and sell it in Europe) 

Now if yield desires of colonists was implemented/utilised to give a colonist/colony bonus (like meet a persons needs and they require half the liberty bells [I forgot how this mechanic actually works in terms of code]) then a varied supply chain becomes more beneficial/important/interesting as some citizens demand ale and some like cider. Meet that need and they feel less attached to Europe.

The conclusion I came to with playing was that most of these yields are the same. (same price, same function) and it just made working out what was going on more complicated and headache inducing, without there actually being a need for me to produce any more than one of them.

The other option with that would be heavy price fluctuation to 'encourage' diversification. That just seems tiring rather than rewarding... (I think)

**Comment by Nightinggale** [comment]
`
Now if yield desires of colonists was implemented/utilised to give a colonist/colony bonus (like meet a persons needs and they require half the liberty bells [I forgot how this mechanic actually works in terms of code]) then a varied supply chain becomes more beneficial/important/interesting as some citizens demand ale and some like cider. Meet that need and they feel less attached to Europe.
`
So essentially you are saying that meeting domestic market demands should provide bell bonuses?

**Comment by LibSpit** [comment]
That seems like the most 'logical' benefit in terms of game play, the more you supply the less attached people feel to 'home' and see the new world as their home. It also provides a tangible benefit to the player, so diverse productivity can provide the same benefit as a mass of printing presses and elder statesman. If a person is happy and has their comforts they will follow/vote for the supplier of their comfort, They don't necessarily need a team of experts to convince them. 

Although my main point was more these resources just need to do 'something'. The Colonist demands and a bell bonus for fulfilling it just seemed like an obvious way to make them do a 'something'.

**Comment by abmpicoli** [comment]
I don't think that satisfying the domestic market should yield bells... after all the domestic market can be satisfied by importing things from europe, which would increase, not decrease, the dependency.

**Comment by abmpicoli** [comment]
> In my thinking the idea is that you are taking care of your people, and when they have their needs met they are thinking less about 'I miss beer' or whatever.
> 
> They are more willing to ride and die with you into the unknown.

Not if the beer is europe-tagged... unless they want to make a sail expedition to ramsack the beer factory  :smile:

**Comment by abmpicoli** [comment]
Now , for the idea of having yet another resource... We already have grapes, that produces wine, and barley, that produces beer... I don't think we need this extra one.

I already think that some resources are silly...

Natives selling sugar, coffee and grapes on year 1492 , when these are clearly african and european products, simply doesn't make sense. But, well, at least sugar was already at vanilla, so, whatever...

**Comment by orlanth** [comment]
I like the idea of enabling consistent fulfillment of local demands (or persistent failure to fulfill demands) have some form of effect on gameplay, as a reward for paying attention to local economic needs. However as @abmpicoli said, having this directly affect Liberty/ Rebel Sentiment may not be the best way to do this (piling too many different effects onto a single Rebel Sentiment counter somewhat dilutes it’s uniuqe role, which what a bit of an issue having too many things simultaneously affect Fealty in M:C).

IIRC the M:C mod had added several city-specific variables (Culture and Prosperity) which could be used for something like this, and I think RaR has a separate variable for Health. If there could be a Prosperity variable that changes based on fulfilled/unfulfilled Demands, this could be a cool way to try out letting local Prosperity benefit cities in various ways to reward good management of local demands. For how this might work, I’m thinking back to the city “levels” in Civ4 (where cities could be described as Poor, Developing, Refined, Dominant, or Legendary based on their local culture counter) - perhaps reaching and sustaining a certain level of Prosperity could provide local bonuses to Yield production and Domestic Market profits as a reward. Let me know your thoughts! 💰 🤑 

As for adding more Yield types to the list in RaR , I agree adding more to the already long list would likely not improve the gameplay, unless something can be done to make yields more unique.

**Comment by LibSpit** [comment]
Yeah from what I remember prosperity is one of two inputs to the 'independence' value.

It is kind of off the original topic by now, but I was thinking it would apply more like a percentage shift. 

So it doesn't produce bells, but it either increases bell production by X% or decreases Liberty Cost by X% (like I think certain traits do) So you still need to produce bells, but happy fulfilled needs mean people take less convincing that they can make it on their own.

**Comment by raystuttgart** [comment]
I am not a big fan of adding further Yields (incl. Professions, Specialists and Buildings and maybe new Bonus Ressources) just to have more "Cash Yields".

A) City Screen is already cramped (considering Building slots and space in the Yield rows)
B) AI already now is a bit overwhelmed with all the different production lines it needs to handle.
C) We would need a lot of graphics and currently do not have a good graphical modder in the team
D) Scenario maps that have fixed Bonus Ressource Placements might need to be reworked
E) Balancing of Yield demands from domestic market might need to be reworked

**Summary:**
It is a lot of work and does not really change anything

----------

I once had concepts for several different Food Types to affect Health.
(Corn, Meat, Fish and Fruits)

Basically a colony needed to be provided by several different Food Types so its colonists would stay healthy --> Especially / only affecting larger Cities 

Of course though this could be implemented a "Human only" feature without Players really noticing.
But the rest of the problems described above would basically stay the same.

**Comment by raystuttgart** [comment]
Hi guys,

I really think we will never have "apple -> cider".
If at all a new discussion should be started in the forum.
(Not here in the issues)
