### ISSUE TITLE
Wrong assertation in CvPlayer::buyYieldUnitFrom* (where * is Europe, Africa, PortRoyal)

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#172]
For some unknown reason, there is a precondition check to determine if the player has enough gold to purchase the yield unit.

FAssert(iPrice <= getGold());
if (iPrice > getGold())

This makes no sense at all and we should remove them.

**Comment by Nightinggale** [comment]
There are a number of such checks in the code. Imagine something like getting a list of what you can buy, you click one item and then you can't afford it. The code asserts because the list generation has to be buggy. In this case it looks like CvPlayer::buyYieldUnitFromEurope is written with the assumption that the calling code shouldn't try to buy more than the player can afford, meaning removing the assert checks will then hide bugs in the calling code.

**Comment by Nightinggale** [comment]
It still makes me wonder why it was added in the first place. Is there a risk that the AI tries to buy something, can't because of money issue and then try again repeatably? We had that with AI loading yields into a ship at some point and it froze the game.

**Comment by Nightinggale** [comment]
I just did a quick check in vanilla and while I didn't go through every single assert, those I looked for was there. This means it's not a modding issue, but rather something, which took place before Colonization was even released. For all we know they added the asserts, then added support for lack of money and never removed the assert checks even though they aren't needed anymore.

**Comment by windock** [comment]
Thank you for the fix! It was being annoying
