### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#175]
The text in Assets/XML/Text/ButtonPopup.xml needs translations.

**Comment by Nightinggale** [comment]
We don't have translations for those 3 languages in any of the files in Text. I'm completely open to getting the files translated, but pointing out a single file when the issue is with all of them makes little sense. I'm also open for adding new languages.

Historically TAC and RaR were made by German speaking people meaning it's actually an English translation of a German mod. This is why the German translation is always 99-100% complete and has some German comments in the cpp files. I think RaR had some French translations at some point, but I don't think it was ever completed, or at least it wasn't maintained and is incomplete today.

I would point to #108 as a solution to not adding languages where we don't have a translator. It will also make it easier for translators to locate the untranslated lines as it can be a matter of searching for say <French></French>, as in the string is missing.

**Comment by ShadesOT** [comment]
I was thinking to collect all places where a translation is needed. We can collect that information in one issue or spread it over several issues. If we have several issues, we can handle the information finer grained.

And do I understand right, that all the translations are needed for French, Spanish and Italian, because google translate was used to create them?

**Comment by Nightinggale** [comment]
No, the "translations" are copy paste of the English lines because the game will crash unless there are strings for each, which is the problem #108 tries to solve.

**Comment by ShadesOT** [comment]
Ok, looking at all files in folder text, I see now, that the completeness of translations varies from file to file.

**Comment by ShadesOT** [comment]
I am thinking crowdsourcing is the way to go. I also think that crowdsourcing would need a change in the text file structure to be able to make it automated-ish.

**Comment by Nightinggale** [comment]
We already have a tool for translation [here](https://forums.civfanatics.com/threads/utility-civxmleditor.624161/), though I have no experience in using it at all.
