### ISSUE TITLE
Assert failed: promotion value going negative

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#179]
- With build of 801c47d2153bcb18e7cf79873096888e874232a2
- When ending the turn

Assert Failed

File:  DLLSources\.\CvUnit.cpp
Line:  12148
Expression:  iValue >= 0
Message:  promotion value going negative

**Comment by ShadesOT** [comment]
I added this assert message to the wiki page
https://github.com/We-the-People-civ4col-mod/Mod/wiki/List-of-common-assertions

**Comment by Nightinggale** [comment]
You get this all the time???

It shouldn't be a common assertion. Something is very wrong with your game.

**Comment by Nightinggale** [comment]
It doesn't look like I can reproduce it based on your description. Do you have a savegame or something where it happens?

What happens is disabling of free promotions, which are already disabled, meaning enabling them later will not provide the promotions. In other words somehow you have messed up the free promotion system for units. Did you use world builder or something like that to end up with that assert?

**Comment by ShadesOT** [comment]
I am still using this savegame from 2.7 : https://github.com/We-the-People-civ4col-mod/Mod/issues/47#issuecomment-422524525



> Did you use world builder or something like that to end up with that assert?

No until this savegame I never used Word Builder in that game.

**Comment by Nightinggale** [comment]
Apparently player 1 (a native) has trait 105, which gives the free promotion 86 to UnitCombat 1. It has a UnitTypes 79, which change from profession 5 to profession 11. (I miss the enum naming in #58 right now).

Somehow at some point, the player managed to assign a profession to this unit where one of the following didn't happen:

- didn't have trait
- trait didn't provide free promotion at the time
- some weird way to creating native units can make units with a profession without assigning it first

I suspect I would have run into the last one if it was a major problem, meaning the first two looks like possible culprits. They can occur from xml changes.

Investigating this is tricky as we need to react to the first time this assert occurs. Now it could be really tricky because it might be a leftover from some other profession at some point. The array is saved.

I'm leaning towards "won't fix" because my plan today (which I blew because I went 2.7.x bughunting/fixing instead) was to add free promotions to CivEffects #93. It will not use this array. Instead it will use an array in CvPlayer (the owner of the unit), which is recalculated on load to avoid corruption from xml changes. It's also faster in doTurn.

I propose ignoring this problem (it will take ages to figure out) and then instead remove the ability for traits to give free promotions. Instead traits grant a CivEffect (they already do) and those CivEffects then provide the free promotions. The gameplay effect will remain the same, but we essentially just scrap the code, which caused this bug in the first place without locating the precise location of the bug.

**Comment by ShadesOT** [comment]
I will leave a link on the assertion wiki page.
