### ISSUE TITLE
Tidy up building of road types (aka routes)

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#187]
Currently it is possible to build a plastered country road on a plot and afterwards build a road on the same plot.
Why is this possible? Building several road types on one plot seems to have no effect at all. If any road type on a plot is pillaged, the plot is left without any road type.

Maybe this is a leftover from the times when plastered country roads were railroad tracks. Anyways, we should tidy this up.

**Comment by NoFreeUsernameDammit** [comment]
I'm in favour of removing country road altogether. Since it costs same amount of time as building plastered coutry road, player has no reason to build them, and their removal might make AI build plastered country roads instead.

**Comment by Nightinggale** [comment]
The AI will try to build the best possible route, but Ray declared that the AI couldn't figure out how to build trains, meaning it wouldn't really benefit from the extra costs of railroads and he disabled railroads for the AI, meaning they can't build it. Railroads have since been reskinned. It's easy to control what kind of routes the AI will build. The question is what we will allow it to build.

**Comment by raystuttgart** [comment]
Just did a tidy upof the Roads Code  a few days ago.
