### ISSUE TITLE
Landlocked cities can't produce docks even when water is in the catchment area

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#205]
[Forum thread](https://forums.civfanatics.com/threads/pir%C3%A4us-and-the-2-tile-landlock.638016/#post-15256836)
In short the code for building water improving buildings have never been upgraded to 2 plot radius and is still relying on vanilla one plot.

**Comment by LibSpit** [comment]
that would be cool.

**Comment by Nightinggale** [comment]
M:C has an improvement tag bActAsCity (or something like that). The idea is that the plot acts as a city for the purpose of moving. This allows canals. It's still land plots, meaning land units can cross it just fine. Makes Panama like colonies more feasible.

**Comment by ErikSandbraaten** [comment]
Do we have any suitable gfx\model that could represent a dock\canal tile improvement ? (I don't want to use the fort for this purpose since I looks rather silly)

**Comment by ErikSandbraaten** [comment]
I've gone ahead and implemented a new game mechanic that works like this:
A Fort (or any improvement with isActsAsCity)  now acts as a "Harbor District" (like in civ6) if it's built adjacent to the city AND adjacent to a water plot. This mechanic allows the city to construct water buildings and units. Ships etc. will appear in the fort rather than the city when completed (like in civ6)
The main benefit of this is that we allows more flexible city placement due to landlocked cities being able to both work and access water plots. It makes forts more interesting in general, which is side benefit.
Ideally I'd like to replace the fort with a more specific and suitable improvement but this is what I have for now...

**Comment by ErikSandbraaten** [comment]
Ok, so I chose to implement this as a civ4 modcomp (based on K-Mod 1.46) for now. I hope to release it next week so that the community can experiment a bit with how it affect the gameplay. The AI has been taught to use it as well.

**Comment by ErikSandbraaten** [comment]
My Port District mod has been published:
https://forums.civfanatics.com/threads/port-district.641846/
https://forums.civfanatics.com/resources/sdk-xml-port-district.27309/

**Comment by raystuttgart** [comment]
Actually the behaviour is completely correct to my opinion.
The **City itself** (not just a plot in the City Radius) needs to be connected to a large Lake or an Ocean

I see absolutely no need to change anyhting here.
Many players would not even like that change.

**At least** before we actually implement this:
We should post this as a thread in the forum and add a poll to collect feedback first.

**Comment by raystuttgart** [comment]
That is fixed now since "Lakes".
