### ISSUE TITLE
Pirate spawn rate

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#207]
[Forum thread](https://forums.civfanatics.com/threads/arrrrr.637989/).
Apparently barbarian pirate spawn rate has been disputed with posts indicating both too many and too few. It's possibly related to map size.

If we can't balance it, then maybe we should add a map/game option to make the player pick spawn rate.

**Comment by alexandr-** [comment]
And how about a warning in advance that more pirates will come soon - i sometimes run into issues where i quickly loose all my ships because of sudden pirate raids

**Comment by ErikSandbraaten** [comment]
Pirate spawning is a DLL-event that is processed per player. Arguably, pirates should be handled like animals (handled in CvGame per turn) and not be done on a per player basis. I agree that it would be nice to have a warning before the pirates actually spawn, like a dialog that states that there's a rumor about pirates that are about to set sail from Port Royal ☠️ 
The issue with python events is that we would have to add a fair amount of new functionality to enable them to deal with pirate spawning and most likely we would have to code up custom python code anyway and I think that the current preference for (almost all) of the current programmers is to extend the DLL.

**Comment by LibSpit** [comment]
In FTTW we have imrpovements that can spawn units, these can be player of barbarian or animal in nature, and is controlled in the improvement xml and can be modified by civics to increase or even activate spawns. you couuld make pirate spawn points as part of the map code, then instead of a warning you could find these spawn points and set patrols to watch out for arriving pirates.

**Comment by raystuttgart** [comment]
I think this has been balanced now much better.
There have been no more complaints.
