### ISSUE TITLE
Static Americas Map is extremely disadvantageous for Denmark.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#22]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-118#post-14975000 .

**Comment by raystuttgart** [comment]
Each map is simply different.
And Players in MP might also play random version of the Map.

Also now with the new Terrains and Bonus Resources the North is better to start then before.
The Map has just recently been reworked and so far no complaints.

I would thus close this, because kind of outdated.
