### ISSUE TITLE
Some yields have incorrect 3D models

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#223]
[Forum thread](https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-3#post-15283234)

Apparently adding yield units with world builder will add yield units to the map. Some yields look ok while other yields don't. We have two possible scenarios:

1: the 3D models aren't actually used. In this case they waste memory and slow down game startup for no reason. If that's the case, then get rid of as many 3D models as possible. See #211.

2: the 3D models are used somewhere. We need to figure out where and then fix the broken yields.

*****

Personal speculation is that yields are units in order to simplify the transports. Each slot can carry a unit. In this case we should be able to implement #144 as a YieldArray (or a modified version as proposed in the replies) and that way get rid of all yield units entirely.

If we can get rid of yield units and autogenerate emphasize, then yields will be defined in one xml file instead of 3, which helps xml modding significantly. No risk of going out of sync, which will then cause bugs.

**Comment by orlanth** [comment]
I'm not sure if yields as units may be necessary for their drag-and-drop into transports or other vanilla behaviors - I know the 3D nif models are shown in the pedia; aside from that I don't think vanilla uses them much, but it could be a cool modding option to enable Yields to be dropped on the map for units to pick up in certain circumstances. (E.g. could make some goody huts or exploration Events create a stack of rare yields to collect and bring back rather than a generic cash treasure; defeating certain animals or armed units could drop Fur or weapon yields, etc.) However I'm not sure there is an action that would allow picking up yields from a map tile - if this is too fiddly and there's a benefit to removing map Yield units, those cases could be managed by simple unitinfos/eventinfos tags that can provide a Yield to an adjacent unit with free slots or a nearby city.

**Comment by Schmiddie1979** [comment]
Yields are not shown ingame - you can put them on the map with the wordbuilder but they don't have any function. However, they are shown in the pedia and therefore it would be difficult to delete them completely from the game. It would be a nice feature (e.g. due to an event) to find them on the map with the possibility to pick them up.

**Comment by Nightinggale** [comment]
The entire pedia is in python, except for some string generation, which is in the DLL. This means we can cut out the code, which draws the 3D yields if we want. All it takes is to find the specific line(s) responsible for this.

**Comment by raystuttgart** [comment]
There is also a thread for it in the forum:
https://forums.civfanatics.com/threads/work-coorination-3d-graphics-for-trade-goods-open.680421/

Thus I close it, as it is an oudated duplicate.
