### ISSUE TITLE
maintenance troops

### ISSUE THREAD

**Issue by Villovik** [We-the-People-civ4col-mod/Mod#227]
I want to propose add maintenance troops.
If colonists is in colony they consumes 2foods per turn.
If you have 10 soldiers outside they not hungry?
Idea is to creating gold consumption of soldiers dependence total population inside colonyes 
For example: I have 1 colony with 2 pops so my soldiers requiring maintenance 1gold/turn if I have 1-2 soldiers, or 2/turn if 3-4 soldiers, 3/turn if 5-6 soldiers..
But I don't know what be if gold will be less than 0

**Comment by Nightinggale** [comment]
We talked about military upkeep for Medieval Conquest at some point. The problem is that it has a huge exploit. Just leave a lot of colonists outside the colonies and keep weapons, horses etc in the colonies. In case of war, arm all of them during the same turn and you have a full army without having the peacetime upkeep.

Another problem is how should this be handled. Should we make use of #146? Would the gameplay benefit from this? How will the AI react?

**Comment by Villovik** [comment]
If you keep wepons and horses inside, in this case you losing capacity colony!
What if any units requiring gold, not only army?

**Comment by MichaelQuell** [comment]
i would rather have that every unit consumes 2 food per turn. If the plot or any other transport cant provide enuogh the unit will get dameged

**Comment by LibSpit** [comment]
I am not such a fan of the delivering food micromanagement aspect, I prefer the ideas that we were developing for M:C, with global empire maintenance, with military adding to this. It allowed for the global consumption of resources per turn, from gold to crosses and everything in between. WIth Civics that could also impact on this cost.

As for the exploit Night mentions, M:C had another good method for that. Units that became soldiers could only be a set of basic units, militia types. They then had to be garrisoned for X turns, or I think combat XP worked too. 

Anyway after X turns they recevied a 'Trained' promotion, this allowed them to then be upgraded to better units with elite equipment. You an even have length of service promotions and tiered unit types, then the longer they are a professional soldier, the better the soldier they can be. So a levy army is a perfectly reasonable and possible strategy, but it will suffer greatly at the hands of a well invested professional army. 

As for the 'what happens if you don't pay' situation, I quite like the idea of anarchy, where your civics get locked at the initial settings until you return to positive, the other possibility could be the longer you remain in debt the more damaging the situation becomes, with units vanishing or taking damage, etc.

SO if you do go into debt (we could have a turn or two grace period, or a level of 'acceptable debt') you then need to correct the course asap to avoid serious issues.

M:C and to a lesser extent Other mods also rewarded keeping money in the bank as savings for random events and other mechanics (like banking interst in M:C) this could be further encouraged by putting a max limit of some sort on the amounts of money the king demands, so you do not feel such an imperative to spend it before the king takes it.

**Comment by abmpicoli** [comment]
I see all these options as something that needs careful balance: if soldiers take food, food intake in the colonies must be increased in some way... If soldiers take gold, we must have extra gold profits somewhere... 

I believe this is the kind of developer that will need a lone coder implementing the hypothesis he/she considers best and then see how the game "feels"...

**Comment by alexandr-** [comment]
Should the size revolutionary army be reduced if soldiers would cost upkeep? Otherwise prepping for the revolutionary war, will take a much longer time

> If soldiers take gold, we must have extra gold profits somewhere...

Soldiers already generate money with their need for expensive goods via markets, so this could be balanced with already implemented mechanics.

>  Just leave a lot of colonists outside the colonies and keep weapons, horses etc in the colonies.
But storage capacity should be usually a limiting factor?

**Comment by dcrookston** [comment]
Dawn of a New Era handles this with two changes: units outside of colonies incur a cost each turn in gold, which is offset by making all goods more valuable when sold in Europe.  These two changes are just part of the economic differences in DoaNE though.  I don't know if these two changes on their own would work here.

**Comment by raystuttgart** [comment]
"Upkeep" is already on the list of the features in our forum.
It is the much better place for feature discussions.
