### ISSUE TITLE
New Random Events

### ISSUE THREAD

**Issue by alexandr-** [We-the-People-civ4col-mod/Mod#232]
In https://forums.civfanatics.com/threads/new-colonization-daone-v4-00.523832/#post-13416953 i found some nice exploration ideas by Zholef:

* "Your scout has offended the chief of a Tupi village. In their anger, the natives robbed him of his possessions and kicked him out." (Without his horse, your scout has been reduced to colonist and is forced to return his map on foot. You gain -1 relations with the relations with the tribe.)
* "Your Excellency, rumor has it that our scout has fallen in love with a native woman living in a Sioux camp and decided to stay with her." (Your scout and his map are lost. You gain +1 relations with the relations with the tribe.)
* "Your Excellency, a messenger from an Aztec city has arrived to thank us. He claims the gods were most pleased with the sacrifice we offered." (Your scout and his map are lost. You gain +1 relations with the relations with the tribe.)
* "Your Excellency, our scout has fallen in love and eloped with an Inca noblewoman. Their King is furious." (The scout is lost, but a converted native appears with his map in your closest colony. You gain -2 relations with the tribe.)
* "Some natives ambushed and robbed our scout in the forest." (Without his horse, your scout has been reduced to colonist and is forced to return his map on foot.)

I dont know if they have been implemented yet, but it brought me to other ideas:

European Craze - pick an rarely traded item and high inflate prices (eg. furniture, american beef?) for a random amount of time / amount of goods before it returns to normal prizes
         also inversible: american cloth is out of fashion so prizes will plummet

Need for help - Native Settlement or one of your cities needs a certain good transported to.

Get Rid of Pirates/Animal-Cave - Civ5-like quests where you have some rounds to remove some nearby source of barbarians (in col wild animals/pirates) - see https://github.com/We-the-People-civ4col-mod/Mod/issues/207#issuecomment-451390357

**Comment by orlanth** [comment]
If wanting to add more Events / quest Events, it could be good to focus on coding a few new standard functions for the new event features you want and exposing to EventInfos xml; this way events of that nature can be easily modded without requiring any custom python code for each.

Here are a few potential ideas for Event modding features:
- Add/subtract iYield units of a YieldType to nearest city
- Add/subtract iYield units of a YieldType to the cargo hold of the unit selected by the eventtrigger
- Adjust price of a YieldType in one Trade Screen by iPercent (once tradescreens are standardized)
- Spawn a list of UnitTypes on the event plot (with a tag specifying if these are owned by player, King, or another specific Civilization)
- Apply a CivEffect to the player for iTurns turns

I’m not sure all the event ideas about “losing maps” would actually be that great or interesting for gameplay - if the idea is that a chunk of the map you had already discovered would get “blacked out”, players could naturally still remember having explored that area (and even see it in autosaves) so it wouldn’t seem to add much new fun or special strategic challenge to re-explore it. However they’re not necessarily bad ideas if implemented.

**Comment by abmpicoli** [comment]
Yep, I second the idea that "losing maps" is not very cool... the only way I see this implemented is by covering a circle around the event in "unexplored" , and this wouldn't make sense if the colony being explored is just 4 tiles off a settlement, for example... Also, the idea of "returning maps" would be very complicated to implement.

**Comment by ErikSandbraaten** [comment]
The game tracks tracks isRevealed on a per plot per player basis and there's no support for a unit having it's own partial\revealed map. It would take a lot of effort to implement it and it would not have any chance of being peformant (this comes from a dude that just spent the last few days optimizing plot processing)

**Comment by abmpicoli** [comment]
Another thing to review is the random event system: what happens if we "bloat" it with new random events? Is there a fixed amount per turn, or is there a test for every single random event out there at every turn? If the second is the case, the more random events we add, the more luck-based the game becomes, and turn processing becomes more complex every turn...

**Comment by Nightinggale** [comment]
The game tracks revealed plots in each plot on a per **team** basis, not player. Often there is one player on each team and the difference won't matter, but custom games can have more than one player on each team and it is in fact supported and is working well.

I'm not sure I like the random events proposed in the first post. Losing a scout early on can hit you really hard and it will likely result in rage quit rather than making the game more interesting. It just seems so unfair to lose a unit at random like that and then some other player gets all the ruins before your next scout arrives from Europe.

> Another thing to review is the random event system: what happens if we "bloat" it with new random events?
I feel like the random events is kind of bloated already since there are so many of them. Many isn't bad in itself, but it could be very bad if the engine doesn't scale well.

**Comment by alexandr-** [comment]
You can already lose Units early on, i dont see these different Scouting-Events as rare and then interesting (story-backed) events

**Comment by abmpicoli** [comment]
> 
> 
> You can already lose Units early on, i dont see these different Scouting-Events as rare and then interesting (story-backed) events

But by adding extra events, *once again, depending on how random events are calculated every turn* , you increase the likelihood that a random event like this will happen, making the game more unbalanced with each added random event...

**Comment by Nightinggale** [comment]
You can already lose the game early due to randomness, which isn't ideal. Imagine exploring a ruin and then some big native tribe attack you and kill every single unit. It doesn't matter if you are a good player or not, you can easily get into a situation where you have to pick between restarting or reloading.

Rather than adding more complete unfairness, we should look into some balancing of the randomness. In fact we might consider removing the "natives declare war" exploration outcome because by the time you are strong enough to survive that, all the ruins are already gone. It's essentially a "kill a player" random event.

**Comment by orlanth** [comment]
That's true - here are some thoughts on good tag options in Eventtriggerinfos that can be used for balancing some noxious events be more likely to occur for players who have a lot of resources or are getting too far ahead of others, rather than blind random chance. (E.g as seen in the wiki below, eventtriggers can incorporate things like player total score, military score, total population, total gold, empire size in tiles, and number of owned building/unit/improvement types).

http://modiki.civfanatics.com/index.php?title=Civ4EventTriggerInfos

You can also make events that trigger only once globally for the first to trigger them (e.g. first player to reach a certain map area may get a native raid/war event; first player to amass X populations/buildings/gold may spawn a special pirate fleet), and then that event can stop being included in future trigger chances. In our old WH mod of Civ4, these kinds of events were great for adding some much needed auto-balancing to the game, by introducing some special challenges when players were getting too far ahead and could handle the challenge.

To keep things unexpected, you can also use iPercentGamesActive so certain events will not necessarily always predictably show up in every playthrough. 

A lot of the BtS-specific tag options from Civ4 (city anger/unhealthiness, Corporations, Religions etc) were deprecated in Civ4Col - maybe some tags with triggers based on new things like FFs, Domestic Markets demand, TradeScreen prices, Rebel Sentiment, etc could be great for expanding Civ4Col modding potential.

**Comment by ErikSandbraaten** [comment]
See me comments on #241 where I explain some of the problems with the events with regards to the AI.

**Comment by raystuttgart** [comment]
Implementing Event Ideas of others is not a todo of the WTP team.
Everybody in community can learn and use the existing System to create his own Events and share them - if motivated. 
(It is not that difficult and we would give help if problems arise.)

This is simply personal taste that no other modder will ever implement.
Because everybody has enough ideas of his own for Events and other stuff.

Thus I now simply close it.
Otherwise it would stay open forever anyways.
