### ISSUE TITLE
Scout recommendations on shipwrecks

### ISSUE THREAD

**Issue by alexandr-** [We-the-People-civ4col-mod/Mod#234]
The yellow circle marks settlement-spots and  (most of the time?) huts and temples, but also shipwrecks which cant be reached - see attached screenshot.
![img_5458](https://user-images.githubusercontent.com/6338481/50725699-c3da1680-1101-11e9-8427-a12497f626de.JPG)

**Comment by Nightinggale** [comment]
Known issue, but yes it should have a ticket. The issue is that shipwrecks are ruins and it checks for ruins without checking domain. It's partly related to the issue that it's not highlighted for ships.

While it might seem cosmetic at first, it is actually a view into how the AI is thinking and the lack of a highlight means the AI lacks interest. I''m not sure the AI really considers moving scouts to shipwrecks because the scout can't move into the plot in question.

**Comment by ErikSandbraaten** [comment]
The relevant code is in CvGame::updateColoredPlots(). I'll have a look into fixing this and then see what else we can take from K-Mod version since it has several improvements that should be useful.

**Comment by ErikSandbraaten** [comment]
Note that I chose to use the green color to distinguish goodies from proposed settlement locations (still yellow). We may want to rework that a bit as well.
