### ISSUE TITLE
Change Request : Prospector new abitlity

### ISSUE THREAD

**Issue by jkevcol** [We-the-People-civ4col-mod/Mod#239]
Propector must search for gold, silver, precious stone, etc...

Propector need food to search on the map. 

Chance to find deposit, an amount of the minerals or to be kill. 

No deposit available at start.

Impact on user experience: No location advantage at start on others players.

Alternative request : 
- Rare minerals not shown on the map. Discovered by entering the tile.
- Gold prospector profession available with food and can find gold deposit by entering a tile. 
Reference to Gold rush !!!
- Scout can find others rares minerals deposit by entering a tile.

Thanks to all !!!

**Comment by abmpicoli** [comment]
Let me see if I understood it well:
1) gold, silver, pearls and gem deposits would be not visible at the start, depending on the proper professions to discover them, right?

I'm not sure I like the idea... unless the indians can also "see" them, so we have situations like incan gold... 

But I understand the issue of game balance: to have gold at the coast, at game start, is a *huge* advantage...

**Comment by Nightinggale** [comment]
I don't like this idea. It means you have to send people around to figure out where to build the colonies. Early on you do not have the people meaning people will just build colonies while completely ignoring such bonuses. This is a huge problem because by the time you have time to survey, the matured colonies are likely to have left plots unreachable by any colony and still too close to colonies to found a colony to cover those plots.

If anything, the map generation should just not generate such bonuses and then each turn there is a chance of discovery on plots being worked. This chance will diminish with the number of found bonuses meaning each map size will have a certain amount of bonuses and not just finding more and more until the map is full.

We could code this with a list in world size where it knows how many bonuses there can be added of each type. That would result in a DLL code, which will not need updating if the bonuses updates.

Maybe add a chance modifier to professions like ore mining has a higher chance of finding gold than say hunting.

I kind of like this approach for another reason as well. It's not uncommon for the gold to be in the middle of a mountain area, making it completely unreachable by colonies. Not just about making a bad colony with the sole purpose of gold mining, but downright impossible to found a colony within range.

**Comment by abmpicoli** [comment]
I don't like the idea of having mineral resources being "discovered" by mining as the exclusive means for finding gold, silver, etc. Once again, it makes situations like having indians with gold/silver to sell not feasible. 

And the issue of maps with too many mountains, making impossible to build a colony is, for me, a problem with map scripting.

Right now I'm experimenting with floyd-steinberg dithering on the FaireWeatherTweakedEx map to ajust terrains and mountains , which diminish the chance of having a mountain range such as this, that would make the map to be unusable.

Another thing that can be made is to make sure that all bonuses are at most 2 tiles away from a grassland / prairie / savannah or marsh plain when building the map.

**Comment by Nightinggale** [comment]
> Another thing that can be made is to make sure that all bonuses are at most 2 tiles away from a grassland / prairie / savannah or marsh plain when building the map.
You should take city catchment radius into account. Right now it's hardcoded in the DLL at compile time, but we should turn that into a map parameter, making the player select it when starting the game. #60

**Comment by jkevcol** [comment]
The critical point of request is to avoid being favored over other players.

Rare minerals that can be sold in raw form should not be so easily discovered.

@abmpicoli Why Inca Indian cannot sell gold/silver? They are on their native land and knows where to find rare minerals unlike colonist. However, they can sell their minerals at a better price to players who have a very good relationship with them.

@Nightinggale I like the way my request become on this grooming. You have a good idea. Maybe this feature can be a new game option so player can play classic game as well.

Founding colony by knowing the minerals location or by finding them in the colony? 

I think is the question to answer before go further. 

Thanks !

**Comment by ErikSandbraaten** [comment]
Here's a counter proposal: How about we ensure that silver,gems,gold etc. are placed in inhospitable regions ? Players can then make interesting choices and trade-offs concerning where to place their colonies. I completely agree that starting too close to gold and vast amounts of fertile land is unbalancing.

**Comment by ErikSandbraaten** [comment]
Regarding the prospector idea: It's an interesting mechanic and it could be applied to non-mining as well. (The DoaNE mod has something similar with the agronomist mechanic where yields must be planted, albeit we could have them be discovered instead)
The real issue is, as always, the AI. We'd have put in quite a bit of effort to enable the AI to compete with the human player(s).

**Comment by Nightinggale** [comment]
From what I can tell, the graphics engine calls CvPlot::getBonusType() to set what to draw. We could change this to tell the bonuses the player can see and add another variable to tell what is on the plot, possibly hidden. This will allow placing bonuses on the map, but require a special action like prospecting to reveal each bonus.

A plan for #93 is to allow CivEffects to show/hide bonuses. This could be used to for instance hide all bonuses of a certain type until the player reach a certain era. A plan to allow one to reveal and another to actually gain the bonus is also under consideration.

Whatever we do, we shouldn't hardcode anything in the DLL. It should be generic and allow xml to setup something for every single bonus type as well as setting the profession to work on this in xml. We might want to make prospecting a CvBuildInfo, which contains which terrains/bonuses it can prospect. This would allow setting up a profession for minerals and one for plantlife or whatever. We should however be careful not to bloat this feature and make way too many professions for this.

If we are to prospect, we will need to consider what to do if a player prospects after building the colonies (which would likely be common) and minerals turns up in an unreachable location. #142 seems like a valid solution to that problem. It could also be a solution to otherwise unreachable bonuses. Just remember that a unit approach should always be a worse solution than just working the plot from a colony, but not so much worse that it makes people rage quit if all the bonuses are in between colonies.

**Comment by jkevcol** [comment]
In regard to all comment. 
Whatever will be do in this matter, i'm in the same thinking of ErikSandbraaten. 
AI should compete efficiently. 
Keep it simple for a good balance.

Thanks to all.

**Comment by edbouverie** [comment]
I like the idea - perhaps do not hide all precious resources at the beginning of the game but lower them and add a prospecting ability. You could also think about a new improvement which is a panning station for river tiles which could give a very small silver/gold/gem yield. I do no know if fractions of resources exist?

**Comment by jkevcol** [comment]
Not hiding all precious ressources its a good Idea but deposits should be depleted faster. Deposits find by prospecting are depleted more later. 

Panning station could be a good Idea if precious ressources is in a city tile. A River must be in the city. This improvement could give a +1 bonus per turn for all kind of rare Minerals extracted.

**Comment by raystuttgart** [comment]
It seems that we all disagree to this.
I will thus just close it.
