### ISSUE TITLE
Change request : Fidelity Rewards

### ISSUE THREAD

**Issue by jkevcol** [We-the-People-civ4col-mod/Mod#245]
King ask for payment during the game forced you to do a good project more later. 

The king could be grateful after a certain payed amount if i have a good relationship with him.

Exemple after:

2000 = An expert unit (Choice among three expert)

4000 = An militay unit

Etc...

Context:
The king ask 400$
I pay the King.
Total amount = 400

The king ask 120
I refuse
Total amount = 280

The King ask 1720
I pay the King.
Total amount = 2000

King reward me with cargo of 100 wood and the malus for not paid the king is halved or forgeted.

But if i would not have refused :
King reward me with an expert unit.

Thanks and give a grooming to that !

**Comment by raystuttgart** [comment]
I am not really a fan of this.

King's request should be a kind of bad thing that gives you an incentive to say "No!" and thus anger him. (Which will have negative consequences for the future and will on the long term be your incentive for the revolution.)
If the Player is rewarded for always saying "Yes, my Lord" and kissing the ring, this (current) concept does not make any sense anymore because you will always say yes because in the end it will be just as costly as buying an expert in Europe but you will also have made the King happy with even avoiding all the consequences (e.g. on Tax Increases, REF, ...)

So from my side a definitive "don't like" to the current suggestion.
The current concept is basically just an exploit or a "mild cheat".

**Comment by raystuttgart** [comment]
Nobody is ever going to work on this.
Since I am trying to clean issues a bit, I will close it.
