### ISSUE TITLE
New Idea : Founding Father as colonist

### ISSUE THREAD

**Issue by jkevcol** [We-the-People-civ4col-mod/Mod#246]
Founding father could be real colonist in the game.

Example:

I gain Benjamin Franklin. 

Benjamin Franklin appear at the European dock.

If i use Benjamin Franklin as an elder statement in my colony, I gain the bonus of Benjamin Franklin.

I find is a good representation of the name of your mod : We The People

Founding Father who give productivity bonus can be assign to productivity building.

Founding Father could be captured.

Etc...

I know its a huge Feature but i think it’s worth thinking about.

Thanks

**Comment by Nightinggale** [comment]
My biggest concern in this regard is the amount of memory this would require. Each FF would take up one entry in units, possibly one unit class for each. This makes looping unit types slower. On top of that each FF will require 3D graphics. This means more graphics loaded at startup time, which will slow down the loading time prior to reaching the main menu. This time should ideally go down, not up.

Worst of all, all this extra data (both data and graphics) will take up extra memory and being a 32 bit application, we really only have 2 GB in total regardless of how much system memory modern computers have. It's not a problem yet, but we could run into problems if we start to bloat the game like this. The risk of this is real because Caveman2Cosmos had to redesign and not be as feature rich as planned because of the memory limit.

Another issue is the amount of needed manpower to make this huge amount of graphics. We would need somebody (one or more people) to show up and be expert graphic artists in order to make this amount of units, particularly if they aren't to be visibly much worse than all other units in the game.

I have to say I don't like this idea based on purely technical reasons. As for the gameplay side of this idea, I think it's good to have proposals to provoke the concept of "copying vanilla" as this forces people to think about what we really want with the game.

**Comment by jkevcol** [comment]
In my opinion, i) is not compulsory to have a graphical representation of every founding father.

Only one could be sufficient. It could be the better graphical unit of the game. 

Thus, a single unity with a different color suit according to the category of founding father. Military, Trading, Religious, Politics, Explorer and Indian.

Outside the city : The name of the founding father and its capacity can be registered in property panel. 
In the city: A pop up image of the founding father on mouse over.
--------------------------------------------

For the question of available memory, I don't see the interest of the African port.

The European and smuggled port seems to me sufficient for a good game experience.

Can i ask you the purpose of this improvement?

**Comment by abmpicoli** [comment]
> For the question of available memory, I don't see the interest of the African port.
> 
> The European and smuggled port seems to me sufficient for a good game experience.
> 
> Can i ask you the purpose of this improvement?

Well, the problem of removing a feature is that there may be always someone wanting it. The idea of the african port is to be able to recruit african slaves, and as an alternative that doesn't demand pirate ships to sell stuff, alternative to europe. 

I, personally, don't pay too much attention to it. But I don't know what the actual player base thinks about it.

**Comment by jkevcol** [comment]
The principle of boycott in the vanilla game is precisely to be disadvantaged commercially. How work the boycott in africa port?

If no boycott in africa port, i suggest we make it a game option.

**Comment by Nightinggale** [comment]
There are no plans to remove the African port. Jkevcol is the only one talking about it. The only planned change is #147, which is about redesigning the code to make it less prone to bugs while maintaining the same experience for the player.

Boycotts in Europe affects Africa as well, but not Port Royal. You do need a smuggler to sell something, which is under boycott. If this isn't the case, then it's a bug because the code is clearly written with this design goal in mind.

-----

I'm still not sure about FFs as units. FFs are single individuals doing political work while a unit in the game represent multiple people. Making some FF a unit means one person would do the same work as say 200 people. Another issue is that it would severely affect late game where you try to train experts for everything. You would end up with a bunch of units, which you do not want to work because they are worse than the other units you can use for the limited number of slots.

As Schmiddie said, can FF die? What if they are on a ship and it is killed by animals? Killed by natives?

What about teams with multiple players? FFs are in CvTeam, not CvPlayer meaning two players in one team will gain the same FFs. If there is just one FF unit for each FF, which player should get the FF unit?

I have to say I'm not a big fan of any feature, which has so many unanswered questions, particularly because a number of the questions lack a proper answer. The problem isn't to come up with answers as we can always "just make something up". The issue is finding answers, which makes sense from a gameplay and game balance and I fear this is rather difficult if not impossible to get right.

**Comment by Schmiddie1979** [comment]
I totally agree!

**Comment by jkevcol** [comment]
Agree too! Thanks guys !
