### ISSUE TITLE
Automated fishing boats sails to Europe

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#249]
[Forum thread](https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-6#post-15338484)

**Comment by ErikSandbraaten** [comment]
While testing, I created 5 whaling boats and set them all to fully automate. After several turns in autoplay, I encountered this assert:  CvSelectionGroupAI.cpp:199  which is triggered when (iTempHack > 100). Something is fishy in CvUnitAI::AI_workerSeaMove() !

**Comment by ErikSandbraaten** [comment]
Note that gatherboats are allowed to escape to Europe if they "detect danger" which will happen if they spot a privateer and they have enough movement points to sail to Europe.

**Comment by ErikSandbraaten** [comment]
Ok, the problem is that bool CvUnitAI::AI_gatherResource() only calls : 
getGroup()->pushMission(MISSION_WHALING);  (or MISSION_FISHING)
without expending all the movements points (by calling finishMoves() etc)

**Comment by raystuttgart** [comment]
Do you already know how to fix it or at least have an idea?

Would it be good enough just to not allow them to sail to Europe or is there more to be done?
(Although I am not sure if Whaling Boats are supposed to be allowed to sail to Europe.)

By the way - most likely I wrote that code because I added Whaling in TAC and Fishing Boats in RaR.
(I am not really good at writing AI code though. koma13 in TAC was much better than me.)

**Comment by ErikSandbraaten** [comment]
I guess I have to apologize because it appears that I ranted about stuff that you actually implemented.
Will double check, but I'm fairly certain that gather boats can end up in Europe in order to escape from pirates. They should stay there until they heal and then sail back so in my opinion this is a feature that works as intended. 
The assert is a separate issue that is causes by automating more than 1 gathering boat. The solution is to split up the group and to automate them individually. I'll put this on my list.

**Comment by raystuttgart** [comment]
No need to apologize. 
I know that my code is not perfect - because I just wrote so much of it in little time.
And I know that I am specifically not good at writing AI code.

**Comment by raystuttgart** [comment]
@devolution79 
Is there still something to do?
I could swear that we have no issue here anymore.

**Comment by raystuttgart** [comment]
**@devolution79** 
Could you give some comment on this?
Is this issue still to be fixed?

**Comment by raystuttgart** [comment]
I think this problem has been clarified / fixed.
It just happens if they are damaged.
