### ISSUE TITLE
From Marla_Singer AI Improvement: make AI evaluate better island placements.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#25]
>This is an old issue which has always existed, it's not new to v2.7 (I haven't downloaded that one yet). I believe that comes from the fact the AI in Civ4Col is aimed to build land Empires, expanding accross a single big landmass, and not to build colonies on different smaller islands. In the same way, the Caribbeans are generally ignored by the AI despite having good ressources. As a Human player I generally enjoy settling in the Caribbeans for that reason, automatizing ships for goods transport between colonies in the same way as for chariots on land. But I don't think the AI knows how to do this.
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-118#post-14975000

**Comment by ErikSandbraaten** [comment]
There are several issues that prevents the AI from properly managing migration between islands (areas in game terms) and coordinating transports between them.

I originally added the coastal transports in 2.7 with the objective to improve the AI in this regards, but due to time constraints I left out several features like having the AI use coastal transports to ferry yields and colonists between coastrally linked islands.

**Comment by raystuttgart** [comment]
Outdated, as @devolution already improved AI logic for settling on islands.
Thus closed.
