### ISSUE TITLE
Randomly visible tiles in ocean (after exploring)

### ISSUE THREAD

**Issue by Alignn** [We-the-People-civ4col-mod/Mod#254]
I don't think I got this issue before I compiled 2.7.2 on my own. Can't see any obvious pattern to it. Doesn't affect gameplay much, just looks funny.
![oceanview](https://user-images.githubusercontent.com/18351802/52790183-3675d480-3066-11e9-901b-6a0b0c72b69c.jpg)

**Comment by Nightinggale** [comment]
I had this in Medieval Conquest at some point, though the shape is different. The culprit is likely the fact that the game stores how many units can watch a plot. It increase by one when a unit moves closer and decrease by one when a unit moves away. Obviously this cached counter is incorrect and one culprit could be that the cache is saved in the savegame. If xml changed to reduce the visual range of a unit, then the counter will not decrease even if the unit moves away, hence adding a permanent +1, which makes the plot always visible. It's also possible that the cache is corrupted even without saving and loading, but the issue is a corrupted cache.

**Comment by Alignn** [comment]
While I have made XML changes, I don't think I touched vision range at any point. Can I clear the cache somehow to fix the issue?

**Comment by ErikSandbraaten** [comment]
I did encounter a strange issue that resembles this when I parallelized the visibility computation. It may very well be an "old" bug that is showing up.

**Comment by Nightinggale** [comment]
I looked at the code and I found something rather confusing. CvPlot::updateSight() updates what the plot owner can see as well as the view from units on the plot. However CvUnit::setXY() seems to handle what units can see as well when moving into plots. It seems to me like units can be added more than once, but only removed once when being removed from a plot (like moving). Even if it is written correctly, it's very confusing, hence prone to bugs when we mod the code.

I propose a rewrite of how the view plots code works, which should make it more clear.

*****

## CvUnit

- Add a function to turn viewing on and off
- SetXY turns viewing off, move the unit and then turns it on
- Dying turns viewing off
- Europe travel can turn on/off
- Creation turns on
- New promotion changes visual range
- Whatever else fits this pattern

*****

## CvPlot

This one is more simple. It has on/off like CvUnit, but it's for the plot owner and it triggers on plot ownership change.

Whenever something change on the plot, which change visual range (removing feature blocking view etc), the plot will loop all plots within a theoretical max visual range, turn vision off for plots and units, change the plot to the new setting and then enable vision for all the plots where it just disabled vision.

*****

This makes it well defined what each file is supposed to do. It also adds the ability to reset the cache and loop all plots to set it again, hence allowing visual range to be modified in xml and then load a savegame without breaking the game.

The basic principle should still be the same. Each plot has an array to give each team a counter of how many units/plots can view the plot actively (no fog of war). The drawing engine draws the plots where the counter is > 0.

**Comment by ErikSandbraaten** [comment]
@Alignn Have you retested with a revision prior to where I added the visibility cache ?

**Comment by ErikSandbraaten** [comment]
I also want to point out that the storms feature and the associated visibility computations do slow the game down quite a bit on huge maps it's something like 10-20% of the CPU usage in the early game. (Later on the AI pathfinding  eventually dwarfs the other subsystems in terms of CPU usage though)

**Comment by ErikSandbraaten** [comment]
We definitely need some form of caching and\or a better algorithm since right now there's a lot of redundancy. Alternatively, I should to get my act together and fix the bug in the multi threaded implementation that I've got. Maybe I should just commit it as a branch of the existing task parallelism branch ?

**Comment by Alignn** [comment]
> @Alignn Have you retested with a revision prior to where I added the visibility cache ?

Not yet - I had a game I wanted to finish before risking messing things up, but now is fine.

**Comment by Alignn** [comment]
Well, after rolling back to the suggested version it went away, but more annoyingly it also stayed away after I checked out the newest version and recompiled. That or the bug requires something other than just exploring all over the map. I'll post here if it comes up again, ofc.

**Comment by ErikSandbraaten** [comment]
Still happening in 2.8 and it is very easy to reproduce. Working on a fix atm

**Comment by raystuttgart** [comment]
Thanks for looking into this.

I know that it is easy to reproduce but I still do not know / understand what causes it.
Of course, once you know what causes it, it is usually also easy to fix it.

**Comment by ErikSandbraaten** [comment]
I am not able to reproduce it anymore (and I haven't changed any of the code!) :(   Could anyone that is being affected by this issues please consider providing saves, preferably from the turn before the plot became permanently visible ?

**Comment by ErikSandbraaten** [comment]
Alternatively, provide fool-proof instructions on how to reproduce the issue.

**Comment by raystuttgart** [comment]
This usually **only** happens in **late game** once a lot of ocean has been uncovered.
I normally never saw it before turn "100" - usually even later.

So to reproduce you could try to have the game "autoplay" e.g. 300 turns.

**Comment by ErikSandbraaten** [comment]
Interesting, a couple of days ago I had it happen within 10 turns. I think it's related to having at least 1 vision upgrade.

**Comment by XSamatan** [comment]
I have two saves, a autosave where the problem should appear in the next few rounds, and a manually taken save as soon as I found a plot with this visibility problem.


[AutoSave_AD-1554-September.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/4987628/AutoSave_AD-1554-September.zip)

[visibility.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/4987630/visibility.zip)

Please note that this game is highly edited to my liking, however the changes are only xml, dll is 2.8

Regards
XSamatan

**Comment by ErikSandbraaten** [comment]
Thanks for the autosave, fortunately the visibility bug had already been triggered by the northern scout (plot: 53, 182) . Simply moving him SW was enough to make the plots (66,186) and (67,186) visible (visibility count was stuck1 even though no unit from our team could possibly observe them)

it looks like I have a candidate fix, but more testing is required!

**Comment by raystuttgart** [comment]
Could you explain what the technical cause of the bug is?
Maybe this will also explain already the fix.

**Comment by ErikSandbraaten** [comment]
https://github.com/We-the-People-civ4col-mod/Mod/commit/b8d549d1fe3102da5e76d9ecb51782dc8d30a03b
The proposed fix is to disable the visibility check for the outer ring (one past the unit's actual sight range).
I suspect that the outer ring check in CvPlot::canSeeDisplacementPlot fails to calculate the visibility for water features correctly.
Of course it would have been better to rewrite the function entirely and use some sort of ray-casting method (and also get rid of the recursion). 
Note that if this turns out to be the fix, then this is actually a bug that we've inherited from Civ4!

**Comment by raystuttgart** [comment]
Considering "another bug inherited from Civ4BTS":
That is possible of course, because our mod WTP does things Civ4BTS and Civ4Col Vanilla have **never considered**.
For example **"Winds and Storms" (water features) change Visibility** on Ocean. - Something like that never existed in Civ4BTS.
And as far as I understand, this **only happens on Ocean**.
If the fix works and is performant everything else does not really matter.

**Comment by raystuttgart** [comment]
**Important question though:**
Does this somehow change / reduce visibility on Ocean during normal gameplay?
e.g. the plots uncovered when your Ship has Promotions that have "+1 Visibility"?
(Sorry if I ask stupid questions.)

**Comment by dcrookston** [comment]
Yes, there are storms and good/bad winds that obscure vision on the ocean.
They obscure it even when your ship is right next to them though, they
don't need the +1 visibility promotion to be affected by it.

Incidentally I think it's silly that good/bad winds obscure vision but
that's another topic entirely.

**Comment by ErikSandbraaten** [comment]
The crux of the issue turned out to be a missing initialization of the visibility range cache (that I introduced during 2.7.x). The cache was correctly set during map creation but not when loading a savegame! Sorry about this incident!

**Comment by MrZorG33** [comment]
I downloaded river_merge from GitHub, created a DLL according to Nightingale's instructions and started a new game. after a while, randomly visible tiles in the ocean appeared again.
![опять видимые плитки в океане01](https://user-images.githubusercontent.com/61798883/115979967-baef0680-a591-11eb-95eb-18e390ef160a.jpg)

**Comment by Nightinggale** [comment]
Confirmed. It still happens when there is weather under certain conditions.
