### ISSUE TITLE
Ships in a port die instantly when hostiles enter tile

### ISSUE THREAD

**Issue by Alignn** [We-the-People-civ4col-mod/Mod#257]
If an enemy tries to move a land unit into one of your cities with ships in it (but otherwise empty of units), they instead destroy one ship (with no fight) until all ships are gone and they capture the city. This is sad, but not completely unexpected - they died ineffectually defending your stuff.
If an enemy does the same to a friendly (to both you and your enemy) port city, your ships are also instantly destroyed. This feels surprising and unfair.
Might be a leftover from Civ 4, but we could do better:

If hostile troops enter a city, all ships are moved out to neighboring tiles. Preferably coasts, not lakes.
This makes sense from a gameplay perspective - instantly losing ships is frustrating, but having land units fight ships wouldn't work because of the strength differences - and also an immersion perspective - ship captains wouldn't just sit on their hooks while enemies march toward the dock.
If there's a blockade of hostile ships in each adjacent tile, bigger ships will fight to the death, and if they fail, any smaller ships (fishing, whaling, coastal) are captured.

**Comment by ErikSandbraaten** [comment]
I think the current rules that you describe is a hold-over from Civ4 where all ships would get destroyed if the city where they reside is captured. However, ships are rather costly\precious in WTP so it would make sense to allow them to escape. There's already a chance for ships to escape\evade if they loose in combat. I think that a suitable mechanism would be to let the ship(s) sustain some damage and then eject the ship to a non-lake water plot.

**Comment by raystuttgart** [comment]
I can take care of this if everybody agrees to do it this way.
(Ejecting the ships with some damage instead of instantly destroying when city is captured.)

**Comment by raystuttgart** [comment]
As it seems, Nightinggale, devolution and myself are ok with "ejecting damaged instead of destroying" when a town is captured by the enemy.
Since there are no other opinions on that currently, I will start coding.

By the way: 
If they cannot be ejected, because the enemy has blockaded the port with his ships the current logic of "destroying" will still be used. Ejecting will only happen if there is a free water plot with access to Europe.

If anybody disagrees, let me know before I have spent too much wasted effort into this.

**Comment by ErikSandbraaten** [comment]
I support ejection. The same logic should hold for forts as well I suppose. Keep in mind that a ship may already be damaged so it should not be reduced by a fixed amount. If you check the code for capturing colonists you'll find that they will suffer some random damage (about half of their current hp I think) upon be captured and we may reuse this.

**Comment by raystuttgart** [comment]
I still remember my implementation of capturing colonists and was going to use it as an example to be partially reused. Thanks for reminding me though.

I had not thought about the Forts - good that you however thought about that.
I will need to check what I can do with that.

About your comment on "refactoring":
Do you have any idea or even a concept already how the could be written better?

**Comment by raystuttgart** [comment]
This is fixed / improved now.
(For both, Cities and Forts)

Instead of being destroyed, they are now just ejected but with random damaged (but only if there is a free Water-Plot that is not blocked by enemy Units).
Otherwise they are destroyed like before. Thus blockades might become more interesting.

Texts now also show Ship names not only Ship Types

Tested several times and seems to work fine.
No Asserts either.

Will commit to fixes.
(Together with TXTs)
