### ISSUE TITLE
Changing profession (e.g. scout, cavalry) in an emptied colony (about to be abandoned) does not subtract goods

### ISSUE THREAD

**Issue by Alignn** [We-the-People-civ4col-mod/Mod#258]
I'd conquered a colony that had 221 horses, and emptied it of colonists so I got the "Your colony will be abandoned" popup. After emptying it I realized I could save some of the horses by turning colonists into scouts, so I started doing that - and noticed the number of horses wasn't going down. 
In the end I was able to turn 6 colonists into Scouts, and when I had a non-scout colonist enter the colony again (just to check if it was just the interface that wasn't updating), the number remained at 221. I was even able to increase the amount further by turning my Scouts back into regular colonists.

I checked with a unit of Cavalry in one of my own colonies, and much the same there - I could turn every colonist into Cavalry without using up any equipment. In this way you can instantly conjure up as many military units you like, as long as you have the (non-native, non-slave) population for it, and one to start with. And of course, you get infinite horses/guns/blades/tools.

**Comment by ErikSandbraaten** [comment]
A savegame would be helpful!

**Comment by Alignn** [comment]
[Here's one](https://www.mediafire.com/file/s73zohtc1unsf7d/WAR.zip/file), but you can just start a new game and after founding a new colony with your starter units, and reproduce the issue at any time.

**Comment by ErikSandbraaten** [comment]
I've observed the following while debugging:

CvUnit::canHaveProfession  (by setting a conditional breakpoint with eProfession == 61)

```cpp
			if (kOwner.hasContentsYieldEquipmentAmountSecure(getProfession()) || kOwner.hasContentsYieldEquipmentAmount(eProfession)) // cache CvPlayer::getYieldEquipmentAmount - Nightinggale
			{
				for (int i=0; i < NUM_YIELD_TYPES; ++i)
				{
					YieldTypes eYieldType = (YieldTypes) i;
					int iYieldCarried  = kOwner.getYieldEquipmentAmountSecure(getProfession(), eYieldType); // cache CvPlayer::getYieldEquipmentAmount - Nightinggale
					int iYieldRequired = kOwner.getYieldEquipmentAmount(eProfession, eYieldType);
					
					if (iYieldRequired > 0)
					{
						int iMissing = iYieldRequired - iYieldCarried;
						if (iMissing > pCity->getYieldStored(eYieldType))
						{
							return false;
						}
					}

					// Erik: This is just a temporary hack to stop the free stuff exploit!
					if (iYieldRequired == 0)
					{
						if (pCity->getYieldStored(eYieldType) < 50)
						{
							return false;
						}
					}
				}
			}
```

The following line seem to be the problem:
Int iYieldRequired = kOwner.getYieldEquipmentAmount(eProfession, eYieldType);
returns 0 which indicates that this player does not need any horses for the scout profession. Consequently, there is no check against the city's storage of horses (since it would be redundant)

I then added the code block "temporary hack" to force a check for the yields being available which did stop the exploit, albeit it's not a proper fix of course.

@Nightinggale could shed some light in this since he knows more about this caching scheme.
