### ISSUE TITLE
Forts don't grow into great forts with all military units, only the colonial militia.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#26]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-117#post-14969798 

> One bug has been recognized:
> 
> Forts will only grow up to great forts in case you put a colonial militia in it. In case you put other military units into it (e.g. cavalry, artillery, ranger, line infantry) it does not work. This is strange...has anyone else this issue?
>

**Comment by ErikSandbraaten** [comment]
There's already a ticket for this here:
https://sourceforge.net/p/religion-and-revolution-git/tickets/7/

A couple of months ago or so I spent some time analyzing  these issues and it turns out there are multiple fort related bugs. We need a full overhaul of everything related to forts like activation, bombardment, growth etc.

**Comment by ErikSandbraaten** [comment]
Here are some more thoughts from my braindump doc:

Fort activation rule:

Profession \ unit must have either UNITCOMBAT_GUN  or UNITCOMBAT_SIEGE and
It must be able to receive defensive bonuses. This makes the rule consistent with cities, which is an important criteria.

In other words all infantry with guns and the light artillery can activate the fort.
Heavy artillery, scouts, cavalry, dragoons, conquistador cannot.

The rule concerning forts should be the same as for city defense. Why can a unit defend a fort but not a city?
This makes sense since cavalry\conquistadors(melee) cannot defend a fort

CvCity::doExtraCityDefenseAttacks()
CvPlot::doFort()

These contain redundant code and should be refactored
We can check combatclass like this : UnitCombatTypes eArcherType = (UnitCombatTypes)GC.getInfoTypeForString("UNITCOMBAT_WHATEVER");
	


enum DllExport UnitCombatTypes
{
	NO_UNITCOMBAT = -1,
};


Need to add these to get the fort logic right

**Comment by ErikSandbraaten** [comment]
More work is needed, but forts work more sensibly now

**Comment by ErikSandbraaten** [comment]
Should have remained fixed for a looong while
