### ISSUE TITLE
Draining marshes should require windmills

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#275]
The BuildInfo used to drain marshes should require a colony with a windmill within X plots. Wind power was the primary power source for pumps in draining projects (small or large) prior to steam power.

An implementation would likely require some sort of cache in CvPlot. It would likely be too slow to search the map for colonies within range each time a pioneer has to figure out which builds are valid (a frequent issue)

**Comment by raystuttgart** [comment]
Hi guys,

something like this is way too **difficult to explain or visualize** to players.
Something **that small is really also not even worth the effort** of coding. Almost **no player** will care to my opinion.

Please let us NOT make features overly complicated **just for immersion**.
Especially since our own understanding and immersion might be completely different from that of other players.

**Comment by raystuttgart** [comment]
Are we really going to write such code?
This may

A) not be liked by everybody
B) hard to understand by players
C) not working in other mods
D) hard to maintain in the future with changes in Improvements
...

Guys, let us get serious again with our efforts and todos.
