### ISSUE TITLE
Wrong Icon

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#279]
The determined trait seems to display a rare fur icon. Rather than the bell. 

![Screenshot (4)](https://user-images.githubusercontent.com/49459725/65467339-d5498700-de26-11e9-9f88-b3606cfc0e8c.png)

**Comment by Nightinggale** [comment]
CIV4GameText_Colonization_utf8.xml:

```xml
<Tag>TXT_KEY_TRAIT_REBEL_COMBAT_MOD</Tag>
<English>[ICON_BULLET]%D1%% effect of [YIELD_BELLS] on Rebel [ICON_STRENGTH]</English>
```

Apparently [YIELD_BELLS] is translated to the wrong GameFont ID. Sadly it looks like this is done inside the exe file, meaning we can't actually fix the bug. Instead we have to work around it somehow, like add a search and replace feature to TXT_KEY reading. This is more work than I thought when I saw the screenshot, but adding such a search and replace feature can be done as a list of pairs like replace A with B. This way we can add support for stuff like [ICON_HEALTH].

First step would likely be to add a new debug screen in domestic advisor, which shows all the valid [whatever] and what they will print. Since we do not have a list, we should use a script to read the vanilla strings to harvest everything written in [ ] brackets. That will aid us in the sense that we will finally actually get a full list of what can be used in TXT_KEYs.

Another semirelated bug is that TXT_KEY_TRAIT_REBEL_COMBAT_MOD is also present in CIV4GameText_RaR_Release1_utf8.xml. Obviously each string should only be included once.

**Comment by raystuttgart** [comment]
Hi guys, 
I don't know why this text was changed to have the Icon [YIELD_BELLS] in WTP (or RaR 2.7) but **in RaR 2.5** there was NO ICON in this text, it just said **"Revolutionary Rate"** (as text) **instead**.
`
<Tag>TXT_KEY_TRAIT_REBEL_COMBAT_MOD</Tag>
<English>[ICON_BULLET]%D1%% effect of Revolutionary Rate on Rebel [ICON_STRENGTH]</English>
`
I even believe had know this bug and thus fixed it purposely that way.

**Comment by raystuttgart** [comment]
It is fixed now.
