### ISSUE TITLE
2.8 Yield Branch: AI Ship Issues

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#293]
The AI ships act very strangely, when near the edge of the map, near or inside the "Travel to Europe area". Constantly turning in circles and travelling back and forth, rather than effectively patrolling.

The AI also loves to spam Coastal Boats. These become very easy targets for Privateers and can be "farmed" for experience in war time.

**Comment by ErikSandbraaten** [comment]
A fix for the overproduction of coastal transports was commited here: https://github.com/We-the-People-civ4col-mod/Mod/commit/7aeaf0d574081947f03da2b22ceb66c15568fa81

Will have a look at the ship AI soonish I hope

**Comment by ErikSandbraaten** [comment]
I am assuming that you are talking about combat ships ? There are a number of issues with them:
- The erratic movement is caused by the ships responding to animal "threats" which is wrong IMHO
- Combat ships often end up hanging around in the Travel to Europe tiles because they lack the code to patrol properly.
- Combat ships fail to escort (as in grouping or shadowing) transports ships, thus allowing privateers to pick off nearby transports that should have been protected.
- AI players do not purchase combat ships in time before privateers become commonplace.

I should hopefully able to resolve these issues in this branch which is mostly concerned with Naval AI issues:
https://github.com/ErikSandbraaten/Mod/commits/better_ai

**Comment by ErikSandbraaten** [comment]
Removing the bug label. The overproduction of coastal ships was a genuine issue that has been solved by now. As for the naval AI behavior, it works as intended but is very sub optimal thus the AI label is kept and IDEA added.
