### ISSUE TITLE
Changing names / correcting English

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#304]
Whilst playing, I have noticed a number of small errors, or occasions when another word would be better suited, often for reasons of historical accuracy. I have added the XML where it is different from that displayed ingame. So here are my suggested changes:

### Roads

I think the current terms are a little confusing, the country road sounds inferior to road and the term plastered road doesn't exist in English. So I propose replacing them with historical terms.

Sources : https://en.wikipedia.org/wiki/King%27s_Highway_(Charleston_to_Boston)
 
               http://eh.net/encyclopedia/turnpikes-and-toll-roads-in-nineteenth-century-america/

**Current term** :  Road                        **New term :** Trail

**Current XML**
        <BuildInfo>
            <Type>BUILD_ROAD</Type>
            <Description>TXT_KEY_BUILD_ROAD</Description

**Current term :** Country Road           **New term :** Toll Road

**Current XML**
<BuildInfo>
            <Type>BUILD_PLASTERED_ROAD</Type>
            <Description>TXT_KEY_BUILD_PLASTERED_ROAD</Description

**Current term :** Plastered Road          **New term :** Highway

**Current XML**
<BuildInfo>
            <Type>BUILD_RAILROAD</Type>
            <Description>TXT_KEY_BUILD_RAILROAD</Description

### Units and Professions 

I think we should use these terms because they are more historically accurate. Although ship names present a problem, as this was an age before standardisation, so there are many different names for ships which are functionally very similar. Sloop was a generic term, whereas Sloop-of-war was a class of ship in the Royal Navy.

**Current term :** Renowned Medic   **New term :** Physician

**Current XML**
<UnitInfo>
            <Type>UNIT_DOCTOR</Type>
            <Class>UNITCLASS_DOCTOR</Class>

**Current term :** Small Boat               **New term :** Packet Boat

**Current XML**
<UnitInfo>
            <Type>UNIT_SMALL_COASTAL_SHIP</Type>
            <Class>UNITCLASS_SMALL_COASTAL_SHIP<Class>

**Current term :** Large Boat              **New term :** Schooner

**Current XML**
<UnitInfo>
            <Type>UNIT_BIG_COASTAL_SHIP</Type>
            <Class>UNITCLASS_BIG_COASTAL_SHIP</Class>

**Current term :** Conestoga              **New term :** Conestoga Wagon
**Current XML**
<UnitInfo>
            <Type>UNIT_CARRIER</Type>
            <Class>UNITCLASS_CARRIER</Class>

**Current term** : Sloop                      **New term :** Sloop-of-war

### Traits

This is just a matter of correcting English.

**Current term** : Farmers             **New term** : Farmer

**Current term :** Undemanding        **New term** : Efficient

**Current term :** Imperial                 **New term :** Imperialistic            

**Current term** : Conquistador      **New term** : Conquistadors

**Current term** : Forest Warriors       **New term** : Forest Warrior

**Current term** : Hunters                **New term :** Hunter         

**Current term** : Coastal Warriors  **New term :** Coastal Warrior

**Current term** : Nomads          **New term** : Nomad

**Current term** : Raiders             **New term** : Raider

### Buildings

This is more of a matter of historical veracity. There were few abbeys in the Americas and most of their members were secluded, also there was no monastic tradition in many of the Protestant churches featured in the game during the period. There is also no monastic profession in game. There is no such thing historically as a "Cathedral of the Archbishop" and the only Archbishop featured in the game is the one you speak to via diplomacy, also the Dutch and Danish Churches are not led by an Archbishop. Whilst the term metropolitan is associated with the Catholic and Orthodox Church, I don't know if its possible to have different Civs have different names for the same building, or have the building restricted to the Catholic and Orthodox factions. I have added the XML where it is different from that displayed ingame.

**Current term** : Church                                          **New term** : Parish Church 

**Current XML**   
<BuildingInfo>
            <Type>BUILDING_CHURCH</Type>
            <BuildingClass>BUILDINGCLASS_CHURCH</BuildingClass>

**Current term** : Abbey                                                 **New term** : Church 

**Current XML**
<BuildingInfo>
            <Type>BUILDING_CATHEDRAL</Type>
            <BuildingClass>BUILDINGCLASS_CATHEDRAL</BuildingClass>

**Current term** : Cathedral                                               **New term** : Cathedral 

**Current XML**
<BuildingInfo>
            <Type>BUILDING_GREAT_CATHEDRAL</Type>
            <BuildingClass>BUILDINGCLASS_GREAT_CATHEDRAL</BuildingClass>

**Current term** : Cathedral of the Archbishop                   **New term** : Metropolitan Cathedral 

**Current XML**
<BuildingInfo>
            <Type>BUILDING_MINSTER</Type>
            <BuildingClass>BUILDINGCLASS_MINSTER</BuildingClass>

**Current term** : Wine Factory    **New term** : Large Winery

**Current term** : Beer Factory    **New term** : Large Brewery

**Current term** : Rum Factory    **New term** : Large Rum Distillery

**Current term** : Grand Opera    **New term** : Opera House

**Current XML**
BuildingInfo>
            <Type>BUILDING_OPERA</Type>
            <BuildingClass>BUILDINGCLASS_OPERA</BuildingClass>

**Comment by raystuttgart** [comment]
Hi guys, 
seriously let us not be more christian than the Pope.

Most of those terms are still from RaR and we had Native English Speakers on board that helped with translations and spell checking - none of them complained about these terms.

None of the terms I read there are really wrong to my opinion.
But if we start changing we should have a Native English Speaker take a look.

And to my knowledge it is not possible to have just different names for different Nations.
We could of course give them completely different Buildings just to change the name - but that is really wasted effort.

Some of the suggestions I don't even like.
"Highway", "Parish Church", "Metropolitan Cathedral"

Let us forget this and not waste our efforts.

**Comment by Drunk-Monk** [comment]
I was assigned this task by @Nightinggale because the names in game and in the xml are not coherent. As for the other issue your correct, its your opinion, but terms like 'Plastered Road' and 'Cathedral of the Archbishop' are confusing and we can have better alternatives.

**Comment by Nightinggale** [comment]
> I was assigned this task by @Nightinggale because the names in game and in the xml are not coherent.

First of all, my main focus was to find the cases where displayed name and internal name mismatch like Plastered Road being called ROUTE_RAILROAD internally. Accepting ingame names and xml names to drift more and more apart would be future bugs waiting to happen because modders gets confused.

I was thinking of tweaking the issues regarding naming, not tweaking everything. When you change something, what you change to should be better. Removing the `Factory` keyword isn't better because right now we have factories as a keyword for production bonus. This means the player will notice the pattern that if a building is named something with factory, output will increase even if the colony can't provide more of the input yield. We have that naming convention fairly consistent and moving away from it would likely be a mistake.

> Current term : Country Road New term : Toll Road

I actually like Country Road better because the players live in a modern world where Toll Road means a road where  you have to pay to use it. This isn't the message the game wants to give. Trail is a fine name though.

Highway might have the same issue, but to a much less degree. It's certainly not worse than plastered road.

> Current term : Cathedral of the Archbishop New term : Metropolitan Cathedral

I don't think Metropolitan is the correct word. Maybe Grand, if we rename at all. I like the other names though. I don't like the name Abbey because while I know the name, I will not intuitively know the rank of it relative to the other church buildings. Your proposed names fixes that.

> Current term : Farmers New term : Farmer

If we are to change this, then the new name should be `[Farmer:Farmers]` because that way we can let the dll pick one based on the number of units. This means it will say 1 Farmer, 2 Farmers etc. We can also apply gender to names, which in turn can be used when inserted in other strings, which can then have `[1:him:her]`.

While this would be the correct approach, I question if it's worth the time just to add/remove the trailing s. It's likely something we should have added from the start as going through all the places it's used now could be time consuming.

We could add it and then add support in new code we write and maybe fix in existing code when we happen to come across it anyway.

**Comment by raystuttgart** [comment]
This is outdated.
We massively corrected the English texts the last years.
