### ISSUE TITLE
Wild Animals and promotions 

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#310]
I feel there needs to be a streamlining in the amount of military promotions available. Many seem to be very repetitive, for example Forced March is a better version of Explorer. Homeland Guard an overpowered form of Minuteman. The Piracy and Merchant Vessel promotions also provide a negative attribute, which is inconsistent as it goes against the solely positive manner of the other promotions. The Great Discoverer promotion is also incredibly overpowered.

I think that the sea creatures should be only visible or (be vulnerable to being attacked by) by the fishing, whaling and coastal boats. It just seems absurd that a frigate would go around chasing giant squid or sharks. The Animal Hunter promotions should be restricted to Scouts and the aforementioned Boats, as its pretty useless for every other unit as they can easily overpower wild animals.

**Comment by ErikSandbraaten** [comment]
I agree that promotions (as well as the combat system IMHO) are a mess the moment and they could do with a complete overhaul.

The idea of having both pros and cons is actually a but appealing to me because that would curb the idea that more of something is always better. What if homeland guard kept the 15% combat in friendly territory but had -5% combat outside ?

**Comment by raystuttgart** [comment]
That is long taken care of.
