### ISSUE TITLE
Reform the food mechanic

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#312]
Reform the food mechanic, as it is an easy exploit to get Free Colonists by collecting small amounts of food from each colony and then dumping this large collection of food onto a smaller colony. Its also relatively trivial to have large colonies in inhospitable locations. Also, there are few consequences for starvation, and no food cost for units outside of settlements. Historically (quite understandably) food production was the number one priority and many of the early colonies failed or struggled to survive. Perhaps to add more peril to the prospect of starvation, you could receive a penalty like a revolt that halts production, or lose a percentage of Rebellion rate, this would mean that you would have to focus on co-operation and trade more with the natives (who would have abundant food resources in the early game), to stop the player being destroyed in the early game. You could also add the option to request food, from the King and Archbishop through diplomacy.

**Comment by ErikSandbraaten** [comment]
Yes, in my opinion this is a serious exploit that is easily abused by human while the AI is not coded to take advantage of this at all.
Food is generally a bit too easy to come by and WTP suffers from "yield inflation" and could to with a bit of re-balancing. Part of the problem is the "tier 2" improvements such as the "large farm" which make farms more productive after a while. Maybe the first farm level should be less generous and the second should give the full improved yield? The 2 plot radius also exacerbates this issue due to allowing the various improvement multipliers of a city to be applied to even more plots.
#338 should go a long way towards fixing this by making high food plots less abundant in general.
In particular we could consider "soil depletion" or a similar mechanism to make "overworked" farms less productive rather than more productive to mirror history a bit.

**Comment by raystuttgart** [comment]
Depletion mechanics of resources actually was discussed several years ago and it even had been implemented by one mod already. (Currently cannot remember though which one.)

However the feature was only used for mining resources (like Iron Ore or Silver).
It was only applied on their Bonus Resource and at depletion only the Bonus Resource was removed.

Thus AI could still handle it because the at least the base Yields stayed on the plot.
If we really applied this on the base Yields though, this might be difficult for AI to handle.

From the feedback I read and if I remember correctly, most players really did not like it.
It is not really a feature that casual players want to have.

To be honest I would not like to play with the feature myself.
But if we had it as Game Option (when starting a new game) or as XML-setting I would not mind if it was implemented.

**Comment by ErikSandbraaten** [comment]
I'm sorry if I vented a little bit concerning food but I really think that food is too easily obtained and that plots yields are overall a bit too high in general.

**Comment by raystuttgart** [comment]
Couldn't we just implement a modifier for Plot Yiels and Produced Yields depending on difficulty?
(That could be done in the XML settings for the Game Difficulty Levels.)

Or alternatively have Game Options "reduced Yields"?
(That would actually be might preferred solution from gameplay perspective because it gives most flexibility.)

That should satisfy alsmost everybody.

**Comment by Nightinggale** [comment]
The problem with nerfing food production is that it shouldn't be too hard to start. While it might be realistic to have severe issues providing food for early settlers, it would likely be a mistake from a gameplay perspective. If people find it too hard to get started, they could drop the game instead. Also even if people stick with it, it might not be as much fun.

Sid Meier made a mistake in the original Civ, which was changed prior to the first release. He had the idea that severe negative events could occur, making the big civs become worse and then give the player the enjoyment of fighting back to becoming the major player again. However the focus group (essentially play testers/beta testers) loaded a savegame each time it went bad and never experienced the enjoyment of coming back up. Apparently the fun in playing and certain hardships are incompatible for most players.

We need to balance early and late food production without making the improved food production facilities so weak that people don't bother with them. This is certainly easier said than done.

One option could be to use #320 to store fractions of food and that way we can let units each 2 food/turn +X%, where X is the population count. This will make big cities require more food than they do now without really breaking early colonies. The question is if it's confusing for the players.

**Comment by raystuttgart** [comment]
Yes, good balancing is extremely difficult.

Balancing of Yields was one of the most often discussed topic of all times considering RaR.
Some Players were always complaining that Yields were too abundant, others wanted even more ways to get bonus modifiers and others were happy as it is.

I am also against "random punishment" of Players though. They need to understand what is happening and be able to prevent it.

Also, we should be carefult that we don't affect AI negatively. I don't want to make it weaker as it already is. We could always compensate of course by hidden AI cheats.

Generally I think:
A) Let us at some point implement "Satisfaction / Happiness" game mechanic which will mainly affect big cities and see how it will turn out.
B) Optionally we could also still keep the Game Option "Reduced Yields" in mind. It would definitely be an interesting Game Option for players that like an extra challenge.

**Comment by LibSpit** [comment]
I don't think the issue described is one of food abundance, rather it is 'exploiting' a game mechanic to the Nth degree, when the AI does not understand how to do it too.

Getting New Colonists by organising and centralising your food production/storage is one of the rewards of good planning.

The two main issues seem to be:
1: The  AI can't do it so it falls behind in population.
2. You an cheese it by cloning settlers in a tiny village..

I don't think having high population and production is an issue, so long as the AI is on a parity with you. Fighting with two large colonial forces is pretty cool. As well as seeing the AI develop mega cities on the same scale as your own.

The two solutions would seem to be:
1: Fix the AI (the solution to all things :D ) either by teaching it to move excess food around and store it in a single location, or through some magical teleportation/food consolidation cheat?!
2. 'Lock' Growth out of small settlements, so that only cities (insert definition here, pop cap./building/whatever) So that you have to produce more food to get a baby boom. 

Perhaps having a building that produces 'growth' from food separating it from the eating/starvation system. Then a larger city could also have access to a bigger/faster growth producer. Hospitals or the like. Taking food and converting it to the new Growth yield using doctors or midwives or whatever other fluff works.

This could also mean you could change the early game to be more about importing food to your colony to survive until it becomes a more self sustaining enterprise, without giving the player the ability to 'ship in' a bunch of growth spurts, as they have to convert food to growth over time. It would also limit just how much one location could achieve for growth, meaning that you may need to have multiple birth farm cities, to maximise the exploitation of your food production.

This way a well organised player can still exploit food production and be rewarded for good planning with lots of new colonists to produce mountains of goods or paint the new world red with the blood of your enemies, but it is not a simple shunt and dump exercise.

**Comment by raystuttgart** [comment]
This is already discussed in the forum here now:
https://forums.civfanatics.com/threads/changing-growth-mechanics-to-be-more-immersive-open.677105/

Thus this issue is just redundant.
(Such discussions are better handled in the forum.)
