### ISSUE TITLE
Colony happiness / management 

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#317]
Whilst the mod has some of the notions towards the health and happiness mechanics of Civ 4, it would benefit to be fleshed out, adding another dynamic to the game other than just trying to produce as much as possible, as quickly as possible. For example, colonists could request that you build educational, religious and entertainment buildings, and supply certain goods (Tobacco and Alcohol for example). These would rise in complexity and price as the game goes on, happiness would also be shaped by Native Raids, lengthy wars, Pirates etc. At the very least a notification, when your city becomes unhealthy would be nice 😊

Food supply would also be related to this, as a hungry populace will be an unhappy one. #312

**Comment by Nightinggale** [comment]
I'm not too happy with the health implementation. The issue mentioned in #320 hits health hard as 3/turn -1%=2/turn.

> other than just trying to produce as much as possible, as quickly as possible. 

What other metric do you intend to introduce? I mean happy people will produce more of something (cargo, population units, gold, independence etc) or happiness will be irrelevant.

We do have a domestic marked, but currently all it provides is gold. The population will not care if they are being supplied with whatever they request or nothing at all. If we are to benefit more, improved automated cargo transport between colonies will have to be improved as well or it will end up being unused and possibly annoying due to drowning in micromanagement.

**Comment by Drunk-Monk** [comment]
> 
> What other metric do you intend to introduce? I mean happy people will produce more of something (cargo, population units, gold, independence etc) or happiness will be irrelevant.
> 

I think I haven't made myself clear. We are both in agreement that happiness should boost production. I mean in terms of the big picture, Col is meant to be a 4x game with a focus on the economy, however the main objective of the game is production, everything else is of lesser importance. Because of this I believe game-play suffers, there is little in terms of risk reward and the late game especially becomes very predictable and formulaic.

**Comment by raystuttgart** [comment]
Happiness System is implemented since ages now.
Also I implemente a "Health Overhaul" in "Plains".

Issue is thus now obsolete.
