### ISSUE TITLE
Shipwrecks

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#324]
Is it possible to have Shipwrecks spawn randomly throughout the game and drift, rather than have them pre-spawned at the beginning of the game? It’s strange to arrive at a new continent full of European wrecks, more than there are ships constructed in the average game. Also, the real benefit is providing experience to your early ships, which counter intuitively end up faster than your later ships, who don't have the opportunity to gain as much experience. #241

**Comment by raystuttgart** [comment]
The current solution was done for simplification.
Yes, theoretically they could be spawned during the game ...

**But:**
- It would be not really ideal for performance because you would basically loop through the complete map to find good points to spawn
- Shipwrecks would be spawned in areas the Player had already searched so he would need to search the Ocean all the time - I would personally hate to do that.
- It would be quite hard to balance (find a good spawn rate)

Summary, I really don't like that idea and would rather leave everything as it is.
It is better for performance, better for gameplay and easier to balance.

**Comment by raystuttgart** [comment]
By the way:
What does "partially implemented" mean in this case?
What was already implemented for that?

**Comment by Drunk-Monk** [comment]
It was referring to the fact that whilst shipwrecks already exist in the game, I believe they could be better implemented.

**Comment by raystuttgart** [comment]
Ok, so there has no effort been invested into this issue yet.

Of course a lot of things can be done better considering immersion.
But we also need to consider the price for that, e.g. effort, performance, gameplay / balance, ...

For me personally in this case the price is simply too high considering the benefit.

**Comment by raystuttgart** [comment]
Hi guys, this is "no bug" and "no issue".
If somebody wants to improve / overhaul Ship Wrecks a new thread for discussion in the forum should be started.

"Respawning Water Goodies" / "Land Goodies" is by the way something I have on my "wish list".
(Since we recently created e.g. "real Shipwrecks" and "Camp Fires" that is basically the idea for the next expansion of the Goody System.)

It still would need to be clarified **in the forum** though. 
(These issues are the wrong place to discuss features.)

I will close this, because it was a**lso suggested by @Fuerstbischof** in his recent **thread about "Naval issues in 2.8.2.x"**.
We do not need to discuss the same thing in 2 places. (And this is the wrong place to discuss and decide features.)
