### ISSUE TITLE
Slavery

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#335]
As pointed out by many players, slavery is one of the weaker aspects of the mod. Slaves are overly cheap and present a nuisance rather than a threat, to remedy this I think that slavery should have more depth and consideration. It would be great to see slave revolts, as these were a constant problem and source of anxiety for the slave holders, the independent communities that the slaves formed also affected the balance of power internally and between the competing states, and in the case of Haiti fought a major war to become an independent country. 

Rather than the situation now where a slave deserts only to run around aimlessly, slaves should try to seize arms and/or horses and either join Native communities or establish their own, becoming basically a new Native power. This would operate in the same manner as the Natives, able to gather resources and trade, engage in diplomacy etc However the presence of the settlement should encourage other enslaved units to revolt and desert, and for them to try to join the settlement or initiate their own. Example of this type of settlement from history are the Maroon settlements of Jamaica, Guyana and Surinam. The Free Africans of Cuba, Dominican Republic, Puerto Rico and Colombia. The Miskito, Garifuna and Cimarron of Central America and the Quilombos of Brazil. 

To complement this the mod should also implement manumission, where Slaves can over time become free citizens, this would utilise the “learning by doing” mechanic, but at the end the player would pay to transform the unit into a Free Colonist. 

Leaderhead Ideas : Zumbi, Toussaint Louverture, Queen Nanny, Jean-Jacques Dessalines, Cudjoe, Benkos Biohó, Gaspar Yanga, Bayano

#77 #233

**Comment by Nightinggale** [comment]
Sounds like you want to make runaway slaves gain their own player entry, which would then be different from the wild animals (barbarian) player. In theory each revolt should generate a new player, but we don't have unlimited slots. There is an exe limitation as well as memory/performance penalties from increasing the max number of slots even if they aren't used. A single player would likely be a decent tradeoff in this regard.

A I mentioned on the forum, civics are used when declaring independence. We can add more categories and make some independence only and others able to be set in a menu like in BTS. This would make it possible to give slaves production bonuses (even negative) and affect their odds of running away/revolt. No upkeep as that isn't easy to implement in a gameplay reasonable way. Because of this each civic should include a bad part, which is a tradeoff for the bonus now that we can't do that with upkeep.

> To complement this the mod should also implement manumission, where Slaves can over time become free citizens

I would rather have it easy for them to become freed slaves. For game balance reasons, freed slaves would have to be the worst units in the game in terms of production, but they will not be able to run away or revolt. Also they gain the ability to educate themselves towards ending up as free colonists.

Being able to convert directly from slave to free colonist would likely backfire big time from a game balance point of view.

**Comment by Drunk-Monk** [comment]
I agree with all of your ideas, although I think there would need to be the implementation of some form of tech tree or "progress", for civics to work well.

**Comment by raystuttgart** [comment]
Hi guys,

I opened a [thread to "Improve Slavery"](https://forums.civfanatics.com/threads/making-slavery-more-interesting.656425/), which should basically replace this issue.

Spawning a new Civ out of nowhere would most likely not really work anyways and be way too much effort to implement all the Civ Details.
(We might one day have the "Pirate Civ" anyways, that could also be used for "Revolting Slaves".)

I will thus close it.
