### ISSUE TITLE
WTP 2.7.2 beta1 - Founding Father's 2 galleons appearing

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#340]
When I accept the Founding Father's offer (Giovanni da 
Verranzo from the Discovery-Tree) of getting 2 Galleons ...
they appear on the plot of a exploring ship in the middle 
of the map ...
maybe they should appear in the national port in europe 
or the main colony?

**Comment by raystuttgart** [comment]
Yes, this is an really old issue, although it was always considered to be minor.

Of course it can prably be adjusted quite easily.
The solution to spawn them in Europe sounds good.

By the way:

This is not the only FF that gives free ships where this happens.
All of them appear on a tile (anywhere on the ocean) where there is another ship.

I believe it was implemented that way because it was easy to do.
(It should prevent ships to be spawned too far away or in an inland lake.

- Another FF gives a free Caravela Redonda. (Ferdinand Magellan)
- Another FF that gives 2 free Fishing Boats. (Jean Talon)
- Another FF gives 2 free Pirate Fregates (Blackbeard)
- Another FF gives 2 free Privateers (Francis Drake)
- Another FF gives 2 free Galleons (Giovanna da Varrazano)
- Another FF gives a free Brigantine (Jacques Cartier)
- Another FF gives 1 Corvette and 2 Frigates (Jean Talon)
- Another FF gives 1 Free Merchantman (Michel de Ruyter)
- Another FF gives 2 free West Indiaman and 1 Privateer (Piet Heyn)
- Another FF gives 1 free Ship of the Line (Walter Raleigh)
- Another FF gives 2 free Whaling Boats (William Barentz)

Just by reading the list I just realized that the issue might not be as minor as I thought.
(But as I said it should be relatiely easy to fix.)

**Edit:**
We need to be careful though with Ships that are not allowed to sail to Europe.
Those should not be spawned ther because it might lead to bugs / crashes.

**Comment by Nightinggale** [comment]
How about looping the colonies and spawn in the first colony, which has access to Europe? This will in most cases make the units spawn in the first founded colony because the list of colonies is sorted by founding order.

We still need to figure out what to do with a player with no valid colonies. It's unlikely, but certainly possible. The ocean starting plot would seem like a good option for that case.

We should have shared "spawn plot locators" in the dll, possibly with multiple different approaches and then the spawning events/FF/whatever can use xml to pick which system best matches the case in question. We shouldn't do something like this with a case by case coding approach.

**Comment by raystuttgart** [comment]
We could maybe have the following logic:
(should be pretty save)

Ship that can be bought in Europe 
-> spawn in Europe (thus it could also directly pick up settlers)

Shipt that cannot be bought in Europe 
-> spawn in best "PortCity" if available -> iAI_findBestPort method could be used for that
-> spawn as now if noPort is available

**Comment by raystuttgart** [comment]
Hi guys

I will look into this and implement an improvment.
Should probably not be too difficult and thus a good start to get back into coding Civ4Col again after my retirement from modding for so many years.

@Nightinggale I will push this then to the "fixes" branch when I am done and tested it locally.

**Comment by raystuttgart** [comment]
This is fixed now. :)
Will push to fixes tomorrow.

**Comment by raystuttgart** [comment]
Just as explaination:
For Ships only:
1. The logic now tries to spawn ships in a harbour city with access to Europes.
(Just in Case a FF should ever give Free Coastal Ships)
2. If that does not work it will spawn in Europe
(Using logic already existing)
