### ISSUE TITLE
Privateers

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#341]
It seems as if the AI doesn't like to heal/repair its privateers.
Is this another minor bug well known by the community?

**Comment by raystuttgart** [comment]
Hi 3tag, 

thanks for reporting.
are you playing / testing with 2.7.2 Beta 2 or is it another version?

And no, this was not known to me.
Actually Privateers/Pirates were coded to do so (at least in RaR I think it was still working fine).

If there are no enemies nearby it should try to directly heal if there is a suitable plot
If there are enemies nearby it should try to flee to a Native city or one of its nations cities and heal there. (Basically it flees to the closest city that is not hostile.)

Actually it should not behave differently than any other combat ship in that matter.
I also haven't seen anything that could explain the issue you describe.

**@team:**
The code to start analysing should be in CvUnitAI::AI_pirateMove()

**@devolution:**
You can probably give more insight to AI behaviour than me.
I also saw that you did some changes to CvUnitAI::AI_retreatToCity

**Comment by 3tag** [comment]
Hi raystuttgart.

I just took the 2.7.2 Beta 1 "Bughunting Version" (there is a Beta 2?), posted by nightinggale 3 days ago, and started a new game for fun. I only started reporting as a thanks for all the effort over the many years. My way to contribute a little bit ... it seems the game won't be given up ... 

I sighted the mentioned privateer once near the plots from where ships go to their homeports, with a lack of hitpoints. Lots of turn went by and I wondered why ther is a damaged privateer now near the colonies. I didn't compare the names, so maybe it was another one, but I think it was the same ship.

Do you know how I can label my postings here in github? The help description was not helpful to me.

**Comment by raystuttgart** [comment]
Hi 3tag,

no 2.7.2 Beta 1 is perfect.
That is the one that was published a few days ago.
Sorry for confusing you.

The team surely appreciates bug reports like yours.
We are going to check it out thoroughly.

The labelling is fine as well.
It does help greatly though if you write the version of the release your playing in the text.
Now we know of course.

Beta 2 is just the next (currently ongoing) version for the new bugfixes and improvments.
It is not published yet though because not much has been committed to it yet.
It is not really necessary for community to test it yet.

Thanks again.
We hope that you still enjoy playing the mod.

**Comment by ErikSandbraaten** [comment]
Hi,

I just had a look at the code for privateers: CvUnitAI::AI_pirateMove()

They do attempt to heal if damaged so that should work, but I agree that there are a number of other issues:

- AI ships often suffer damage from storms due to bad pathing so they probably appear to be somewhat damaged fairly often.  (I recently fixed this in the better AI branch though)
- They often attack other privateers which is a bit weird.
- They don't make any attempt at unloading their captured cargo. Neither when in Europe or in a friendly city.
- They seek refuge in natives villages without checking for nearby hostile units that can attack them from land while staying in the village.
- It would be better if they avoided players that have strong combat ships but they don't seem to be aware of that.

Most of the naval AI is overdue for an overhaul and it's on my list :)

**Comment by raystuttgart** [comment]
Hi,

so ok, they should try to heal (by seeking refuge) as I was thinking.

But yes, your other points are worth considering as well.
And of course your right, naval AI could need an overhaul.

- If the first point in the list (pathfinding leading to damage from storms) is already fixed in the AI branch that is awesome. 
- Privateers attacking other privateers (of other nations) is not necessarily an issue for me. They did that in reality as well.
- Privateers not unloading Cargo really is a major issue though and should be fixed. I really have no explanation currently why they should not.
- That they do not check for nearby hostiles when seeking refuge in an Native village is a bit strange. Maybe the easiest solution to implement would be to simply have them seek refuge in a city of their own nation.
- If they avoided players that hae strong combat ships they would most likely never attack Human Player in the end game anymore. They would only weaken other AI players. Maybe better leave it as it is. (Or exclude Human Players from that "strong navy" check of AI.)

**Comment by ErikSandbraaten** [comment]
I propose that privateers and pirates will ignore gather boats (whaling \ fishing). At the moment it's far too annoying to loose these ships all the time unless they are escorted by a combat ship.
This makes sense since I don't think that pirates are that fond of seafood anyway 😆 ,

**Comment by raystuttgart** [comment]
If we do that, we will most likely get bug reports "Privateer / Pirates are broken since they do not attack Fishing Boats / Whaling Boats".

Not everything that is a bit annoying or needs specific gameplay needs to be removed.

And I also disagree that Pirates would not attack Fishing Boats / Whaling Boats because they are easy prey and Pirates also were interested in "Whale Blubber" and "Food".

This change would simply make "High Sea Fishing / Whaling" easier and thus take away challenge.
But challenge is also a good thing.

**Comment by ErikSandbraaten** [comment]
Not sure why people would complain about their gather boats not being attacked. This  change would only apply to AI pirates. At the moment the lifetime of gather boats are so short that they are mostly pointless.

**Comment by ErikSandbraaten** [comment]
.. and in case you don't think that pirates are not effective enough, d be happy to teach the AI to prey more efficiently on these hapless ships 😁

**Comment by raystuttgart** [comment]
Well the livetime of Gather Boats is only short if you don't protect them. :)

**Comment by raystuttgart** [comment]
But yes, I am looking forward to your AI changes considering Pirates. 👍

**Comment by raystuttgart** [comment]
This is already outdated from 2020.
I think AI now heals its ships in Villages.
