### ISSUE TITLE
Goods storage 

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#357]
Dear All,

I noticed when playing the 2.7.2.beta1 version that the goods storage does not increase when the base camp is updated, see table below:

Base Camp +200 goods storage - Correct
Village Hall +200 goods storage - NOK
Town Hall +200 goods storage - NOK
City Hall +200 goods storage - NOK
Governor Palace +200 goods storage - NOK
Colonial Congress +200 goods storage - NOK

If this is already known or mentioned somewhere else, than please forgive me and close the topic.

Kind regards,

Chris
The Netherlands

**Comment by raystuttgart** [comment]
Well, I believe that this is simply a misunderstanding.
Because what you read from Pedia (or XML) might simply be confusing to you.

The Base Camp Upgrades do **NOT** increase the goods storage.
(They are also not intended to.)

But since they replace each other, the XML modifier needs to be there for all of them.
(And yes, it is also described that way in XML.)

So it is not a "**+** 200" for every Upgrade. It is simply a flat 200 that will **not be increased** by Base Camp Upgrades.
The Base Camp Buildings Upgrades will only make sure that the 200 Storage will always be given as a base.

Only the "Storage" Buildings (Storage House or its Upgrades) and the "Market" Buildings (and its Upgrades) will however increase the Storage Capacity step by step.

It has **never been different** in RaR (or TAC) either.

**Summary:**
It is **working as designed**.
But yes, Pedia might be misinterpreted.

**Comment by ErikSandbraaten** [comment]
I agree that the tool-tip is misleading. The pier building line has the same problem. 
Example: In the tool-tip it is claimed that building a dock will add +2 food on water plots. However, the dry-dock claims the same increase, it's just that these effects are not additive since buildings replace their predecessor so in this case, there is no net increase in food production from building the dry-dock.  This actually tripped me up as well when I started playing RaR. In other words, I do believe it's worth updating the tool-tip a bit. 
The BUG mod for BTS has a feature called "actual effects" that I think vastly improves the hoover text and I think we could allow ourselves to be inspired a bit by this :)

**Comment by raystuttgart** [comment]
This is not a "RaR" or "WTP" issue though.
It is the same for Vanilla and all other mods.

For RaR and WTP however this has more effects, because we have much more levels of Upgrades for every Special Building.

Well ok, but then we should post with a correct issue, e.g.:
"Clear Pedia Entries and Tool-Tips for non-additive Building Effects for Building Upgrades"

Basically it is mainly a problem of "Do I understand how Special Buildings and their Upgrade Levels work?"
(Knowing that Upgrade Levels of a Special Building do not add but replace the previous Upgrade Level and its effects.)

I have reopened the issue though.
So if somebody wants to and has a good idea how to improve this, I have absolutelty no objections.
