### ISSUE TITLE
Crash on mod load

### ISSUE THREAD

**Issue by Sirisma** [We-the-People-civ4col-mod/Mod#362]
Loading the vanilla game works 100% fine.
I boot up the vanilla game and go to the advanced tab, click "Load a Mod", select "We_the_people_2_7_2_beta_1", the game reopens momentarily and then CTDs before even getting to a splash screen, about the time it starts to initialize the engine.
Steam's launch options are blank. I've tried reinstalling both the game and mod numerous times since I first encountered this issue at the beginning of summer 2019, including a salt-the-earth of both folders and the registry. I've tried using both the '1 plot' and '2 plot' .dlls and neither appear to change anything. I'm at a loss as to what the problem is.

**Comment by Sirisma** [comment]
[init.log](https://github.com/We-the-People-civ4col-mod/Mod/files/4330258/init.log)

[PythonErr2.log](https://github.com/We-the-People-civ4col-mod/Mod/files/4330259/PythonErr2.log)

[xml.log](https://github.com/We-the-People-civ4col-mod/Mod/files/4330260/xml.log)

**Comment by raystuttgart** [comment]
Hi Sirisma,

first I need to tell, that I have no idea about specifics of Steam installation of Civ4Col.

So I need to ask some questions:

A) What **patch** is the Steam installation of Civ4Col?
Because with old CD versions you needed to have Patch 1.01.f for Mods.

B) Do **other Mods** work?
Because if they do, we might be closer to the resolution.

C) Please read **install_instructions.txt** that is included in the dowload of our mod.
Did you follow its instructions?

**Comment by raystuttgart** [comment]
@Sirisma just another question:
(Because I read that the install direction for mods in steam might cause problems)

Where did you put the mod?

Variant A:
C:\<Users>\<Username>\My Games\Colonization\MODS

Variant B:
C:\<Colonization_Install_Directory>\Mods\
(You might need to create the folder "Mods" there **manually**.)

If you are using Variant A) please create folder "Mods" in <Colonization_Install_Directory> move the mod folder there (by Drag&Drop) and try again if it works.
(Variant B) might work for you, but I cannot promise.)

**Comment by raystuttgart** [comment]
Just to make sure, that you did not mess upt the installation:

Please check the mod folder you WTP into.
You should find a folder called "/Assets".
Copy paste the complete folder path (including "/Assets" itself) here.

**Comment by Nightinggale** [comment]
Sadly the logs doesn't tell why it is crashing. We can only make guesses.

Try using the beta version of Colonization from steam. That one has better mod support.

> Variant B:
C:<Colonization_Install_Directory>\Mods
(You might need to create the folder "Mods" there manually.)

This would also improve compatibility because the log claims you are using variant A.

**Comment by Curt56** [comment]
It was doing that to me to. Other mods worked but not WTP. I reset my video options to default on my Nvidea card and it loads fine now. Not sure why but it worked immediately.

**Comment by raystuttgart** [comment]
Great.
I will close this ticke then.

**Comment by raystuttgart** [comment]
Oh, I just saw that Curt56 is not the original poster if the issue.
I will thus open it again until @Sirisma tells is if his issue is solved.

**Comment by Sirisma** [comment]
> A) What **patch** is the Steam installation of Civ4Col?
1.0.0.1 is the build number for both available versions.

> B) Do **other Mods** work?
TAC 2.03 works just fine for both available versions.

> C) Please read **install_instructions.txt** that is included in the dowload of our mod.
> Did you follow its instructions?
Yes or I wouldn't be here.

> Where did you put the mod?
> 
> Variant A:
> C:<Users><Username>\My Games\Colonization\MODS
> 
> Variant B:
> C:<Colonization_Install_Directory>\Mods
Tried both with both Steam versions with no progress.

> Copy paste the complete **folder path** (including "/Assets" itself) here.
> 
> For my installation it looks like this:
> C:\games\Colonization\Mods\We.The.People-2.7.2.beta.1\Assets
E:\Documents\My Games\Civilization IV Colonization\MODS\We_the_people_2_7_2_beta_1\Assets
My Documents has always been on my E:\ even before this issue so that should be 100% irrelevant.

**Comment by Sirisma** [comment]
I've tried disabling the Steam Overlay, Desktop Game Theatre, Steam Input, and Big Picture Mode and nothing has changed. The game loads until it says InitEngine, screen goes black, then CTD.

**Comment by Sirisma** [comment]
I restored default graphics settings as suggested and for whatever reason I have no issues now even after reboot. I can't for the life of me understand why that works because the .ini file was deleted like 15 times the past year but 

*shrugs violently*
