### ISSUE TITLE
Width of Help Message Boxes (Mouse Over)

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#366]
As reported [here](https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-12#post-15692933) in the forum by Mr.Zorg some Help Messages Boxes are quite narrow.
They might look better (especially in wide screen resolutions) if we widen them a bit.

It is not only perceivable in Russian.
Even in English texts the Help Messages Boxes are a bit narrow.

I already tried quickly to adjust **CvMainInterface.py**.
(But for the moment I have failed - need to take a bit more time.)

I was simply trying to change / increase this here:
HELPTEXT_AREA_MAX_WIDTH
or this here:
HELPTEXT_AREA_MIN_WIDTH

It did not work though.

I also found the place where e.g. the Help Text on normal Map Screen is generated.
I think it was this here:
```
# R&R, Robert Surcouf, No More Variables Hidden game option START
screen.setHelpTextArea( HELPTEXT_AREA_MAX_WIDTH, FontTypes.SMALL_FONT, HELTTEXT_AREA_X_MARGIN, yResolution - SADDLE_HEIGHT+HELPTEXT_AREA_Y_MARGIN, -0.1, False, "", True, False, CvUtil.FONT_LEFT_JUSTIFY, HELPTEXT_AREA_MIN_WIDTH )
```

I could perfectly move the Helptext area around the screen (change its position).
But I somehow was unable to change its width ...

Could one of you guys check as well?
I was never that good in programming Python considering pretty Screen layout.

All I need to know is the setting to change, then I can out an appropriate value by testing ingame.

**Comment by raystuttgart** [comment]
As @f1rpo explained over at Civfanatics, it seems to be an issue with the exe.
https://forums.civfanatics.com/threads/shrinking-resource-bubbles-by-modifying-the-exe.676727/#post-16280347

Thus this is probably not possible without pretty nasty hacks.

**Comment by f1rpo** [comment]
For the record, an alternative would be to reimplement the help text area through other widgets. The BUG mod for Civ4:BtS has indeed already done that: [/Screens/PLE.py#L2158](https://github.com/f1rpo/AdvCiv/blob/12f1a90dc03156213e1934428749b4c82367e985/Assets/Python/Screens/PLE.py#L2158)
(I'm guessing that this was implemented before the release of the GameCore DLL source, simply because the modders saw no way to add to the regular help text area at all.) Seems to work pretty well (screenshot below) – but quite a task to port that Col (not sure if CyGInterfaceScreen has the same interface in Col either); even in BtS, just having CvDLLWidgetData redirect help text to that new implementation is more work than I'm willing to put into it.
![PLE-info-pane](https://user-images.githubusercontent.com/27625493/170780664-dde12e3e-6083-442e-8a5b-29286e9225cd.jpg)

**Comment by raystuttgart** [comment]
Let us close this, the effort for this seems outrageous.
