### ISSUE TITLE
Defensive Pact Error

### ISSUE THREAD

**Issue by Curt56** [We-the-People-civ4col-mod/Mod#370]
I start a new game and go into world builder, make some adjustments and save it as a world builder save.

I start a new game (scenario) and load my world builder scenario/save. I cannot see the option to form a defensive pact with natives while I am in game. It never shows up.

Any reason for this

**Comment by raystuttgart** [comment]
Actually that was programmed purposely by **devolution**.

You need to be in **War of Independence** before a Defensive Pact with Natives is allowed.
(However I am not sure if a Defensive Pact is then still possible, because AI is pretty cautious with Defensive Pacts once you have a War going.)

**Reason:**
There was an "exploit" that in a Defensive Pact with Natives they would give you all their goods for free (when Trading with Wagon Trains.)
Devolution wanted to get rid of that because Colonial AIs would never use it (or actually mostly not even get to Defensive Pacts with Natives).

**Comment by Curt56** [comment]
Okay, so that only applies when I have altered the game/map in world builder? If i start a regular game or scenario, the defensive pact option is available.

**Comment by raystuttgart** [comment]
ah ok, then it is a different issue you are talking about.

Some game options are stored in scenario maps and then cannot be if you start by "Play Scenario".
(This also affects "Defensive Pacts".)

But if you start by "Custom Scenario" you can always overwrite them.
So it really depends on **how you start the game**.

**_Recommendation:_** 
Always start by **"Custom Scenario"** (using predefined maps) or **"Custom Game"** (generating new maps by scripts) and you will be able to set all the options to your preference.

**Comment by ErikSandbraaten** [comment]
Note that you can restore the original defensive pact mechanic by changing the 1 to 0 in Assets/XML/GlobalDefinesAlt.xml

<Define>
<DefineName>PERMANENT_ALLIANCE_REQUIRES_REVOLUTION</DefineName>
<iDefineIntVal>1</iDefineIntVal>
</Define>
