### ISSUE TITLE
Negative Amount of Horses 

### ISSUE THREAD

**Issue by stepik-tug** [We-the-People-civ4col-mod/Mod#383]
Hello, so i got a message that indians stole 75 horses but that i have no proof that they did it or that i say to them either you give them back or WAR and the third option examine setllement , as i was waiting to get 150+ horses this turn and load up a galeon full of horses to africa i was kinda sad i tought maybe i can fuck with the system and the horses are still in the setlement so i can load them up and not go to war with the indians . And it worked kinda sort of  , i then pressed on i dont have proof that thez did it and they stole 75 horses but as i did not have 75 horses available anymore it substracted of the current amount and i got -57 Horses..
![image](https://user-images.githubusercontent.com/57330756/94377492-83ff6200-0122-11eb-9354-6ce587a72ab0.png)

**Comment by raystuttgart** [comment]
So you are trying to "purposely f*** the system" and wonder if strange things happen. :)
Well yes, the Python Event System can be tricked currently - if you interact in between Event Pop-Up and Decision.

**Comment by stepik-tug** [comment]
> So you are trying to "purposely f*** the system" and wonder if strange things happen. :)
Firstly i do not wonder about it at all, im reporting a in game behavior which i find buggy i thought this place is for exactly this type of communication.
This is a bug , bugs are still considered issues i assume ?
Do i have to make a list of reasons why bugs in games are not desirable or do you want me to report bugs when i stumble upon them ? 

I followed game mechanics and came into a situation which i regard that it is not supposed to happen , i report it as a bug. If you have a problem with my wording of "fuck with the system" or in other words :  using game paths available , clicking "examine Settlement" in a dialog which randomly pops up and using the examine settlement view options i have available to prevent this random event from interfering with my game plan , if you still find my wording not satisfactory enough i can try to word it to your satisfaction.


> Well yes, the Python Event System can be tricked currently - if you interact in between Event Pop-Up and Decision.
This can not only be considered a trick in the python Event system but in the Event in generall , if you dont want people to "examine the city" and  do stuff you dont put that option in the event.

**Comment by raystuttgart** [comment]
Sorry, but there is no reason for me to fix things like that.
The system simply checks conditions before an Event is triggered.

And yes, it is possible that in between the triggering of the Event and the decision you mess with the original conditions.
Thus you of course also create strange results.

There are many good reasons where you **sometimes really want to check your City** before making a decision.
Preventing there to have the player change any of the aspects of the cities in "Check City Mode" is not even intended, because it is also used by other features e.g. the "Build Message"

I do not care if people "purposely f*** the system" and thus destroy their own fun in the game.
If that is however fun and they want to do it, go ahead. Fine for me as well.

**Summary:**
Yes you found a potential bug that can be exploited.
It can not happen accidently though but only if you do it on purpose.

I **suggest to close** this unless somebody is motivated to change "Check City Mod".
(For me it is way to much wasted effort to check the specific situations that may allow changes in the cities and others that may not allow it.)

If somebody however feels motivated to further analyze and fix it, go ahead.
I really do not mind if this is reopened and fixed. - Simply believe it wil never be the case.
