### ISSUE TITLE
Sloop wakes up from sleep for no known reason

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#408]
Issue reported on the forum, complete with savegame.
[link](https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-7#post-15992872)

**Comment by ErikSandbraaten** [comment]
I suspect that it's simply an animal that passes by in the fog...

**Comment by ErikSandbraaten** [comment]
Regardless, we may consider either outputting a message stating the reason for the awakening or just filtering out these events so they don't cause the unit to unnecessarily wake up.

**Comment by ErikSandbraaten** [comment]
The save is from Large_Rivers :(

**Comment by raystuttgart** [comment]
This most likely is no bug.
There was probably just an enemy somwhere.
(e.g. Privateer or Wild Animal)

**Comment by ErikSandbraaten** [comment]
Yep
But reporting exactly what caused the wakeup may stop complaints in the future ? Filtering out animals or other weak enemies that pose no threat may also be considered.

**Comment by raystuttgart** [comment]
Actually I really do not like that "Wild Animals in Water" have kind of become a joke ...
Check the current balancing of Ships vs. "Wild Animals in Water".

Ships: 
iCombat: 20+

Wild Animals in Water:
iCombat: 2 to 4

I rest all further comments on this.

The problem starts with "Wild Animals in Water being no threat". (Current balancing)
Not that ships wake up. (Because that would make sense with proper balancing.)

**Comment by MrZorG33** [comment]
I will repeat here: on the cage with the Sloop another ship was also "sleeping" and it did not wake up.
so we need to check why he did it. about once every six moves.

**Comment by raystuttgart** [comment]
@MrZorG33 

Please check the visibility range of the 2 Units (Sloop and other Ship).
Are they the same?

And are you really talking about **Sleep**? (Keyboard-Shortcut: F)
Or are you talking about **Sentry**? (Keyboard-Shortcut: S)

**Comment by MrZorG33** [comment]
Keyboard-Shortcut: F
The visibility of the Sloop and the Frigate is not the same (Sloop +1, that is, 2 cells). but I have positioned the other ships so that they can see beyond the Sloop. he wakes up anyway.
I can't attach a save game here. attached it to my forum post <a href="https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-7#post-15992872">Release candidate 2.8.2.0 - testers needed</a> (before unsleep.ColonizationSave).

![image](https://user-images.githubusercontent.com/61798883/103922966-8e6bc780-5125-11eb-8bd0-3c5d5450e564.png)

**Comment by ErikSandbraaten** [comment]
Had a look in the debugger and these are my findings:

The sloop does wake up every time a new "load" (20 units of whale blubber) is harvested by the gather boat every turn so the animals/pirates are not to blame this time :/
