### ISSUE TITLE
Learning from natives takes 1 turn

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#411]
Forum report with savegame
[link](https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-7#post-15991079)

**Comment by raystuttgart** [comment]
@Nightinggale 
This is no bug, this is **actually normal and possible**.
We know about that possibility since years.
(It does not happen with every tribe, every Civ, every profession.)

1. It depends on the Native Tribes (some have bonusses)
2. It depends on the Colonial Nation (some have bonusses as well)
3. It depends on the Profession to learn (some are incredibly easy and fast to learn)

This is basically **just a balancing complaint** and could be solved in XML if properly discussed.
(Not everything that player do not like is a bug.)

Summary:
I will close because it is not an issue.
Just something a player noticed, did not like or did not understand.
