### ISSUE TITLE
bottom interface overlaps the unit icon

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#437]
the unit icon outside the main screen is overlapped by the bottom bar of the interface. the problem came from 2.8.x

![иконка юнита скрывается за интерфейсом](https://user-images.githubusercontent.com/61798883/115996103-a557fc00-a5e6-11eb-9c33-9d52102fd9c8.jpg)

**Comment by raystuttgart** [comment]
This is definitelynot reproducable in "river merge".
There is not even any logical explanation for this ...
Nothing we did in "Large Rivers" or "river merge"would even come close to causing that.

**Comment by MrZorG33** [comment]
I have this error in merge_rivers. here she moved from 2.8.2.4

**Comment by raystuttgart** [comment]
Ah ok, you talk about the "Icon" about **"where the Unit is"**. 
(So you can click to jump to the Unit.)

By telling me "it is a bug", I was **totally confused** and thus could not reproduce it.
I was **searching for an "actually critical bug"** and not for a minor "interface annyoance".

**Summary:**
Yes, it is a bug. But it is also not critical. (Since only small UI issue.)
We should try to fix it but it will not block the release.

**Comment by MrZorG33** [comment]
in my opinion it is highly undesirable to have this "interface annyoance" in the new release.

**Comment by raystuttgart** [comment]
It is undesirable, but it is not enough to **"block the release"**.
If bugs like this will block our releases, we will never ever release again.

If we can fix it until next week, great.
Othewise we will release anyways and fix later.

**Comment by raystuttgart** [comment]
Since this was obviously somehow cause in 2.8.x I sadly currently have no starting point for analysis.
I was sinmply not invovled in 2.8.x and in "Large Rivers" it still works perfectly fine.

I simply do not know **where** I could **start searching** for the **cause** of it.
(**CvMainInterface.py** and other places I checked are absolutely fine or even identical so the issue must have been cause somewehere else.)

And **debugging** which Nightinggale could do **will not help us either**, because DLL does not trigger a bug in such cases.

The only thing that may help is to find some change in 2.8.x that may potentially have cause it and then analyze that change ...
I never heard however that 2.8.x was changing User Interface aspects ...

**Comment by Nightinggale** [comment]
I will run though old revisions to try to pinpoint when this starts. That would be our only lead on this issue at the moment. It's however not on top of my todo list.

**Comment by MrZorG33** [comment]
I found on the forum - started in 2.8.2.3

**Comment by raystuttgart** [comment]
Found what?
Please send a link to the post.

**Comment by MrZorG33** [comment]
https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-12#post-16062099

**Comment by raystuttgart** [comment]
That makes it much easier to figure out what was changed. :)
I would have been searching myself to death - because I was never involved in 2.8.x at all.

**Comment by raystuttgart** [comment]
Thanks, that was really beyond my skills to analyze and fix.

**Comment by raystuttgart** [comment]
Fix confirmed, just tested to be sure.
