### ISSUE TITLE
visible ocean tiles in the fog of war

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#446]
today I downloaded large_merge with the latest updates. I started playing a new game. again visible tiles of the ocean in the fog of war. 

![опять видимые плитки в океане01](https://user-images.githubusercontent.com/61798883/116795157-920fc980-aadb-11eb-96a6-1c87dde8c79a.jpg)

but! after a while they disappear.

![image](https://user-images.githubusercontent.com/61798883/116795356-11ea6380-aadd-11eb-85d3-785303828a26.png)

**Comment by Nightinggale** [comment]
Are you saying this happened without saving and then loading?

I did change the savegame format for this by not saving this, but rather calculate from scratch on load. This way it should always be correct on load, even in hard to solve situations like somebody changing xml data.

**Comment by MrZorG33** [comment]
I started a new game. in the course of the game, I did save the game and load the saved game. at what point the visible tiles appeared, I cannot yet say. I'll watch.

**Comment by MrZorG33** [comment]
Last turn my Caravel sailed here. On the next turn, there are still visible ocean tiles.

![image](https://user-images.githubusercontent.com/61798883/116795904-f08b7680-aae0-11eb-8c6e-7018c194cdd0.png)

after loading a saved game they disappear.

**Comment by Nightinggale** [comment]
Ok, it didn't get corrupted while loading. However in theory it could meaning it wasn't wrong to recalculate on load. Also it does fix broken games now.

The problem must be due to moving features (weather).

**Comment by raystuttgart** [comment]
But if it is due to "moving features", we would have this bug since 2011.
And would it then not be basically the same with "moving enemies"?

Just asking ...
(I have no idea about this feature.)

**Comment by Nightinggale** [comment]
I did some testing. If you click end turn and a cloud shows up, the plots you can see on the other side of the cloud are still visible. Because the ship can't see them after the cloud has appeared, moving the ship afterwards will not clear the visibility count and the plots will remember that a unit can still see them.

I did find code a while ago, which would trigger on negative visibility count and then set it to 0. I commented that it feels like hiding a bug rather than fixing it. Now I think I'm on to the bug it is hiding.

I have a strong indication that the ship needs to have increased visibility range for this to trigger meaning it only happens with ships with the right promotions.
