### ISSUE TITLE
It is not possible to sell food from the customs house

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#45]

**Comment by Nightinggale** [comment]
Related to #44. I vote for the quick solution for 2.7.1 and start the loop in popup creation with 3 instead of 0, in which case the first 3 yields, which are currently disabled in the GUI read code will be removed from the GUI as well.

We can make a nice solution for this later, but we should priorities getting the other (possibly crashing) bugfixes out in a stable release before we spend too much time considering a permanent solution for this. We can do that post 2.7.1.

For long term solutions, we should consider the balance of which yields to allow sales of. We can use an InfoArray as explained in #128, in which case we can make a setup where included yields are defined in xml without having the xml checking overhead at runtime and that's just one option out of many.
