### ISSUE TITLE
Some bonus resource placement bug

### ISSUE THREAD

**Issue by Tsubasanut** [We-the-People-civ4col-mod/Mod#451]
I have couple of issues with new bonus resources.

1. in  CIV4BonusInfos.xml  **Turkey** branch is wrong - need to empty **TerrainBooleans** tag. Otherwise Turkey will give bonuses to food even if there is no forest on the tile. It contradict Colopedia and I agree with Colopedia logic here.

2. A specific issue with RAR Americas Gigantic. Melons are placed on Savannah and Coconut Trees are on marsh. So no bonuses for them. Also all turkey tiles are open terrain, should be on forest tiles.

**Comment by raystuttgart** [comment]
Actually Turkey giving Food without Forrest was intended in my balancing - because there were complaints that it got "unusable" once a City is foundend on top of it that removes the Terrain Feature.
But thanks for pointing me out that Colopedia Text says different, will check that.

RaR Americas Gigantic is a "Scenario Map" (fixed Bonus Ressources, fixed ...) and totally outdated.
And it is the absolutely only "Scenario Map that has everything fixed.

I am totally fed up with maintaining it and will not touch it anymore other than "adding Large Rivers".
With every change it causes huge maintaining efforts ...

All other Maps simply randomize Bonus Ressources, Terrains Features, ... as definied in XML.

**Comment by raystuttgart** [comment]
Edit: 

1. Turkey Colopedia Corrected.
2. RAR Americas Gigantic ... I will see ... (Plot Coordinates would help)

**Comment by Tsubasanut** [comment]
Thanks you, I will provide exact coordinates when I get back to game in about 7-8 hours from now.
I can also fix the map if you like. 
I can see value in historic map setting, but it's a PITA to support it for sure.

**Comment by raystuttgart** [comment]
Which version / release do you play?

There is little point in touching the map yourself.
(I need to work on it for adding "Large River" anyway.)

The only thing that would really help is Map coordinates (X, Y coordinates).
You can get those by 

1. Activating modders cheat (CivilizationIV.ini - if cheats are not yet activated, please make yourself a backup before changing)
2. Shift + Mouse Over (the plot)

**Comment by Tsubasanut** [comment]
I'm playing 2.8.2.4 release, so it is not internal. I'm ok with not touching map ^_^

Here are coordinates to bugged tiles:
Melon - (67, 138), (93,128). Savannah, should be march
Coconuts - (74,134), (103, 84). Marsh, should be savannah

**Comment by raystuttgart** [comment]
I have now taken care of all the problematic bonus ressources I found.
Also checked your ones. Thanks for telling.

Also directly updated the Map for "Large Rivers" (our new feature)
