### ISSUE TITLE
warehouse volume increases incorrectly

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#455]
many complain about the insufficient amount of warehouses in the game. I don't know why, but only today I noticed that all buildings (warehouses, markets, base camp and higher level buildings) that increase the volume of the main warehouse give a smaller increase than what is written in the description.

![рынок неправильно добавил места01](https://user-images.githubusercontent.com/61798883/117550971-e3740780-b04b-11eb-90b4-b47abe947f1e.jpg)
![неправильный объем склада02](https://user-images.githubusercontent.com/61798883/117555824-22658580-b06b-11eb-9a4c-7e00b87ca0d3.jpg)
![склад неправильно добавил места01](https://user-images.githubusercontent.com/61798883/117552093-26d17480-b052-11eb-941e-a035236a06ee.jpg)
![склад неправильно добавил места02](https://user-images.githubusercontent.com/61798883/117552097-289b3800-b052-11eb-887d-6edc6ff5f515.jpg)

Base camp +200
Village Hall +200
Town Hall +200
City Hall +200
Government Palace +200

total = 1000

Storage house +900
Wharehouse +1500
Wharehouse expansion +2000
 total = 4400

total in colonies without access to the ocean, the volume of the warehouse should be = 1000+4400= 5400

![неправильный объем склада05](https://user-images.githubusercontent.com/61798883/117555683-fc8bb100-b069-11eb-8889-ed5fb32d9601.jpg)

in cities on the coast, you can build Customs +2900
total in colonies on the coast, the volume of the warehouse should be = 5400+2900= 8300

in addition, in our capital, we can build a Congress Hall (+200) , Central Customs (+3300) and Statue of Governor (+300)
total in the capital, the volume of the warehouse should be = 1000+4400+2900+200+3300+300 = 12100

we need to find the error.

**Comment by raystuttgart** [comment]
You are interpreting this wrong. :)

Village Hall does not add +200 to Base Camp, since it **replaces** Base Camp.
There is no "increase" and Colopedia also does not speak about "incrase".

Village Hall simply gives the same 200 Storage as Base Camp.

Also Storage House (900) is replaced by Warehouse (1500).
It never says "+1500", it just says "1500".

There is no bug, this is just misreading or misunderstanding the numbers.
Everything is perfectly as XML says and it is all that the Picures and Colopedia says.

**Summary:**
Working as designed.
(No bug, nothing to worry about.)

**Comment by raystuttgart** [comment]
I do not know how often I have clarified this already since TAC, but it keeps being asked again and again and again ...
Often feel like a Hamster in a threadmill ... :)

**Comment by MrZorG33** [comment]
Thanks again for the detailed clarification.
"_Often feel like a Hamster in a threadmill ... :)_" we all are sometimes the same hamsters :D

**Comment by raystuttgart** [comment]
Sorry, but I sometimes get annoyed, when I read "bugs" about things that have always been working that way.
And for me the reasons why are absolutely obvious. So it feels like "personal taste changes" hidden as bug reports.

I also get annoyed if we discuss other **personal taste changes** again and again even though the result of the discussion is so obvious to me, because I had that discussion **already 10 times** in the past and know how it always ended ...

It is also frustrating for me to be **the last "dinosaur"** of this community that fights against **extinction** of all the old knowledge and experience ...
Where are **all the other old modders** gone that could also explain and share these things?

So again, sorry if I sometimes lack patience ...
