### ISSUE TITLE
Bug report - "Negative cargo stored error"

### ISSUE THREAD

**Issue by LGMailhos** [We-the-People-civ4col-mod/Mod#472]
![Civ4-WtP_cropped_debug](https://user-images.githubusercontent.com/3653585/121765737-917b4180-cb23-11eb-8e7e-8fb52514ac14.png)

A save game previous to the pop up related to this bug, and a couple saves after the pop up are included as attachement.  

The bug seems to disapear on about 10 to 15 turns, without any noticeable ill effect.

[Civ4-Colonization-WtP_debug.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6641691/Civ4-Colonization-WtP_debug.zip)

**Comment by raystuttgart** [comment]
**Which version?**
(That is the most important information we need.)

- **Published** "2.9"?
- **Current internal** "develop"? (going to be 3.0)

If this bug was seen in **published release 2.9** then we probalby already fixed it in upcoming 3.0.
If the bug was seen in **current internal** "develop", the we seem to have another issue like that.

@Nightinggale 
Could you please take a look?

**Comment by Nightinggale** [comment]
This turned out to be a new way to get negative storage. This time it was triggered by trading with natives.

The savegame is interesting. It triggers some assert failures due to AI attacking an AI city (settlement or colony), which results in states, which shouldn't occur (fleeing unit not on expected plot and such). This is pending further investigation.
