### ISSUE TITLE
Boarding crews

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#473]
Hi Guys,

I trust you are all well and enjoying the beautiful summer weather. I have an idea, did not know where to drop it properly so please forgive me if I placed it incorrectly...

During war time with other colonial powers, I find it too random if I can capture ships or not. In other words, I would like it to become (more) predictable. By doing so, I have a good alternative to expand my fleet of trade and warships at minimal cost.

May I propose to develop a new unit - a boarding crew! A few details to consider:
- A (military) unit, that can be purchased only in Port Royal...? Would make the use of that port more attractive... Now, I hardly visit it...
- A unit that cannot be trained, only purchased...?
- Purchase price:  starting at 2000 gold coins, and increasing like the other units when purchasing them in Europe...?
- A skill that can be assigned only to the petty criminal...? Makes it more attractive to "buy" these units when the King offers them, and makes the petty criminal more useful... (this option actually has my preference, as it makes the player dependable on having petty criminal units...)
- Proposed requirements: 25x rope and 25x tools to represent the grappling hooks needed to board a ship, and 25x blades and 25x guns to represent the fire power required to overtake the ship
- The captured ship keeps all the upgrades (not sure if that is the same now...)
- The unit "disappears" once the boarded ship is captured, and acts as the new crew compensating for all the lives lost during the battle... :-)
- The AI can use it too, meaning escorting convoys becomes even more of a necessity...?
- And to compensate for the above, when a ship has one or more military units onboard the boarding crew is unsuccessful and will die without capturing the ship

Just a thought, I hope you can appreciate the suggestion. Looking forward to hearing your thoughts!

Chris
The Netherlands

**Comment by raystuttgart** [comment]
Puh, quite an extreme effort you suggest ...

Mostly because your concept "Boarding Crew" is extremely complex.
"Boarding Crew" would thus also be impossible to teach to AI ...

It sounds immersive, but from my perspective it is still not good design.
It is too complex, too much effort, too dangerous to get expoited e.g. during WOI ...

Other concepts would be much simpler and easier to teach to AI.
e.g. to simply have a simple Promotion "Boarding Crew" - with some DLL logic behind that increases chances.

----

And yes, stuff like that should only be suggested / discussed in the Forum.

**Comment by vissercsp** [comment]
OK - Thanks for the quick reply, please close this subject and pursue the idea of a "Boarding Crew" promotion
