### ISSUE TITLE
gost ship of CTDs

### ISSUE THREAD

**Issue by XSamatan** [We-the-People-civ4col-mod/Mod#475]
Game is crashing after ending the turn. I probably narrowed it down to a Swedish Caravel SE of human player colony as deleting this ship via WB crashes the game.

I changed a lot of values in /xml so this folder is also attached.

Would be great if you guys can take a look at the situation, wanted to start a week-long RP-WtP-session and it took quite some time to set up the map :)

Regards
XSamatan
[Caravel crash.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6650138/Caravel.crash.zip)

**Comment by XSamatan** [comment]
version is 2.9 (with the mentioned xml edits)

**Comment by Nightinggale** [comment]
It took a bit of work, but now I can load it with the development version (essentially I merged your xml files with all our xml changes since last release).

Apparently weird stuff is going on right as I load the game where there are more selection groups than units. Any idea how that could have happened?

**Comment by Nightinggale** [comment]
I found the crash. The game loops through all units on a plot and the list contains a NULL unit. It crashes when it tries to read the team of that unit, though the real bug is that it's there in the first place.

Before reaching this, multiple asserts triggered, like checkPopulation and the cache for how many units and unit power is in an area. Apparently it believe there are negative amount of units somewhere.

I have never seen anything like this before. This savegame is seriously messed up. Did you change xml and then load a savegame or did you do the xml edits before starting this game?

**Comment by XSamatan** [comment]
Thanks for looking it up!

It's a modified 2.9 version, since I have a lot of differences balance-wise I used winmerge to get my edit up to the new release. The map is also changed on multiple occasions (European players, native settlements) - maybe there lies the error. I re-start the game from the initial save file and see if it is any better.

**Comment by XSamatan** [comment]
> Apparently weird stuff is going on right as I load the game where there are more selection groups than units. Any idea how that could have happened?

Since I have no idea what selection groups in Civ4Col are I can't answer this question.
units.xml is changed in a way that affects immigration and prices, but no other changes to units.
I use CTRL+NUMBER to mark specific units if that would be a selection group

**Comment by Nightinggale** [comment]
a selection group is a group of units, which you select and move around together.

**Comment by XSamatan** [comment]
Does the AI use this feature?

Tugulawina (sp?) and the Inuit nation happened to spawn in tropical territory, I moved them to a more snowy setting, deleting units and settlements in the original area in the process. I also removed the AI's starting ships and manually planted settlers in locations I want them to occupy.

**Comment by Nightinggale** [comment]
Yes the AI makes use of SelectionGroups. A number of activities we normally view as unit activities are actually selection group activities, which then applies to all units in the group. A unit can't exist on the map without being part of a group, even if that group consist of just one unit.

**Comment by XSamatan** [comment]
Well, I deleted a **lot** of units on the map, created new ones, planted cities, moved players around...much space for error :D

I'll upload my initial save file, would you be able to take a look at that if it shows the same behaviour? 
[wb-initial 2+0.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6650527/wb-initial.2%2B0.zip)
