### ISSUE TITLE
Save file upgrader

### ISSUE THREAD

**Issue by wyphan** [We-the-People-civ4col-mod/Mod#476]
I just installed 2.9 and tried loading a save file from 2.8.2.4, and got a CTD, even though I already cleared my cache. Is there any way I can upgrade my save file to be compatible with 2.9?

**Comment by Nightinggale** [comment]
Remove UNIT_EXPERT_SETTLER from Assets\XML\Units\CIV4UnitInfos.xml
That will require you to remove/change it from all the places it is referred to.

The problem is that the game engine does something to units and since we don't have the source code for it, it's an open question what it is. Long story short: adding a unit to xml breaks savegames. I want to fix this, but it's kind of hard considering I don't know what it is doing.

**Comment by Nightinggale** [comment]
Added #480 with the task of how to (hopefully) fix this problem. It seems that savegames already broken by this are near impossible to save though. There is no remedy other than not updating until you are ready to start a new game.
