### ISSUE TITLE
wild animals spawn on the player's territory

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#527]
I had never played with wild animals, but then I decided to test the card that Rei was talking about. the problem is in the title.
![image](https://user-images.githubusercontent.com/61798883/148588576-ffcb7ae3-05ec-4b49-8d53-c68110cdd1e8.png)

**Comment by raystuttgart** [comment]
Yes that is possible but it is **not a bug** in my opinion. (This is the behaviour since the feature exists.)
It is even realistic that Animals also get "born" in Human controled Terain.

Once they were spawned there they are **simply moved outside** player territory again **anyways**.
It would cost way **too much performance** to always check if they are in a City Radius or such before spawning.
