### ISSUE TITLE
unit is not visible behind terrain textures

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#543]
sometimes units are hidden behind terrain textures. for example, a native trader.
this usually happens when a scout (or any other unit) "picks up" a goodie.
![image](https://user-images.githubusercontent.com/61798883/151696833-b1fd403f-294b-4ceb-bb2d-d6b06cc76c1a.png)

does not require an immediate fix.
as soon as the unit starts moving, everything returns to normal.

**Comment by raystuttgart** [comment]
There is no way to really fix this.
This happens in the graphics engine if it is too much under stress.
Nothig we could do in the DLL would affect it in any way.

**Comment by MrZorG33** [comment]
then let's leave this ticket open for now. perhaps in the future there will be an opportunity. let it be "in sight".

**Comment by Nightinggale** [comment]
Would it be possible to make a savegame where this happens consistently? Maybe it's related to the function, which decides which unit to draw on the map. That one is in the DLL.

**Comment by MrZorG33** [comment]
hmm.. I'll try to make such a save.
by the way. approximately the same bug (in my opinion) is observed on the screen of the colony. when loading / unloading ships or wagons, the image of a building under construction may disappear and reappear. You can see this in any of your games. I don't think it can depend on the screen resolution at which I play. though...

**Comment by raystuttgart** [comment]
As I said guys, this is related to the graphic card being under stress.
(Most often something like this is seen in WorldBuilder when massively editing the map.)

It is simply an "update" problem.
Once you load or switch screens, the problem is solved.
(e.g. going to Europe Scree or City Screen)

e.g. 
- Bonus Ressource not shown (hidden by Terrain when Terrain is placed)
- Building not shown (hidden by Unit when unloaded from Ship)
- City not shown (hidden by Hill, when Hill is placed)
- ...

It is simply a **performance issue**. The graphics engine is not updating automatically.
And since "Plains" add so many new graphics, it may have been a bit increased.

I have observed dozen other cases like that.
(Any kind of graphical update may be affected.)

**Comment by MrZorG33** [comment]
sorry Ray, but I can consider my card to be quite powerful at present (1660ti ), however there is a problem. I will check your statements about switching screens (the main thing is not to forget about it))))

**Comment by raystuttgart** [comment]
**@MrZorG33** 
It may also be related to the game itself running only one 1 core. (Until @ErikSandbraaten made it multi-threading-capable)
It is definitely **not** a problem of the game logic (DLL) it is related to the graphics.

As I said, it happens regularly.
(Especially in Worldbuilder.)

And it is not related to any specific graphic to my experience.
(You can have it in lots of scenarios and lots of different graphics.)

There is really almost nothing we can do about it.
It happens inside the graphics engine and we can not touch it.

**Comment by ErikSandbraaten** [comment]
Try experimenting with the Debug Menu (cheat mode) to see if you refresh/update the rendering somehow:
![image](https://user-images.githubusercontent.com/32330976/152577914-9d7eb28b-2c58-4e94-acd5-2ee5af06e4b7.png)

I suppose it could something simple like failing to update one of the engine rendering bits or something like that

**Comment by MrZorG33** [comment]
@ErikSandbraaten I tried the first four bookmarks - nothing helped. the unit is hidden behind the forest.
switching to the europe/africa or colony screen didn't change anything either.
![image](https://user-images.githubusercontent.com/61798883/152648363-2b64c1f7-7e79-495a-a6dc-861e5e4b9208.png)

**Comment by raystuttgart** [comment]
But if you save and load it is visibly normally again, right?

**Comment by MrZorG33** [comment]
no.
I observed units in different types of forest. units are least visible in the coniferous forest (depending on the composition of the group. single units are almost always hidden. double / triple units, as a rule, are slightly visible).
![image](https://user-images.githubusercontent.com/61798883/152650931-be54cd29-3ed8-43af-851a-2d28911bc716.png)
![image](https://user-images.githubusercontent.com/61798883/152651416-0a81f4f8-f4d8-4bbd-8f46-3d2988bd9c10.png)

perhaps the scaling that is now applied also plays a role. so, most likely, this is not a bug, but a display feature.

**Comment by raystuttgart** [comment]
what happens if you zoom in and out - it might be infact simply a matter of scaling.
(Also this effect may look different in different resolutions.)

**Comment by ErikSandbraaten** [comment]
Could be a Z-depth / clipping issue. Maybe the trees are simply taller than the low-ish treasure wagon :P

**Comment by MrZorG33** [comment]
By the way, yes. coniferous trees are definitely taller than deciduous trees.

**Comment by raystuttgart** [comment]
Ok, I will check and make them a bit smaller. :)

**Comment by raystuttgart** [comment]
I made it smaller but that is not the problem.

The problem is this here (Clipping) and I do not know yet how to fix it.
(I would need some advice from a more experienced graphical modder for this.)

I will ask around once I find time ...
(It is a pitty **Schmiddie** is not around anymore.)
![Civ4ScreenShot0010](https://user-images.githubusercontent.com/59391125/152658125-d0aa9a16-ffab-4614-b485-304df2baf437.JPG)

**Comment by ErikSandbraaten** [comment]
I suppose we should try to solicit some advice on the civfanatics forum

**Comment by raystuttgart** [comment]
I already asked for help after taking a look at the files.
(First tried to fix it myself but could not find anything in NIF or XML.)

**Comment by raystuttgart** [comment]
@Schmiddie1979 Could you take a look at the Corniferous Forest?
(I added it during my work in Plains - it was split from the other Forest.)

There is kind of a problem with clipping and Units in it get hidden / are badly visible.
Maybe it is easy for you to fix and repair the clipping?

**Comment by Schmiddie1979** [comment]
I have checked that. There seems to be no difference between this new feature and other trees/features. I have checked the graphic file itself and XML entries. Units will be hidden by all different trees. I assume it has in fact something to do with the new scaling of the units. I would say - take it as a challenge that units might be hidden on the map due to the features on the map.
