### ISSUE TITLE
farm in the tundra

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#576]
_randomly generated map_
my pioneer has the opportunity to build a farm in the tundra.
![image](https://user-images.githubusercontent.com/61798883/155859238-9b3a6e1e-5ddc-4f0a-a678-96b58aa2d945.png)

I admit that this is possible because of lingonberries. but I think it's wrong.
especially since lingonberries give +1 to food, but this tile gives 3 food. although the tundra slab, by itself, should not provide food at all.

**Comment by raystuttgart** [comment]
Actually that was intended. But well as I said, modding is always a matter of personal taste.
I intended to give Tundra Cities a bit more chance to produce food and sustain population.

---

Also the calculation is correct:
(It behaves like every other Food Bonus Resource.)

+1 by "lingonberries"
+1 by Farm itself
+1 by Farm Bonus from "lingonberries"

---

Some Improvement needs to give a Food Bonus on "lingonberries".
Otherwise the complete Bonus Ressource makes no sense.

---

What you guys could do in XML though is to e.g.:

A) Remove "lingonberries" from Tundra, so it stays only on Taiga.
B) switch "Farm" with "Collectors Post" on Lingonberries.

Both of these would remove the problem of "Farms on Tundra".

---

It is up to you what you want to do with it. 👍 
As I said, feel free to change whatever I have implemented.

**Comment by raystuttgart** [comment]
**By the way guys:**

I highly suggest to **not** discuss every small balancing detail like this.
You will go crazy making screenshots and waiting for feedback.

Somebody needs to be given the responsibility for the balancing.
Tiny changes like this are really not worth to go through an approval process.

Just implement it without wasting time. 👍 
(And only if somebody complains discuss.)

**Comment by MrZorG33** [comment]
well, I admit the possibility of "some food in the tundra". but the farm is not built yet and the tile already gives 3 food. grassland, prairies give the same amount of food.

this is not a complaint, but just an attempt to correct the balance.
I would allow 1 food on the tundra tile, but no more.

**Comment by raystuttgart** [comment]
Tundra gives that amount of food only with the Bonus-Resource.
But as I said implement whatever you guys agree to implement. 👍

**Comment by devolution79** [comment]
Some civ4 mods have a(n) orchard/grove improvement, perhaps it would be suitable improvement for berry resources when a farm/plantation does not fit well!

**Comment by raystuttgart** [comment]
Solved now in "Yields".
("Cocoa Plantation" has been turned into more general "Fruit Plantation".)
