### ISSUE TITLE
Ship from Europe cannot go to the city which only sea tile is shallow coast

### ISSUE THREAD

**Issue by windock** [We-the-People-civ4col-mod/Mod#608]
Develop2 branch. "unsupported steam version"

Steps to reproduce:
1) settle the only city on a coast, so that it's only sea access is through shallow coast
2) have a ship in Europe
3) Sail to the New World. There is no destination for that ship. However, I can go to the New World through clicking on the sea
4) When ship is in the New World, it can path to the city correctly through "go to" popup.

![shallow-coast-city](https://user-images.githubusercontent.com/79237/183286747-1a5efd34-c013-4d18-b401-4175571d4c7e.png)
![europ-shallow-coast](https://user-images.githubusercontent.com/79237/183286775-c7d59cdd-0589-41e0-bdab-86e3fdbb625d.png)
[AutoSave_AD-1503.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9276610/AutoSave_AD-1503.zip)

if you go to the world builder and delete shallow coast, leaving a regular coast in it's place, then ship can go from Europe to the city directly.

Following is a save file with a regular coast:

![europe-regular-coast](https://user-images.githubusercontent.com/79237/183286969-f7a92d85-b73f-43e5-afea-5213bfb188e2.png)
[windock AD-1503.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9276617/windock.AD-1503.zip)

**Comment by devolution79** [comment]
Confirming, it is caused by CvCity::isEuropeAccessable() returning false since the function fails to recognize the addition of the shallow coast terrain type

**Comment by raystuttgart** [comment]
Sounds to be relatively easy to fix by adding an or with "**TERRAIN_SHALLOW_COAST**".

-----------

But if we fix it like this, what happens if all Coast plots are just "Shallow Coast" and the Ship that checks it cannot enter Shallow Coast?

I think we need to implement this method additionally:
`CvCity::isEuropeAccessableShallowCoast()` 

-----------

This here might the default check done first from the logic to travel to Colonies:
`CvCity::isEuropeAccessable() `

And **if it fails** we may check if the Unit **can enter Shallow Coast** and if yes also try
`CvCity::isEuropeAccessableShallowCoast() `

**Comment by windock** [comment]
Thank you, guys. Five me some time, I will try to fix it myself.

**Comment by devolution79** [comment]
IMHO the only "real fix" is to perform full pathfinding.

**Comment by raystuttgart** [comment]
@devolution79 
That "real fix" is beyond my skills then. I was more thinking of an easy solution.
But since I know that you arleady work on pathfinding I am certain you will find a good solution.

**Comment by devolution79** [comment]
Here's a quick analysis of the issue:

This is the code that determines the valid targets of a ship in Europe (note that the code for the other ports are identical)
CvEuropeScreen.py
`
while (city):
			if (city.isCoastal(gc.getMIN_WATER_SIZE_FOR_OCEAN()) and city.isEuropeAccessable()):
				if unit.getGroup().generatePath(plotEast, city.plot(), 0, false, None):
					self.CityPlotList.append([city, None])
				elif unit.getGroup().generatePath(plotWest, city.plot(), 0, false, None):
					self.CityPlotList.append([city, None])
			(city, iter) = player.nextCity(iter, false)
`
No pathfinding is performed here since the only check is for the city beingc coastal cand the previously mentioned CvCity::isEuropeAccessable. This is honestly a  bit puzzling to me since it seems like the obvious solution (maybe they had performance issues with larger maps but that could be solved by caching the result since the result in fixed and hence only need to be computed once)

Another argument in favor of PF is the following:

Allow the following as targets
- Cities that are only reachable through large rivers 
- Cities that are reachable only through another friendly city or fort (acting as a canal) or through an actual canal!

Disallow the following targets:
- Cities that are blocked by terrain or features suchs as shallow coast or reef

Note that all of these are considered in the context of each individual ship and thus could depend on the ship class and even promotions etc.

**Comment by devolution79** [comment]
Changing the topic a little, but I realize that we have another recently added features that we need to take into account and that is the port capacity. The way it works now is that pathfinding to a target will fail if the city is already at max capacity. I propose that we add another pathfinding flag to allow the capacity to be ignored so that we can still dispatch ships from Europe to the target (rationale: since the capacity is largely a temporary blocker and thus may no longer apply several turns later as the ship is about to enter the port)

**Comment by raystuttgart** [comment]
Thanks for looking into this. 👍

**Comment by devolution79** [comment]
Ok, so a simple and correct fix is to replace the python code with the following:

```
		while (city):
			if unit.getGroup().generatePath(plotEast, city.plot(), 0, false, None):
				self.CityPlotList.append([city, None])
 			elif unit.getGroup().generatePath(plotWest, city.plot(), 0, false, None):
 				self.CityPlotList.append([city, None])
			(city, iter) = player.nextCity(iter, false)
```

... and now we can even pathfind to cities that are only accessable by large rivers!

Do note that it's possible that this will result in noticeable lag on gigaantic maps unless we implement some form of cacheing

**Comment by windock** [comment]
@devolution79 Will you fix the issue yourself, or you want me to implement it?

**Comment by raystuttgart** [comment]
@devolution79 
Could you please fix this?

Otherwise please notify me or @windock to take care of it.

**Comment by raystuttgart** [comment]
@windock 
Please take a look at it and try to fix it. 👍

**Comment by windock** [comment]
Guys, sorry, but I cannot help in the near future. I live in Kyiv, Ukraine, and we have about 6 hours of electricity per day, even less of internet. 
I have an office with a generator and Starlink, but cannot use it for anything but work-related.

I hope to get back to modding when the situation improves, but it is pretty far away in the future, at least a year.

**Comment by ArchdukeLiet** [comment]
Good luck there, hopefully things will normalise around there as soon as possible.

**Comment by raystuttgart** [comment]
I will take care of it. :thumbsup:

Considering Gameplay:
Actually it should allow to set all Coastal Cities as destinations even if they cannot be entered by the ship.
Because it may be the nearest target and you simply may want to drop of Units on Land or you know that the harbour will get accessible again.

Thus "full pathfinding" is not necessary and would probably cause trouble that a City cannot be selected simply becaue the harbour is full.
All that is actually needed is really to have an or with "Shallow Coast".

e.g. By the time you start sailing away from Europe, the harbour is full.
But that does not mean that the harbour will still be full once you arrive.

----

It reallly is the best solution for gameplay.
(Anything else would probalby cause issues with the Harbour System.)

And it will be perfrormant.
(Since the additional check for "Shallo Coast" will hardly change anything.)

**Comment by raystuttgart** [comment]
**Edit:**
It is fixed and tested.
It behaves as it should.

**Comment by MrZorG33** [comment]
continuation of the story ["the path from Europe to a colony with shallow waters"](https://github.com/We-the-People-civ4col-mod/Mod/issues/608)

my West Indiaman may suddenly swim to a colony on a shallow water.
![image](https://user-images.githubusercontent.com/61798883/209698347-4b841f8b-668b-47d6-8294-879806498ecf.png)

![image](https://user-images.githubusercontent.com/61798883/209697820-0f458ad4-f842-4cda-a3a8-282ba66e22fb.png)

the thing is that if you send a ship that can sail in shallow water to any of the colonies first, including those with shallow water, then other ships can be sent to such colonies (they will be present in the destination selection list).
![image](https://user-images.githubusercontent.com/61798883/209698665-4cbc829d-2952-4a4d-9e30-fd80c643f7fa.png)

but if you first send a ship from Europe that is not designed to sail in shallow water, then other ships that can do this will not see colonies with shallow water in the list of destinations.
![image](https://user-images.githubusercontent.com/61798883/209699340-731be5a4-fce8-403b-b42c-75ff56c84ba8.png)

**Comment by raystuttgart** [comment]
Please check if it is related to "Harbour Capacity" in any way.

**Comment by MrZorG33** [comment]
The West Indiaman cannot swim in shallow water. the capacity of the harbor has nothing to do with it. if you are talking about a caravel, then I have only two ships that are in the screenshots.

**Comment by raystuttgart** [comment]
Yeah I can confirm it. 👍 
Also when you exit Europe Screen and enter again it will work again.

It is related to the "generate Path" of the Ship that cannot enter the City.
The paths are somehow re-used then for the other Ship which then also does not see it.

It really depends in which order you click:

**Case OK**
1. Ship that can sail in Shallow Water --> City will be displayed
2. Ship that cannot sail in Shallow Water --> City will not be displayed
Result: Working as expected

**Case Not OK**
1. Ship that cannot sail in Shallow Water --> City will not be displayed
2. Ship that **can** sail in Shallow Water --> City will not be displayed <----- **BUG**
Result: Bug

**Comment by MrZorG33** [comment]
hmm.. in my second screenshot you can see that a ship that can't sail in shallow water can only reach a colony with a coast in shallow water.
Result: Bug

**Comment by raystuttgart** [comment]
The thing is that I think it reuses the "generated Path" of the Previous Ship. 
It does not really seem to generate it cleanly every time ...

**Comment by raystuttgart** [comment]
I also found out that it only reuses the already "generated Path" until a Ship is actually send to the new World.

**Comment by raystuttgart** [comment]
Ok, I now really fixed it. :)
Please get the latest updated.
