### ISSUE TITLE
Lan Connection issues

### ISSUE THREAD

**Issue by DrakeHawkins** [We-the-People-civ4col-mod/Mod#626]
Thanks for the great MOD!!

my son and i are trying to play multiplayer with the mod.  We can connect find with the base game. 
when we load the mod we can no longer find one another's games in the lobby.

we have checked for the mod names and folders names to be identical. I'm sure i am missing something as this seems not to have been brought up on this forum.  Any feedback on what may be wrong?

thanks for your time! 

Drake Hawkins

**Comment by Nightinggale** [comment]
It's because the steam version added the lobby, but by doing so they broke lan support as well as causing various issues for mods. Luckily this is fixable by downgrading.
[Guide on how to get the non-lobby version from steam](https://forums.civfanatics.com/threads/important-for-all-steam-users-follow-these-instructions-to-play-wtp-without-bugs.674675/)
If you do that, then you should unlock lan games and if everything else fails, direct IP games should work. If you aren't on the same local network (like if not all players are on the same lan), then use hamachi to create a virtual lan across the internet.

**Comment by raystuttgart** [comment]
I think this is clarified now.
It is also not a general issue of the mod.
