### ISSUE TITLE
Political refugees should become experts by hard work...

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#68]
I was just checking the properties of the Political refugees... And they can't become expert by hard labor... I don't think that this is fit for them... After all, they should become elder statesmen if they are placed at the city hall for enough time...

**Comment by ShadesOT** [comment]
... and learn medic, statesman and preacher faster than normal settlers
... and learn hard manual labor professions slower than normal settlers (farmer, miner, etc ...)
... and learn the rest of the professions slightly faster than normal settlers,

... because I picture them to be smart but no hard manual laborers.

**Comment by raystuttgart** [comment]
Should I change this or not?
It is really easy XML change though that everybody could do

**Comment by Nightinggale** [comment]
I would vote for allowing them to use LbD, though I do not consider this to be a major issue.

**Comment by raystuttgart** [comment]
It is not a major issue, but it might annoy some people and is hard to explain as well, that the Unit cannot become a Specialist.

**Comment by Drunk-Monk** [comment]
I think they should have LbD, and be capable of learning faster when it comes to professions like Elder Statesman, Doctor, Preacher. This is suggested by there colnopedia information.

**Comment by raystuttgart** [comment]
I am fine to configure the Unit to use LbD.

But I really will not code changes into LbD DLL logic just because of 1 single Unit.
Please let us not code changes of core feature functionality just because of 1 single Unit.

That would be wasted effort and opens all doors for rare bugs and exceptions unexperienced modders could make when adjusting XML or trying to creat modmods.

**Comment by raystuttgart** [comment]
By the way:
I just saw that they should be "good students" meaning that education (in schools) should be a bit faster for them.
Makes more sense to me than "Learning by Doing" (meaning real work) being faster for them.
