### ISSUE TITLE
The promotion "High-Sea Fisherman" is useless for ships that can only defend.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#69]
Either this promotion is removed from such ships, or the "can only defend" attribute should be changed to "can only attack wild animals".

**Comment by NoFreeUsernameDammit** [comment]
To be honest, the promotion is, at current state, useless. All but coastal and fishing boats, which can't gain any promotions, have around 10 times higher strength than wild animals or even more, so they can go through combat without a scratch most of the time, so promotion against them is a waste.

**Comment by Nightinggale** [comment]
Removing a promotion will screw up the promotion indexes already in savegames. Even worse changing the number of promotions will change the length of promotion arrays, which in turn will render savegames impossible to read.

In short: even if it could be tempting, we shouldn't remove any promotions right now.

This is one of the issues which can be fixed with proposal in #46 as in it takes xml changes into account when reading savegames and can convert to the new indexes when loading.

**Comment by abmpicoli** [comment]
Maybe we could change the promotion a little? -1xp needed for promotions would make for early unit development, and after the unit is high level, it would become less and less important... sort of making the spirit of the promotion the same...

**Comment by raystuttgart** [comment]
Promotions are going to be rebuilt anyways (see forum).
This issue has been noticed and discussed as well.
