### ISSUE TITLE
CDT End of turn

### ISSUE THREAD

**Issue by Silversides2** [We-the-People-civ4col-mod/Mod#691]
Click end turn and after a few AI moves the game CDT's, ive gone through all my units to stop them moving but i dont know whats causing this issue.
Im using the current public release and ive tried this on both my desktop and laptop installs with the same result.

Any ideas on how to fix?
[John The Danish  AD-1694-MayCRASH3.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/10347692/John.The.Danish.AD-1694-MayCRASH3.zip)

**Comment by Nightinggale** [comment]
Known bug, which has been fixed in the development version. For the sake of you continuing your savegame I attached a custom DLL with the fix. Note that using this will make your game unable to play in network games unless everybody use this file.
[WTP DLL 3.0.1+crash fix.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/10347836/WTP.DLL.3.0.1%2Bcrash.fix.zip)

**Comment by Silversides2** [comment]
Perfect, thanks for your hard work
