### ISSUE TITLE
AI doesn't seem to know how to farm shipwrecks.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#70]
I see all the times the english, for example, with lots of shipwrecks around them. They don't seem to bother to farm the shipwrecks at all... even if , to my knowledge, all shipwrecks have positive consequences...

Probably because their script tells only to send ships mindless to europe.

**Comment by Nightinggale** [comment]
Somewhere in the source code (most likely CvUnitAI.cpp) there is code to explore ruins. This is only triggered by UNITAI_SCOUT. The answer to this bug is likely to figure out the UnitAI for exploring ships and make it enter the same code as UNITAI_SCOUT, but for water. It's an open question if it can use the same or needs some copy pasting.

We could make a fun experiment. Allow AI scouts to walk on water. They should explore the map and get the shipwrecks because the AI can't tell shipwrecks from ruins.

**Comment by abmpicoli** [comment]
Oh, no, please :) One of the coolest things about shipwrecks is that we can add navigator1/2 quickly to the ships... 

I think it is better to change the sailing AI to be a little more smart , to do exactly what we players do: Only move to europe when there is only one movement left, and use whatever movements left for exploring the map. Although I reckon that this is a tricky AI code to do...

**Comment by Nightinggale** [comment]
The AI can assign different tasks to ships and one of them is exploring. That will work kind of like the scout, except it's ignorant about goodyhuts (which is the code word for ruins and shipwrecks). If the AI learns not to ignore them, it will explore the map like scouts explore. It's something to keep in mind and I'm wondering about this aspect too because the AI will likely try to get all the shipwrecks if it's aware of them. We can't implement this without considering game balance.

**Comment by ErikSandbraaten** [comment]
The scout AI uses the function CvUnitAI::AI_goody() to determine which visible goody to path to.
We could adapt this function and have empty ships hunt for goodies if they have nothing better to do (that is unlikely for transport ships since they have to continuously ferry colonists and goods around since cargo capacity is a precious resource)
We could make a separate scout ship AI that would be a good fit for the sloop that would focus on exploration and goody hunting. UNITAI_SCOUT_SEA ?

**Comment by Nightinggale** [comment]
We may also consider not hardcoding UNITAI to a specific domain and instead have them use the same domain as the unit. We could also consider a list of UNITAIs for units, which gives them tasks with a priority. That way the AI can set ships to transport colonists, but if it has an over capacity of ships, it can assign one to scouting. It can then revert back to the top priority (transport) once it requires extra transport capacity.

**Comment by ErikSandbraaten** [comment]
In a test build I have allowed AI ships to use UNITAI_SCOUT (along with some other changes to deal with the domain differences). The result is that the AI is capable of collecting the ocean goodies.

**Comment by alexandr-** [comment]
Can this also (positively) influence "Finding the pacific"-quest?

**Comment by ErikSandbraaten** [comment]
The AI is currently not able to target any of the quests. It may however "win" by pure accident if it "stumbles" upon the quest fulfillment criteria.
I think that teaching the AI to explore for ocean goodies should at least help somewhat.

**Comment by ErikSandbraaten** [comment]
AI support implemented in 2.8.2
