### ISSUE TITLE
cosmetic: make "goody huts"  glow.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#71]
I always find ancient ruins / burial grounds difficult to see , even if the map is cleared. It would be nice if they were highlighted somehow... Maybe by making them "glow"...

**Comment by alexandr-** [comment]
Doesnt a yellow circle most of the time mark huts and temples?

**Comment by abmpicoli** [comment]
> 
> 
> Doesnt a yellow circle most of the time mark huts and temples?

Only when the scout is near it. Not in the map itself.

**Comment by Nightinggale** [comment]
There is a function for CvPlot where you can set the marker. Vanilla uses circles, but there are a lot of shapes available. Also there is a free choice of color. The only real limitation is that one plot can only have one marker.

We can add different overlays if we want. Adding a bonus highlight would be a good idea because some of them can be hard to spot without adding the bonus "flags".

**Comment by orlanth** [comment]
A map overlay that can show highlight circles for selectable options of interest sounds great. Maybe one each showing goodyhuts and Bonuses.

**Comment by raystuttgart** [comment]
Just implemented it yesterday as Game Option.
