### ISSUE TITLE
Make a coordinate class instead of using x,y variables

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#719]
One aspect of good C++ coding practice, which we tend to lack is to make classes for variables, which logically fits together as a set. Perhaps the most obvious candidate for such a class is the (X, Y) plot coordinates. They are passed around as ints. Not only will this not be type safe, it logically split the two variables like you want X from one plot and Y from another.

Putting them together as one class means it becomes a single argument in a function call and there shouldn't be a risk of bugs with X from one plot and Y from another. Also it results in less code to be written overall, particularly if we overload operators like == and +. Adding plot() to get the plot of the coordinates in question (or NULL) also helps towards clean code.

One part of the coordinates, which is somewhat nasty is the global defined INVALID_PLOT_COORD. While we can likely not change this due to exe compatibility (I think the exe is using this one), placing it inside isValid() makes the general code cleaner with less risk of bugs.

**Comment by ArchdukeLiet** [comment]
Would this affect loading times and if so, would it increase or decrease?

**Comment by Nightinggale** [comment]
This will likely not have any performance impact whatsoever as technically the CPU will still have the same workload. It is aimed at clean code, which in turn should make it faster to write code and reduce the risk of bugs.

**Comment by jo-oe** [comment]
I have tried to implement this change because I'd like to build on it.
As this is my first try at some of the more interesting things in C++ (overloading operators etc.), I'd be happy if eg. Nightinggale could have a look at it. I tried to keep it as simple as possible, unfortunately I had to stick with int for the coordinates (even though short would be enough, it does not allow the "INVALID_PLOT_COORDINATES" value).

Any other optimizations are welcome, as the functions here will probably be quite critical to performance.

Note that we could also add the functions to Reader and Writer, but then we would probably completely lose savegame compatibility. So in case we want to do that, we might want do merge this before 4.0 release ... otherwise I have no problem postponing the merge to a later version.

**Comment by jo-oe** [comment]
[cross-post from discord:]
There are a few fixes from devolution in the "optimizations2" branch, I also did several code changes in "coordinate_class" branch (and merged optimizations2 into it, because we both worked on the same files and functions).
At the moment, as far as I can see, there are no significant crashing bugs in that branch. But as I also worked on some code streamlining because it helped me through the merge, there could always be smaller gameplay bugs introduced.

I would now like to suggest merging those changes into New_Hope _before_ the beta.
My reasons:
1) Quite a lot of core files and some core functions have been changed. Continuing to work on seperate branches for months (until after 4.0 final) will surely cause new merge conflicts.
2) Testing for gameplay bugs is best done by playing. People will start playing the beta and we will get feedback on if we broke anything. And it will be a beta after all ...

I understand that merging new code right before a release is controversial. But please also consider those reasons mentioned above.
I would like to merge maybe tonight so there is still time to prepare the release files (compile and pack) tomorrow.

**Comment by jo-oe** [comment]
merged
