### ISSUE TITLE
Shipwrecks and bonuses are being created on ice.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#73]
Just detected that shipwrecks are appearing under the ice.
![image](https://user-images.githubusercontent.com/1733170/45718371-26b79a00-bb73-11e8-839b-70ac0a7348f9.png)

**Comment by Nightinggale** [comment]
Looks like the issue is with CvMapGenerator::canPlaceGoodyAt(). 

Most likely this will do the trick (untested)

```cpp
if (pPlot->getFeatureType() == FEATURE_ICE)
{
	return false;
}

```

However FEATURE_ICE is not part of the enum, meaning it should be GC.getDefineINT("FEATURE_ICE"), but that's slow. It's likely better to wait for the enum generation or at least add FEATURE_ICE = 0, to the enum. FEATURE_ICE is 0 with the current xml file but it would be kind of fragile to assume it will stay that way without any sort of verification.

**Comment by ErikSandbraaten** [comment]
During my investigation of this issue I discovered that ice is placed by the map generation script (FaireWeather) after the goodies has been placed. The correct fix is thus to move the goody generation to after the "afterGeneration" call has completed. As a side benefit, we can also fix the related issue where bonus resourced are placed under ice if we also move addBonuses().

**Comment by ErikSandbraaten** [comment]
Changed the title to also include the bonuses under ice issue.

**Comment by Nightinggale** [comment]
I removed the xml tag as it looks like it's a pure coding issue. Obviously the correct solution is to not do post generation tasks on the map before the map script is done. It should also rely on the more generic code like checking if plots are isImpassable, though we should make sure we don't remove bonuses from mountain peaks due to being too generic.

**Comment by ErikSandbraaten** [comment]
Yeah, I feel that we may have to overhaul the map script and\or map generation but for now it seems sufficient to add the extra check for an impassable feature and to move the bonus\goody generation.
