### ISSUE TITLE
city screen: profession list not sorted alphabetically

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#739]
The pull-down menu for giving colonists a new profession is not sorted alphabetically. Listing on this list the outdoor and indoor professions separately should of course be kept.

**Comment by Nightinggale** [comment]
It is sorted by ProfessionTypes as in the order they are written in xml. It has always been like that. This allows us to fully control the order, which means we can put simple ones on top while "late gate" professions are further down.

If we want to change that, then it's a sign decision we should agree on. I will say that it could make sense to make a new profession selection window where rather than the popup we have now it becomes a pulldown menu. Granted it has way less information as you only see the name in the list, but the pulldown menus has one awesome hidden feature, which is once clicked, if you press a character key on the keyboard, the selection will jump to the first list item starting with that character. So for instance if we click and press O, it will jump to "Ore Miner".

I'm not entirely sure I like the idea of the pulldown because it will display so much less, but perhaps we can be creative and work around that. Also nothing prevents us from having both and then add some sort of selector feature (not sure how yet).

**Comment by raystuttgart** [comment]
As Nightinggale said, it is listed **according to the order in Civ4ProfessionInfos.xml**.
**Listing alphabetically would be a bad idea**, because now similar Professions in same buildings can be kept logically together.

Let us please keep the system as it is.
I really would not want to have them listed alphabetically.

**Comment by raystuttgart** [comment]
Can we please close this?
