### ISSUE TITLE
missing profession for YIELD_PIG_LEATHER

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#740]
ATM there is no profession for the production of the yield Pig Leather Aprons (YIELD_PIG_LEATHER) set up. 

Unit (UNIT_LEATHER_TAYLOR =Master Leatherworker ?) and building (BUILDING_LEATHER_PADDER_HOUSE =Leather Padder's House ?) are yet unclear.

Taking into account that we are adding lined boots while not even having shoes or boots indicates that a closer look at the leather business will improve the game experience. (if we need an open building slot in town check my earlier issue re: charcoaler #737)

**Comment by raystuttgart** [comment]
Hi Fürtbischof, there is no missing profession fot the Pig Leather Aprons, see here.

![Civ4ScreenShot0007](https://user-images.githubusercontent.com/59391125/219288005-a006935d-2a49-4515-8d87-3fbfeab55d9b.JPG)

**Comment by raystuttgart** [comment]
Otherwise if somebody wants to change the Buildings and Yields and feels he will get it nicely balanced go along and improve it. I will not work on this again, since I feel it was hard enough to achieve what was already created without changing it again.

Also I don`t always feel changing stuff like 1 year after something was created and massive effort was invested.
Why not suggest changes while the concept is still in work and things can be changed easily ?

**Comment by Fuerstbischof** [comment]
Yes, you're right. My fault. :-(

I got the wrong impression after reading the desription of the profession which can be found in CIV4GameText_WTP_New_Professions_utf8:

TXT_KEY_PROFESSION_TANNER_PIG_STRATEGY
[COLOR_HIGHLIGHT_TEXT]Pigskin tanners[COLOR_REVERT] can work in the [LINK=BUILDING_TANNERS_HOUSE]tanner's house[\LINK] or one of its upgrades to produce [LINK=YIELD_PIG_SKINS]pigskins[\LINK] from [LINK=YIELD_PIGS]pigs[\LINK]. [LINK=UNIT_TANNER_PIG]Master pigskin tanners[\LINK] excel at this craft, and can greatly boost your production of pigskin.

Yep, the text was obviously copy-pasted from the pig butcher. :-(

CIV4GameText_WTP_New_Yields_utf8:

TXT_KEY_YIELD_PIG_LEATHER_PEDIA
[TAB][H1]Pig Leather Aprons[\H1][PARAGRAPH:2][BOLDStrategy :[\BOLD][NEWLINE][COLOR_HIGHLIGHT_TEXT]Pig leather aprons[COLOR_REVERT] are made from [LINK=YIELD_PIG_SKINS]pigskins[\LINK]. To do this, a colonist needs to have the [LINK=PROFESSION_TAILOR_LEATHER]leather tailor[\LINK] profession in the [LINK=BUILDING_TAYLORS_HOUSE]tailor's house[\LINK] or one of its upgrades. The output of pig leather aprons can be doubled by commissioning [LINK=UNIT_TAILOR]master tailors[\LINK] who can be hired in Europe.[PARAGRAPH:2][BOLD]Background :[\BOLD][NEWLINE]Pig leather aprons are hard-wearing work clothing, used by blacksmiths to block sparks from the forge and by butchers in case knives slip.</English>

**Comment by Fuerstbischof** [comment]
I'll commit a revised text later.

**Comment by raystuttgart** [comment]
Maybe the Professios should also be renamed. (Thinking ...)

Currently they have the Yield they **consume** in brackets.
But it might be better to have the Yield they **produce** in brackets.

**e.g. instead of this:**
Tanner (Cattle Hides)
Tanner (Pig Skins)

**To write something like this:**
Tanner (Quality Cattle Leather)
Tanner (Pig Leather Aprons)

----

This may have caused the confusion.

**Comment by raystuttgart** [comment]
I think we can close this here since there is no actual bug.
Improving naming of Professions may happen anytime anyways.
