### ISSUE TITLE
wrong painting used for FF Robert Bakewell

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#753]
https://de.wikipedia.org/wiki/Robert_Bakewell_(Agrarwissenschaftler)

As can been seen by looking at his German wikipedia entry, the painting used to represent him in WTP actually shows Thomas Coke, 1st Earl of Leicester (1754-1842) 

https://en.wikipedia.org/wiki/Robert_Bakewell_(agriculturalist)

Although quality is not great we should stick with the original:
https://commons.wikimedia.org/wiki/File:John_Boultbee_(1753%E2%80%931812)_-_Robert_Bakewell_-_NPG_5949_-_National_Portrait_Gallery.jpg

**Comment by raystuttgart** [comment]
It would really need a high quality image to create a FF image.
Otherwise it would look plain bad.

I rather have an historically incorrect nice image than a historically correct ugly one.
(99.9% of the players would not notice a wrong image but will notice an ugly one.)

----

Once somebody finds a good hirstorically correct image of Bakewell, let me or Schmiddie know. 👍 
Creating a FF image from a good base image takes just about an hour, so it is manageable. 

Until then, let us please keep the current image.

**Comment by MrZorG33** [comment]
I suggest closing until a suitable image appears.
