### ISSUE TITLE
FF William Brewster: in or out?

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#756]
William Brewster had been replaced earlier by John Maurice, Prince of Nassau-Siegen, although the tag itself was not renamed. The traits of John Maurice were tailored to his feats during his regency in Brazil, expanding the sugar plantations by exploiting African slaves on a grand scale.

During development past release 3.01 John Maurice got his own tag: FATHER_JOHN_MAURICE. Sadly, the traits were not copied over, some new were made up. Nonetheless, not all traces to the tag FATHER_WILLIAM_BREWSTER were deleted, so that this FF, thanks to the vanilla files, was still in the game. Last week the tag FATHER_WILLIAM_BREWSTER was fully added back to the game and William Brewster, although being an elder from the famous Mayflower voyage and thus being prominently suited to be a religious or political FF, is now a trade FF whose traits are those of John Maurice.

Do we want to keep William Brewster? If we want to keep him, what type of FF do we want him to be?

**Comment by raystuttgart** [comment]
Sorry I am totally confused.

William Brewster is still in the mod.
Why discuss to remove him?
![Civ4ScreenShot0008](https://user-images.githubusercontent.com/59391125/221366292-09b29399-113d-43f8-a5c0-71c1f38c0181.JPG)

**Comment by raystuttgart** [comment]
**By the way:**
A lot of rebalancing had happened in the last 2 years.
So really please do not expect the FFs to be like 2 years ago.

i.e. Some **Cross-Bonusses** had been **removed** since there had been **just too many** of those.
(The mod was flooded by FFs giving cross Bonusses.)

**Comment by MrZorG33** [comment]
I added a few FF related tags because they were missing from the mod and couldn't be translated. blocks about these FFs have been carried over from vanilla as they exist there, unchanged. I just added a translation into Russian.

_and by the way, take the trouble to answer my question on the forum, I wrote you a message a long time ago._

**Comment by raystuttgart** [comment]
**Edit:**

I checked the XMLs of an old version of "New Hope" that is about 1 month old.
**William Brewster** was definitely not changed this month.

The balancing change to turn him into an Economical FF was thus older. I think it was in last December.
(As I said, I think it was caused by the internal "too many crosses FF discussion" started by the beta testers.)

-----

**@MrZorG33** 
But as far as I saw you just added TXT_KEYs.
The balancing of William Brewster was not changed by that.

-----

Otherwise if somebody feels that the balancing should be improved / changed, go ahead and give it a try.
But we should ensure:

1. Each Production chain has a FF (so they are all equally powerful)
2. We do not end up with so many "Crosses FFs" again.

------

Maybe the balancing of those 2 might be swapped though to make it a bit more immersive.

FATHER_JOHN_MAURICE
FATHER_WILLIAM_BREWSTER

-------

**Comment:**
Please **balance for gameplay** though.
(Balancing for pure immersion will not make the mod better.)

**Comment by MrZorG33** [comment]
yes, I just added TXT_KEYs.

however, before doing a rebalance, it is worth discussing it with the team, and not doing it alone. otherwise everyone will start to remake the mod as he pleases and work on the mod will stop.

**Comment by raystuttgart** [comment]
**Yes fully agree:**
Before doing major balancing changes - everything that is not a real fix - please discuss first. 👍 
(It is probably not possible to ask everybody but at least **ask the beta testers in the team** then.)

**Comment by MrZorG33** [comment]
since we figured out that FF William Brewster is still in the game, I don't see the point in keeping it open.
