### ISSUE TITLE
Non-functioning Leader trait

### ISSUE THREAD

**Issue by Tablemat** [We-the-People-civ4col-mod/Mod#808]
Jens Munk and Martim Afonso de Sousa both have the Resourceful trait, which amongst other details provides +2 stone, +2 clay, + 2 tools and +2 production. Only the production element is functioning.

**Comment by Nightinggale** [comment]
The xml settings get cached and ends up in being accessed through CvPlayer::getCityExtraYield. While not the prettiest cache I have ever seen, it is there and is likely working as intended.

The problem is that getCityExtraYield is applied to the city plot, but only if it's non-cargo or the plot already produce said yield. Even worse, being the city plot, it produces food and one more yield so if it produces say cotton, any cargo yield, which isn't food or cotton will be set to 0 **_AFTER_** getCityExtraYield is applied meaning even if the plot can produce the yields in question, it won't or it will only produce one of them. Hammers work because it's not a cargo yield.

The obvious fix is to move getCityExtraYield to apply to CvCity instead of CvPlot when there is a city on it. While that does seem to work, it completely screws over the production help text. It looks like step one in this bugfix is to clean up the yield production code in CvCity and allow the display code to call the same functions rather than copy pasting code, which then goes out of sync whenever something is altered.

On a side note, I always hated the vanilla approach to the help text because it is written in a way, which is so prone to breaking.

**Comment by Nightinggale** [comment]
Fixed. The production bonus has now been removed from the colony plot and is instead added to a new type of production called "from Leader".

Also reworked the help text to make it less prone to failing and if it fails, it is more likely to self report this through assert failures.
