### ISSUE TITLE
remove the "load from dock" button from the Galleon

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#825]
since very often players complain that their Galleon does not want to take colonists from the docks of Europe, I propose to remove this button from it. for example, a fishing boat does not have such a button, since it cannot transport colonists either.
![image](https://user-images.githubusercontent.com/61798883/232477587-1dd45669-11ab-45cc-ae8c-ff4bdef42995.png)

**Comment by raystuttgart** [comment]
I am **not** a fan of it, because who knows what somebody would like to **customize in his XML**.
Not having the Button does not solve the issue that people would try to load single Units manually either.

Also you could e.g. still load "Construction Supplies" with that Button.
And who knows what else we will add in the future.

In fact it may again cause problem report of people saying that the Button is missing.
As I said, the Button itself **IS** funtional - e.g. for "Construction Supplies".

**Summary:**
Removing that Button is **NOT** a solution in my opinion to players not understanding that the Ship cannot load Colonists.
It can later on in the past cause other potential issues - it is better to explain e.g. with Mouse Over (the Unit) as already suggested.

**Comment by MrZorG33** [comment]
yes, I forgot about Construction Supplies. ok, in that case, let's close.
