### ISSUE TITLE
Colopedia Goods and Materials entries needs fixed

### ISSUE THREAD

**Issue by dirlewagen** [We-the-People-civ4col-mod/Mod#837]
There are several entries under Goods and Materials that open a different entry than the one listed, or missing info

- [x] - Barley                        > plains link opens grassland
- [x] - Cattle                        > plains link opens prairie and the prairie link is not working
- [x] - Olives                        > plains link opens prairie
- [x] - Peanuts                     > plains link opens prairie
- [x] - Premium furs             > taiga link opens Northern forest
- [x] - Rapeseed                   > entry lacks a link to terrain and/or to rapeseed plants
- [x] - Rapeseed oil               > rapeseed link opens olives
- [x] - Upholstered furniture > it states it's made from leather but the upholster profession lists exotic wood and down as materials
- [x] - Whale fat                    > sperm whales link is not working
- [x] - Wild birds feathers      > wild birds link opens parrots (boobies, Canada goose, ducks, gulls, loons, penguins and vultures missing)

**Comment by MrZorG33** [comment]
1. Rapeseed > entry lacks a link to terrain and/or to rapeseed plants - here we need the help of translators (English, German, others)
2. Rapeseed oil > rapeseed link opens olives - bug not confirmed (may have been fixed before)
3. Upholstered furniture > it states it's made from leather but the upholster profession lists exotic wood and down as materials - bug not confirmed (may have been fixed before)

the rest is fixed in **develop**

**Comment by MrZorG33** [comment]
> Wild birds feathers > wild birds link opens parrots (boobies, Canada goose, ducks, gulls, loons, penguins and vultures missing)

added missed Toucans and Turkeys.
