### ISSUE TITLE
Canals do not connect to inland colonies

### ISSUE THREAD

**Issue by nblomkvist** [We-the-People-civ4col-mod/Mod#873]
According to the colopedia, canals are supposed to be able to connect inland colonies to water. This doesn't work. Ships can enter the canal, but they can not move from the canal into an inland colony adjacent to the canal.

I tried looking in the code and I think I saw two reasons:
1. Inland colonies are not on coastal tiles so they get no harbour space.
2. Ships are not allowed to enter colonies not on coastal tiles.

**Comment by raystuttgart** [comment]
Then colopedia is wrong - because they were only intended to connect e.g.

- Colonies at a Large River or a Lake to Coast --> City itself already has a harbour
- Colonies at Coast to a Large River or Lake --> City itself already has a harbour
- Large River to Lake, Large River to Coast, ... --> 2 water plots

So no bug - it is working as intendend.
(Everything else would have been an exploit and immersion breaking.)

So no, Canals never supposed to let Ships sail into Inland Colonies in the middle of the countryside or as an exploit for creating inland harbours.
Never tried to implement that - and also not what I personally use Canals for ... they were mainly intended for connecting e.g, Great Lakes on Amerikcas Gigantic or to bridge Panama Canal..

For actual inland colonies having a harbour we might one day implement this here:
https://forums.civfanatics.com/threads/port-district-updated.641846/

**Edit:**
Colopedia was adjusted.
