### ISSUE TITLE
Problems of automated scouts

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#874]
after reading the [forum](https://forums.civfanatics.com/threads/wtp-4-0-2-published-community-feedback.683126/post-16472322), I remembered that I had long wanted to create this ticket :)

automated scouts have a rather significant problem (it was already present in 3.x) - if there are ruins and guarded goodies nearby, then the scout will prefer to attack the goodies guards, rather than explore the ruins and undiscovered terrain. at the same time, the AI does not take into account that, as a rule, the guards are stronger than the scout (they are on the defensive, have bonuses to defense from tiles). but even if the scout lost the first battle, but survived (and the remaining hp is not critically low), on the next turn he can repeat the attack and is guaranteed to die. if the scout has a promotion that allows him to attack several times per turn, he will die on the same turn =)

Another problem is that if it is impossible to carry out exploration, the scout stops and goes into standby mode. this leads to the fact that it has to be looked for on the map. this is extremely inconvenient (especially on large maps) even with the help of an military adviser.

the optimal solution for all of the above would be if the scout just remained active and the player, depending on the situation, could decide what to do.

**Comment by devolution79** [comment]
The issue is likely that the scout AI ends up calling  CvUnitAI::AI_goodyRange or CvUnitAI::AI_goody which may queue a move command to a  nearby "goody" plot without checking for enemy units. This behavior was fine prior to the introduction of goody defenders but now it most likely turns AI scouts into kamikaze units :/

**Comment by devolution79** [comment]
The second issue is that the scout ends up idling if there are no viable plots to explore. I think this happens because the scout ends up calling getGroup()->pushMission(MISSION_SKIP); at the end of CvUnitAI::AI_scoutMove() thus ending its turn without waiting for new orders. I suppose we could print a message that states that exploration has been completed and also ensure that we do not enqueue MISSION_SKIP

**Comment by devolution79** [comment]
@MrZorG33 
I am experimenting with the following: When a scout has finished exploring the message  "your scout has finished exploration, awaiting new orders!" (obviously we'd replaced it with better phrasing a localization) is printed and the camera zooms to the unit.
Do you think this is an ok solution ?

**Comment by MrZorG33** [comment]
@devolution79 yes, you have proposed a great solution to this problem.

**Comment by MrZorG33** [comment]
Now another problem has appeared - automated Scouts have begun to ignore goodies.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/4240b4c0-653c-4805-855c-f9bacf5e9b28)

I'll attach the game save, maybe you'll need it.
[test2.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/12857251/test2.zip)

**Comment by MrZorG33** [comment]
The latest test games did not reveal this error. I'll close it for now.
