### ISSUE TITLE
Settlement Governor AI automating jobs should consider buy price when appropriate

### ISSUE THREAD

**Issue by cammcken** [We-the-People-civ4col-mod/Mod#880]
Often my automated colonists are gathering Ore from a quarry tile when I need Stone. I assume this is because Ore sell prices take a long time to drop below 2, whereas Stone sell prices rarely go above 1.

Although it's hard to tell the AI whether a player intends to sell a resource or use it elsewhere in the colony, would it be possible for the AI to check local needs? For example, if a settlement has a queued building that requires stone, could the settlement AI look at the _buy_ price of stone when deciding the best jobs?

**Comment by raystuttgart** [comment]
Yes, because that AI logic is primarily written **for the AI player** and there it makes the most sense to just consider sell prices.
(As AI is much better off producing stuff it can sell than producing stuff it will hardly ever buy anyways.)

Programming it in any way would weaken the AI players. Thus the issue is rejected.
(The effort for it is also in no relation to possible benefit - as it would only make the logic different not better.)
