### ISSUE TITLE
Game crashes at end of turn

### ISSUE THREAD

**Issue by andushow** [We-the-People-civ4col-mod/Mod#889]
playing 4.0.2 WTP mod, I've checked the logs folder:
init.log
PythonErr2.log
resmgr.log
xml.log
and found nothing.
I can submit the savegame, if necessary.

**Comment by Nightinggale** [comment]
A savegame is absolutely needed or I would have no idea what went wrong.

**Comment by andushow** [comment]
here you are.
[George Washington AD-1512-September.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/12774421/George.Washington.AD-1512-September.zip)

**Comment by Nightinggale** [comment]
Somehow there is a selection group with a unit node, which doesn't contain a unit. This crashes because the code assumes it to contain a unit. It's not the first time we have run into this issue so I decided the solution will be to systematically go through all cases of looping through selection groups and review each for potential crashes if there is a NULL unit.

**Comment by Nightinggale** [comment]
Fixed in next release.
