### ISSUE TITLE
Reproducible Crash when Moving a Citizen on/off Yerba Maté

### ISSUE THREAD

**Issue by MatthewForrester** [We-the-People-civ4col-mod/Mod#906]
**Setup**
WTP: 4.0.2 from Github.
Civ4Col: Steam original_release_unsupported beta
OS: Ubuntu 22.04.3

**Steps to reproduce**

1. Load the following save in WTP **4.0.2**:
[Yerba Crash.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/12900676/Yerba.Crash.ColonizationSave.zip)
2. Enable Resources mapmode (`Alt+R`)
2. Open the city of Barahona (should be just SE of the spawn point)
3. Move a citizen to the tile with the Yerba Maté resource, in the northwest quadrant. Instructing them to grow Yerba Maté may be necessary.
4. Move a citizen back to another tile, such as a fishing tile.

**Expected result**
The citizen works the tile.

**Actual result**
Crash to death.
Sometimes the crash happens after step 3 and sometimes after step 4. If you don't get a crash immediately, repeating steps 3 and 4 might trigger it.

**Screen Recording**
![YerbaMate](https://github.com/We-the-People-civ4col-mod/Mod/assets/38819845/243ef57e-57f6-4b05-a377-068e4d311967)

**Observations**
This may or may not be related to [this bug report filed earlier.](https://github.com/We-the-People-civ4col-mod/Mod/issues/894).

**Workaround**
In `steamapps/common/Civilization IV Colonization/Mods/WTP/Assets/XML/Art/CIV4ArtDefines_Bonus.xml` line 520, replace `<KFM>Art/Terrain/Resources/Yerba/Cnq.kfm</KFM>` with `<KFM/>`.

**Comment by raystuttgart** [comment]
@Schmiddie1979 : Could you look at this bug?
Probably again an issue with the NIF.

**Comment by Schmiddie1979** [comment]
I tried your savegame approx. 100x but it never crashed. 

However, the workaround is fine and works, but you should be careful with this. It is only required respectively necessary for bonus resources which have not yet been included in the PlotSystem.xml. There are some bonus resources which as far as they are not included and improved for the PlotSystem.xml (which makes them look much better with plantations etc.) which have no animation and therefore do not need the .kfm file. In these cases the .kfm file also should NOT be used and indeed often results in crash. Hence, your workaround is exactly what I would have done. When they have been "upgraded" for the use with the PlotSystem.xml. the kfm will be reactivated and can be used without crashes. But this needs some time because it is a time-consuming work and the one who does it needs to know what he is doing in this file. Maybe I finde the motivation some time to do this work for the missing bonus resources.

**Comment by raystuttgart** [comment]
**@Schmiddie1979** 
Maybe we should also for now remove the KFM from the XML to be sure?

**Comment by Schmiddie1979** [comment]
I currently work on it.
