### ISSUE TITLE
profession Prostitute - no bonuses

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#963]
Profession Prostitute does not receive bonuses from health and the level of rebel sentiment.

**Comment by raystuttgart** [comment]
That was implemented on **purpose**.
I explicitly exlcuded Happiness from these bonuses.

Otherwise Happiness would become OP / too abundant.
Thus it is working as designed.

There even was an issue about that years ago when people complained about Happiness being too easy to get.
Then we agreed to not give Happiness any bonusses from Health or Liberty Bells anymore.

Also Happiness is already generated from Production of Liberty Bells and Health.
So if we add the Bonusses to it ... it will double the effect more or less.

So let us please leave it as it is ... otherwise in Lategame Happiness will be too easy to get.
(Once your Liberty Bell Production or Health would go up you would have up to 50% extra.)

**Comment by MrZorG33** [comment]
I understand, the issue is closed.
